### ISSUE TITLE
Error with copy and cut in firefox

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#108]
Hello, I realized that the copy and cut functionality is giving an error in firefox. Follow the picture...

![image](https://user-images.githubusercontent.com/22320158/210360799-da5c8d31-78fc-4592-a8a5-060f5f79c7ae.png)

By the way, I would like to congratulate you for the initiative, it is a great project!!

**Comment by Hufe921** [comment]
I've just dealt with this problem.
But I recommend you to use chrome or chromium kernel browsers
thanks
