### ISSUE TITLE
导出word和文档末尾追加内容

### ISSUE THREAD

**Issue by xjlz875412495** [Hufe921/canvas-editor#120]
是否有导出word的方法？
有在文档末尾追加文字的API吗？

**Comment by xjlz875412495** [comment]
这两个功能预计什么时候可以发布出来呢

**Comment by GH-ID-CHC** [comment]
这两个功能预计什么时候可以发布出来呢

**Comment by douglasmatheus** [comment]
Hello, to add text to the end of the document I know there is the executeAppendElementList() method, like this:

`instance.command.executeAppendElementList([{ value: 'Example', type: 'text' }])`
