### ISSUE TITLE
自动分页模式能每页自动增加页头吗？或者页眉可以编辑也行？

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#132]
![image](https://user-images.githubusercontent.com/103647012/222038686-82548854-42df-4f65-a205-99500498e0d9.png)

**Comment by Hufe921** [comment]
现阶段实现固定格式页眉：[header配置](https://hufe.club/canvas-editor-docs/guide/option.html)
后续见README.md next features

**Comment by yicheng2022** [comment]
header配置我看了，貌似只能配置固定文字，现在还不能换行，在文字中间加入换行符也没有起作用。期待页眉编辑功能上线，加油！

**Comment by Hufe921** [comment]
v0.9.24
