### ISSUE TITLE
使用executeInsertElementList重复插入包含control的数据，control数据会重复多次渲染。

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#134]
![image](https://user-images.githubusercontent.com/103647012/222065418-a9c39a27-bf92-43a6-9aff-4c564015a60f.png)

**Comment by Hufe921** [comment]
麻烦提供一下重现问题的代码

**Comment by yicheng2022** [comment]
我知道怎么回事了哈，调用executeInsertElementList这个方法的时候，我传了多个Array
