### ISSUE TITLE
{占位符}后面按Enter，然后再按Backspace，会显示为：{占位符}占位符

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#141]

**Comment by Hufe921** [comment]
see:[[improve:control element input](https://github.com/Hufe921/canvas-editor/commit/dc54622258872630ff39309f2b1da3baee1f508f)](https://github.com/Hufe921/canvas-editor/commit/dc54622258872630ff39309f2b1da3baee1f508f)
