### ISSUE TITLE
文字重叠问题

### ISSUE THREAD

**Issue by xiangzhi127** [Hufe921/canvas-editor#144]
### version

0.9.19

### Steps to reproduce

原网站运行没问题，移到项目后运行出现文字重叠问题。

<img width="785" alt="image" src="https://user-images.githubusercontent.com/17473252/223681361-cc4d03ca-9417-4afe-9832-f59d0f173666.png">
<img width="574" alt="image" src="https://user-images.githubusercontent.com/17473252/223681810-962b476b-1042-432b-a19f-7c7d8439adc4.png">

### What is expected?

-

### What is actually happening?

-

**Comment by Hufe921** [comment]
使用版本0.9.19未能复现
![image](https://user-images.githubusercontent.com/27001251/223694471-37bab506-4f29-4a29-b237-4f2d9c25345b.png)

请提供一下你的浏览器和系统的信息及版本

**Comment by xiangzhi127** [comment]
<img width="704" alt="image" src="https://user-images.githubusercontent.com/17473252/223712270-adb5c96f-a953-4d4b-ac0d-1fd1bfd2f2c7.png">
<img width="310" alt="image" src="https://user-images.githubusercontent.com/17473252/223715268-490b68ad-abdd-458f-b905-046be1fdba63.png">

**Comment by Hufe921** [comment]
https://codesandbox.io/s/sad-kowalevski-bq409c?file=/src/App.vue
请确认是否运行正常

**Comment by xiangzhi127** [comment]
<img width="1424" alt="image" src="https://user-images.githubusercontent.com/17473252/223899667-801172d7-1ffb-4aa4-b99d-b640328dbe37.png">
正常展示。我试过重新初始化一个vue项目后，再安装canvasEditor也是正常显示的。难道和我现有项目有冲突？

**Comment by Hufe921** [comment]
canvas上下文独立一般不受影响。
尝试：
1. 提供一下项目使用的字体信息
2. 确保npm包使用了最新版本，可以通过
[`editorInstance.command.getValue`](http://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue)
查看版本是否正确，也可尝试删除项目node_modules后，重新安装最新版本之后再运行项目

**Comment by xiangzhi127** [comment]
感谢提供建议，找到原因了，项目全局样式问题。就是下面这段样式的影响的：
*,
*:before,
*:after {
  box-sizing: inherit;
  letter-spacing: 0.5px;
}

**Comment by Hufe921** [comment]
已复现。
原因：部分浏览器canvas上下文，会应用部分css样式。如：letterSpacing、wordSpacing、direction
解决方式：重置属性（待bug修复）
