### ISSUE TITLE
关于目录功能

### ISSUE THREAD

**Issue by zhoujingfu** [Hufe921/canvas-editor#149]
### What problem does this feature solve?

首先先膜拜一下大佬，感谢感谢。
最近也在看富文本的几个技术方向，放弃了slate.js，正好看到这个项目，很棒。
不知最近有没有目录功能的计划，简单看了下代码应该挺麻烦的。
我也尝试一下，争取提pr

### What does the proposed API look like?

目录功能可能涉及：
1. 正文/标题区分 设置api
2. 数字编号、符号  设置api
3. 页面内插入表目录 api
4. 获取目录结构 api（用于生成目录导航）

**Comment by Hufe921** [comment]
期待PR

**Comment by HoChine** [comment]
期待+1，很需要插入表目录api.
