### ISSUE TITLE
表格相关问题

### ISSUE THREAD

**Issue by blueskyzs** [Hufe921/canvas-editor#150]
### version

0.9.23

### Steps to reproduce

1、表格内文字现在不能垂直居中
2、纵向合并单元格后，在合并单元格内点击回车，第一行会跟着增高
3、表格整体没有复制功能

### What is expected?

 希望作者可以解决帮忙解决上述问题

### What is actually happening?

1、表格内文字现在不能垂直居中
2、纵向合并单元格后，在合并单元格内点击回车，第一行会跟着增高
3、表格整体没有复制功能

**Comment by Hufe921** [comment]
1. 表格内文字现在不能垂直居中：**后续加入该功能**
2. 纵向合并单元格后，在合并单元格内点击回车，第一行会跟着增高：**bug待修复**
3. 表格整体没有复制功能：**手动选区复制或在表格最后双击自动选区后复制-bug待修复**

**Comment by Hufe921** [comment]
v0.9.24
