### ISSUE TITLE
表格能否提供方法隐藏边框线？

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#152]
### What problem does this feature solve?

表格的边框线能否有方法可以隐藏呢？

### What does the proposed API look like?

表格的边框线能否有方法可以隐藏呢？

**Comment by Hufe921** [comment]
[v0.9.27](https://github.com/Hufe921/canvas-editor/commit/36f3bb42ce1b1b408763a59c2eab92adfc9783b0)
