### ISSUE TITLE
defaultTdHeight配置好像没有起作用

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#153]
### version

0.9.23

### Steps to reproduce

defaultTdHeight配置项没有起作用

### What is expected?

defaultTdHeight配置项起作用

### What is actually happening?

defaultTdHeight配置项没有起作用

**Comment by Hufe921** [comment]
0.9.28
相似issues：https://github.com/Hufe921/canvas-editor/issues/162
