### ISSUE TITLE
没有数据回写接口

### ISSUE THREAD

**Issue by blueskyzs** [Hufe921/canvas-editor#154]
### version

0.9.23

### Steps to reproduce

只有数据获取接口，没有数据回写接口

### What is expected?

希望作者大神能够提供

### What is actually happening?

只有数据获取接口，没有数据回写接口

**Comment by Hufe921** [comment]
详见文档：[根据光标插入元素](https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeinsertelementlist)
