### ISSUE TITLE
表格最后一列向左拖动到目标位置后，再将表格最后一列向右拖动到目标位置停止拖动表格位置没有变化 

### ISSUE THREAD

**Issue by davidliuzd** [Hufe921/canvas-editor#160]
### version

v0.9.27

### Steps to reproduce

1、拖动表格最后一列向左移动 ![image](https://github.com/davidliuzd/canvas-editor-issues/blob/main/230325/1-%E6%9C%80%E5%90%8E%E4%B8%80%E8%A1%8C%E5%90%91%E5%B7%A6%E7%A7%BB%E5%8A%A8.jpg)
2、向左拖动到目标位置后停止向左拖动 ![image](https://github.com/davidliuzd/canvas-editor-issues/blob/main/230325/2-%E5%90%91%E5%B7%A6%E7%A7%BB%E5%8A%A8%E5%88%B0%E7%9B%AE%E6%A0%87%E4%BD%8D%E7%BD%AE%E5%90%8E%E5%81%9C%E6%AD%A2%E5%90%91%E5%B7%A6%E6%8B%96%E5%8A%A8.jpg)
3、再次向右拖动到目标位置后，停止拖动 ![image](https://github.com/davidliuzd/canvas-editor-issues/blob/main/230325/3-%E5%90%91%E5%8F%B3%E7%A7%BB%E5%8A%A8%E5%88%B0%E7%9B%AE%E6%A0%87%E4%BD%8D%E7%BD%AE.jpg)
4、向右拖动到目标位置放下后表格位置未发生变化（期望位置在最后拖动位置）![image](https://github.com/davidliuzd/canvas-editor-issues/blob/main/230325/4-%E5%90%91%E5%8F%B3%E7%A7%BB%E5%8A%A8%E5%88%B0%E7%9B%AE%E6%A0%87%E4%BD%8D%E7%BD%AE%E6%94%BE%E4%B8%8B%E5%90%8E%E8%A1%A8%E6%A0%BC%E8%BF%98%E5%8E%9F%E5%88%B0%E6%AD%A5%E9%AA%A42%E7%9A%84%E4%BD%8D%E7%BD%AE.jpg)

### What is expected?

表格最后一列应该在步骤3的位置

### What is actually happening?

表格最后一列的位置还原了（步骤2），未发生位置变化

**Comment by tuburing** [comment]
步骤3向右拖拽应该是超出了页面，因此在拖动结束后，触发了判断条件，移动了最小宽度
