### ISSUE TITLE
当图片出现跨域时，无法执行打印

### ISSUE THREAD

**Issue by baseWalker** [Hufe921/canvas-editor#163]
### version

0.9.28

### Steps to reproduce

复制一个有服务端跨域限制图片，然后执行打印

### What is expected?

打印报错：Draw.ts:523 Uncaught (in promise) DOMException: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

### What is actually happening?

能正常打印

**Comment by Hufe921** [comment]
v0.9.29
