### ISSUE TITLE
如果用了右对齐后，再按Backspace键直接到上一行末尾了

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#164]
### version

0.9.28

### Steps to reproduce

1、将本行文字右对齐；
2、点击Backspace；

### What is expected?

往前缩进

### What is actually happening?

本行文字跳到上一行末尾了
![image](https://user-images.githubusercontent.com/103647012/228841442-9ce7f3ae-2ddf-411e-9aab-ab81662fc9a9.png)

**Comment by Hufe921** [comment]
1. 行首删除：
目前逻辑是删除换行符，效果是回退至上一行。
office的行为是：回退对齐方式（依次执行：右对齐=>居中对齐=>左对齐=>删除换行符）。------暂不作bug处理
2. bug：
在行首删除字符时，应该删除整行的对齐方式。------在此issue当作bug处理
