### ISSUE TITLE
表格文字显示异常

### ISSUE THREAD

**Issue by lefex** [Hufe921/canvas-editor#166]
### version

0.9.28

### Steps to reproduce

删除所有内容，然后插入表格，在第一个单元格输入文字

### What is expected?

正常排版

### What is actually happening?

文字排版异常
![image](https://user-images.githubusercontent.com/8437666/229102686-6e9a2660-ae05-411f-bae0-0d69f9796100.png)

### System Info

```shell
Chrome
```

**Comment by Hufe921** [comment]
v0.9.29
