### ISSUE TITLE
你好，可以直接导入个svg文件吗？

### ISSUE THREAD

**Issue by fanqieo** [Hufe921/canvas-editor#169]
### What problem does this feature solve?

你好，可以直接导入个svg文件吗，然后在上面做一些编辑？

### What does the proposed API look like?

你好，可以直接导入个svg文件吗，然后在上面做一些编辑？

**Comment by Hufe921** [comment]
可以插入svg作为图片元素 https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeimage
至于编辑svg，非本项目定位
