### ISSUE TITLE
Error with paste option in context menu in firefox

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#173]
### version

0.9.31

### Steps to reproduce

Open the context menu and select the paste option.

![image](https://user-images.githubusercontent.com/22320158/231528476-574aac2c-1326-43a1-bfb2-38a922c74cf3.png)

### What is expected?

Paste option in context menu works normally.

### What is actually happening?

Exception occurs: Uncaught (in promise) TypeError: navigator.clipboard.readText is not a function.

As shown in the previous image.

### System Info

```shell
System: Windows 11
Browser: Firefox 111.0.1
```

**Comment by tuburing** [comment]
Firefox only supports reading the clipboard in browser extensions, using the `clipboardRead` extension permission.
https://developer.mozilla.org/en-US/docs/Web/API/Clipboard/readText#browser_compatibility

**Comment by Hufe921** [comment]
Can use ctrl/⌘+v, it is recommended to use Chrome or Edge browser
