### ISSUE TITLE
关于更丰富自由的初始化配置控制。

### ISSUE THREAD

**Issue by 1019058432** [Hufe921/canvas-editor#180]
### What problem does this feature solve?

通过自由选择控制渲染配置，能产生自由的布局与更大的应用场景。
此前，我一直在寻找一款可自由控制光标和虚拟键盘弹出(移动端)的富文本编辑器、我使用了contentEditable来实现但效果不是很好（受到输入法实现的影响）。

### What does the proposed API look like?

当前我希望让这个库允许初始化时关闭header、footer及pageNumber等独特场景下的渲染，以便实现纯编辑器的效果，对此：

1. 应该直接让header或footer的option类型可为false？
2. 还是增加编辑器模式进行区分？
3. 还是激进的考虑把main作为base,让header和footer作为扩展继承main，从而打开更自由的扩展和布局（类html）？

当然渐进地全部实现貌似是更好的选择，只是我还不清楚其中有哪些期望的功能会带来更多的问题。我相信这对于扩展应该是有帮助的，分块布局或许能带来更好的规划？例如想要实现导航目录和文档备注仅需要将其填充到一个横向布局的块内元素，至于其是否作为独立插件以及如何进行数据交互则是细节实现了。

**Comment by Hufe921** [comment]
1. 关闭页眉、页脚、页码、页边距是一个比较简单的需求，增加配置代码稍作修改既可实现。
2. 导航目录需求，涉及标题、列表目前功能已经完成，但是改动较大，最近在做bug修复，等系统稳定之后，会考虑目录的实现。

**Comment by 1019058432** [comment]
情况1我在尝试利用父容器滚动的情况下实现有限宽高的编辑器，但鼠标工作不正常同时导致页面渲染异常？

**Comment by Hufe921** [comment]
不好意思，没懂为什么关闭页眉页码 要利用父容器滚动。
方便的话可以，提供一个最小可复现环境
