### ISSUE TITLE
Page numbering setup suggestion

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#183]
### What problem does this feature solve?

Hi, I saw that the page number setting options were improved which looks great.

I would like to suggest the implementation of some more configuration possibilities, which can make the editor more robust and flexible, are the following:

- Option to configure where the pagination should appear header or footer. It is currently fixed to the footer;
- Option to configure from which page the pagination should start, ex: from page 2, then page 1 would not display number.
- Option to define exceptions where the page number should NOT appear, eg page 5, 6, 7; then the editor would show the number on all pages except those reported.

The last two suggestions could also be applied to setting up the header/footer. From which page the header/footer can be displayed, or which pages the header/footer will NOT be displayed.

### What does the proposed API look like?

I imagine these settings could be defined in the editor's configuration, in the 'pageNumber' property, and applied when the editor is rendering the pages.

I don't know if it's easy to implement, and if you're interested in these proposals. I believe that the editor will meet the most diverse scenarios with these additional settings.

Again congratulations on the project. Hugs.

**Comment by Hufe921** [comment]
Thank you. This is a good idea and will be included in the subsequent iteration plan. Of course, if you are interested, welcome to submit the PR
