### ISSUE TITLE
打印模糊问题

### ISSUE THREAD

**Issue by Simon7520** [Hufe921/canvas-editor#185]
### version

main

### Steps to reproduce

现象：打印出来的字体显示效果是模糊的
调优：手动在打印时，调高canvas的scale缩放比例，可以提高清晰度，但是太高了会导致空白，稍微调高一些也只是改善而没有彻底解决。

### What is expected?

类似Office或者腾讯在线文档，打印出来的字笔画是清晰正常的。
看起来可能时toDataUrl时生成图片的清晰度问题，不知道有没有什么更好的解决方案。

### What is actually happening?

打印字体模糊

**Comment by Hufe921** [comment]
客户端打印会受限于浏览器、系统、字体支持完备度等是无法很好的完成打印功能（如：无法保证在相同数据的情况下，得到渲染一致的效果）。更好的处理方式是服务端生成文件给前端调用打印。
得益于光标及文字排版的完全自行实现，目前比较可行的方案是：在服务端使用pdfjs进行编辑器渲染层逻辑处理，得到pdf文件返回给前端调用。目前测试验证代码：（WIP）（https://github.com/Hufe921/canvas-editor/tree/feature/pdf） ，后续会考虑进一步完善

**Comment by Simon7520** [comment]
> 客户端打印会受限于浏览器、系统、字体支持完备度等是无法很好的完成打印功能（如：无法保证在相同数据的情况下，得到渲染一致的效果）。更好的处理方式是服务端生成文件给前端调用打印。 得益于光标及文字排版的完全自行实现，目前比较可行的方案是：在服务端使用pdfjs进行编辑器渲染层逻辑处理，得到pdf文件返回给前端调用。目前测试验证代码：（WIP）（[https://github.com/Hufe921/canvas-editor/tree/feature/pdf）](https://github.com/Hufe921/canvas-editor/tree/feature/pdf%EF%BC%89) ，后续会考虑进一步完善

试了腾讯文档的打印，好像并没用调用后端接口，不知道怎么实现的。。

**Comment by Hufe921** [comment]
编辑器使用svg作为渲染层，然后前端直接完成打印也是一种实现方式：https://github.com/Hufe921/canvas-editor/tree/feature/svg （WIP）
不过同样受限于浏览器、系统、字体支持完备度等，也是无法保证在相同数据的情况下，得到渲染一致的效果

**Comment by catouse** [comment]
提供一个思路，使用过 [PDF-LIB](https://pdf-lib.js.org/) 的 API 渲染为文字版的 PDF 进行打印，这样可以获得 100% 保真的文档，不存在清晰度问题了。不过工作量不少，需要使用 PDF-LIB API 实现一套同样的绘制接口。

**Comment by Superman-wc** [comment]
先用canvas生成2倍图， 使用pdf.js生成 PDF文档， 再打印PDF， 可以做到文字不模糊的

**Comment by Superman-wc** [comment]
> 

直接用生成图片插入到PDF中，不应该在使用PDF-LIB重新实现渲染，效果会不一样的， 没法100%还原canvas渲染出来的效果

**Comment by Hufe921** [comment]
> 提供一个思路，使用过 [PDF-LIB](https://pdf-lib.js.org/) 的 API 渲染为文字版的 PDF 进行打印，这样可以获得 100% 保真的文档，不存在清晰度问题了。不过工作量不少，需要使用 PDF-LIB API 实现一套同样的绘制接口。

feature/pdf 之前已经实现，但因为字体加载问题，客户端不适合

**Comment by lvjiaj** [comment]
请问打印模糊的问题有解决方法了吗？

**Comment by Hufe921** [comment]
v0.9.40

**Comment by Hufe921** [comment]
> v0.9.40

目前采用增大渲染设备像素比的方式实现

**Comment by Simon7520** [comment]
> > 
> 
> 直接用生成图片插入到PDF中，不应该在使用PDF-LIB重新实现渲染，效果会不一样的， 没法100%还原canvas渲染出来的效果

正是因为这个方案会导致打印出来模糊，图片的分辨率达不到打印机的要求，才要寻找别的方案。



> > 提供一个思路，使用过 [PDF-LIB](https://pdf-lib.js.org/) 的 API 渲染为文字版的 PDF 进行打印，这样可以获得 100% 保真的文档，不存在清晰度问题了。不过工作量不少，需要使用 PDF-LIB API 实现一套同样的绘制接口。
> 
> feature/pdf 之前已经实现，但因为字体加载问题，客户端不适合

字体加载问题具体是什么问题，我看了feature/pdf分支的效果应该是没问题的吧。
