### ISSUE TITLE
更多的功能请求

### ISSUE THREAD

**Issue by gmfu** [Hufe921/canvas-editor#188]
### What problem does this feature solve?

首先，你太优秀了。做到了我想做但是做不到的事情，感谢你的贡献，好想请你喝☕️...

期待以下功能实现，不知你这边是否有兴趣纳入到你的next features。

1. 获取文档所有输入元素控件的值集合
2. 根据输入元素控件Id或编码读取/设置当前值，是否可见，是否必填（支持批量）
3. 给输入元素控件添加扩展属性
4. 动态规则和动态表达式配置：如一个下拉框有两个选项（A、B）实现级联操作，选择A时控制一些输入元素或段落可见并且内容必填，选择B时其它处理。
5. 编辑器中插入前端自定义组件（如：前端angular/vue开发的自定义图表组件插入到文档中）
6. 文档修改痕迹展示
7. 文档修订，批注功能

### What does the proposed API look like?

我不知道这些功能该如何实现，以及您是否对这些内容感兴趣。
期待你的反馈，再次感谢你的贡献。

**Comment by Hufe921** [comment]
1-4：已在next features规划中（control rules）https://github.com/Hufe921/canvas-editor#next-features 
5：暂不考虑支持，考虑通过内容块功能扩展
6-7：后续支持

**Comment by gmfu** [comment]
> 1-4：已在next features规划中（control rules）https://github.com/Hufe921/canvas-editor#next-features 5：暂不考虑支持，考虑通过内容块功能扩展 6-7：后续支持

感谢你的答复，next features满怀期待；

**Comment by xukuanzhuo** [comment]
@gmfu  5. 编辑器中插入前端自定义组件（如：前端angular/vue开发的自定义图表组件插入到文档中）。
可以看下我fork修改的分支https://github.com/xukuanzhuo/canvas-editor/tree/feature/block-chart，新增一个ChartParticle在文档中渲染echarts图表。

**Comment by 4amup** [comment]
> 1-4：已在next features规划中（control rules）https://github.com/Hufe921/canvas-editor#next-features 5：暂不考虑支持，考虑通过内容块功能扩展 6-7：后续支持

有计划增加书签控制的特性吗？
