### ISSUE TITLE
请问是否支持续打功能？

### ISSUE THREAD

**Issue by davidliuzd** [Hufe921/canvas-editor#191]
### What problem does this feature solve?

希望支持续打功能

### What does the proposed API look like?

希望支持续打功能

**Comment by Hufe921** [comment]
可以暂时考虑：将续打前的文字颜色设置成白色解决
如果后续程序实现：会考虑遮罩或其他类似原理实现

**Comment by Whiteyingshan** [comment]
> 我们也遇到续打问题，文字设置成白色没有问题，但是图片没法设置。想着透明度100%应该也可以，但看着图片好像没有 透明度的设置。

请问如何把非选中的文字设置为白色，只看到有getKeywordRangeList这种获取选中文字的命令

**Comment by Whiteyingshan** [comment]
> 可以暂时考虑：将续打前的文字颜色设置成白色解决 如果后续程序实现：会考虑遮罩或其他类似原理实现

佬，请问如何把非选中的文字设置为白色，只看到有getKeywordRangeList这种获取选中文字的命令

**Comment by Hufe921** [comment]
command.executeColor('#ffffff')
