### ISSUE TITLE
打开的功能菜单在点击页面其他位置时不自动关闭

### ISSUE THREAD

**Issue by vndmea** [Hufe921/canvas-editor#192]
### version

main

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

1. 打开页面
2. 点击“水印”或“纸张类型”，会弹出功能菜单
3. 鼠标点击页面其他地方

### What is expected?

打开的功能菜单能在失焦的时候能自动关闭

### What is actually happening?

弹出的功能菜单如果不再次点击相应图标会一直显示

**Comment by Hufe921** [comment]
本项目编辑器(/src/editor)为核心功能及npm包发布代码，外部功能仅作为编辑器功能的演示。
外部功能bug稍晚处理
