### ISSUE TITLE
保存和导入功能

### ISSUE THREAD

**Issue by aeiouaoeiuv** [Hufe921/canvas-editor#197]
### What problem does this feature solve?

建议后续添加保存和导入功能，现在看来写作都是一次性的。

### What does the proposed API look like?

none

**Comment by Hufe921** [comment]
编辑器属于工具，保存及导入属于业务处理逻辑，业务处理时可以通过一下api完成保存及导入：
保存：
1. 监听saved后保存数据（https://hufe.club/canvas-editor-docs/guide/listener.html#saved）
2. 主动调用getValue获取数据（https://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue）
导入：
1. 实例化编辑器时传入（https://hufe.club/canvas-editor-docs/guide/start.html#step-3-%E5%AE%9E%E4%BE%8B%E5%8C%96%E7%BC%96%E8%BE%91%E5%99%A8）
2. 通过insertElementList插入结构化数据（https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeinsertelementlist）
3. 考虑后期加上替换整份文档命令
