### ISSUE TITLE
连页模式不支持设置页眉页脚吗

### ISSUE THREAD

**Issue by MssText** [Hufe921/canvas-editor#200]
### What problem does this feature solve?

看作者提了一个merge去除了连页模式下的页眉页脚设置，不支持是有什么考量吗

### What does the proposed API look like?

如上

**Comment by zhoujingfu** [comment]
连页模式的概念就是没有页眉页脚的呀

**Comment by Hufe921** [comment]
不分页的文档会连续显示在一个页面上，没有明确的页面边界，因此页眉和页脚无法被正确地定位（逻辑互斥）和显示。
参考：谷歌文档、金山文档、腾讯文档

**Comment by MssText** [comment]
>

> 不分页的文档会连续显示在一个页面上，没有明确的页面边界，因此页眉和页脚无法被正确地定位（逻辑互斥）和显示。 参考：谷歌文档、金山文档、腾讯文档

**Comment by MssText** [comment]
好的，了解了
