### ISSUE TITLE
HistoryManager can cause a significant increase in memory usage.

### ISSUE THREAD

**Issue by xavier711** [Hufe921/canvas-editor#203]
### version

latest

### Steps to reproduce

Enter text continuously and see the increasing memory through the Perfermace Monitor in Chrome Dev Tools.

### What is expected?

Should't use so much memory.

### What is actually happening?

<img width="1200" alt="snipaste" src="https://github.com/Hufe921/canvas-editor/assets/89233655/a2906694-3474-42ca-bcd9-d99842714a96">

### Any additional comments?

HistoryManager can cause a significant increase in memory usage.
The more data there is, the more noticeable the growth, eventually leading to a browser crash.
Can local storage be used to handle data for the HistoryManager?

**Comment by Hufe921** [comment]
| editor        | max record count | memory growth rate | debounce      |
| :------------ | :--------------- | :----------------- | :------------ |
| canvas-editor | 1000             | fast               | no            |
| kdocs         | 100              | stable             | yes（instable） |
| tencent       | -                | fast               | yes           |
| google        | -                | stable             | yes           |


Optimizing undo/redo memory usage by comparing different editors, the first step to consider is debouncing
