### ISSUE TITLE
连续使用格式刷时没法取消（缺少取消api）

### ISSUE THREAD

**Issue by 284668461** [Hufe921/canvas-editor#208]
### What problem does this feature solve?

双击格式刷 **进入连续模式后，无法取消格式刷** 。只能再点击一次格式刷。切换到非连续模式。再刷一次才可取消。

### What does the proposed API look like?

建议增加一个取消功能（例如说此时点击右键取消格式刷）或api

**Comment by Hufe921** [comment]
使用ESC取消连续格式刷，具体可参考word及其他在线文档使用方式
