### ISSUE TITLE
怎么获取某一页的数据呢？

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#211]
### What problem does this feature solve?

怎么获取某一页的数据呢？

### What does the proposed API look like?

获取某一页的数据

**Comment by yicheng2022** [comment]
我想复制某一页的数据

**Comment by Hufe921** [comment]
v0.9.38
获取某一页数据：https://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue
追加元素：https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeappendelementlist

**Comment by yicheng2022** [comment]
> v0.9.38 获取某一页数据：https://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue 追加元素：https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeappendelementlist

老大，getValue里面传的pageNo是怎样获取呢？我在文档里面没有找到获取当前页码的方法。

**Comment by Hufe921** [comment]
当前光标所在的页码？

**Comment by yicheng2022** [comment]
> 当前光标所在的页码？

是的

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-get.html#getrangecontext

**Comment by yicheng2022** [comment]
> https://hufe.club/canvas-editor-docs/guide/command-get.html#getrangecontext

这个是哪个版本的功能呢？我在0.9.38的代码里面没有找到这个方法。

**Comment by Hufe921** [comment]
v0.9.39

**Comment by yicheng2022** [comment]
> v0.9.39

刚刚拉最新的版本测试了一下，感谢大佬！
不过发现一个小问题，就是如果最后一页内容很少（只有半页或者几行字），他是直接在最后一页的内容后面增加内容了，没有新建一个空白页，再把内容给放到新页里面去。

**Comment by Hufe921** [comment]
直接在新页面追加元素，可以使用换页符
```
instance.command.executeAppendElementList([{
    type: ElementType.PAGE_BREAK,
    value: ''
  }, ........])
```

**Comment by yicheng2022** [comment]
> 直接在新页面追加元素，可以使用换页符
> 
> ```
> instance.command.executeAppendElementList([{
>     type: ElementType.PAGE_BREAK,
>     value: ''
>   }, ........])
> ```

好的，我试试，感谢！

**Comment by yicheng2022** [comment]
> 直接在新页面追加元素，可以使用换页符
> 
> ```
> instance.command.executeAppendElementList([{
>     type: ElementType.PAGE_BREAK,
>     value: ''
>   }, ........])
> ```

![image](https://github.com/Hufe921/canvas-editor/assets/103647012/b01a63c7-71fa-4580-a110-40ac08535959)
分页符打印的时候怎么去掉呢？设置了颜色为白色好像也没有起作用。

**Comment by Hufe921** [comment]
使用清洁模式https://hufe.club/canvas-editor-docs/guide/option.html EditorMode.CLEAN
