### ISSUE TITLE
英文换行的问题

### ISSUE THREAD

**Issue by xiajinchun** [Hufe921/canvas-editor#212]
### version

0.9.30

### Steps to reproduce

请问一下英文根据单词换行有比较好的处理方法吗？
现在是根据每个字符来换行的；

### What is expected?

![XIA 2023-07-10 12 34 16](https://github.com/Hufe921/canvas-editor/assets/4453349/33c71ea8-c0a9-4b15-acc8-1500680c0f40)

### What is actually happening?

![XIA 2023-07-10 12 33 05](https://github.com/Hufe921/canvas-editor/assets/4453349/23b9641b-3535-4190-847f-344da7308aaa)

**Comment by Hufe921** [comment]
v0.9.38
wordBreak已默认配置break-word(https://hufe.club/canvas-editor-docs/guide/option.html)
