### ISSUE TITLE
关于表格的高度

### ISSUE THREAD

**Issue by wzk-jiuyinghuo** [Hufe921/canvas-editor#214]
### What problem does this feature solve?

首先，感谢您的贡献，最近在使用表格的时候，高度需要在矮一些，是否有对应的配置项可以修改表格的最低高度？

### What does the proposed API look like?

期待你的反馈，再次感谢你的贡献。

**Comment by Hufe921** [comment]
可以通过设置defaultTrMinHeight调整表格行高。
但是因为行间距，字体默认尺寸原因最小高度是40，想要降低这个高度，需后续对表格进行优化。

**Comment by wzk-jiuyinghuo** [comment]
好的，谢谢您的回复

**Comment by wzk-jiuyinghuo** [comment]
您好，那个清洁模式具体的做什么的，我没有试出来，文档里边也没找到具体的说明。谢谢了

**Comment by Hufe921** [comment]
1. 清洁模式：不显示视觉辅助元素。如：分页符、后续的控件辅助元素
2. 默认最小表格行高组成：
`单元格内边距（tdPadding）*2 + 默认行高（defaultBasicRowMarginHeight）*2 + 默认字体大小（defaultSize）`
因此想缩小最小行高的一个示例如下：
```
  const options: IEditorOption = {
        defaultBasicRowMarginHeight: 8,
        defaultTrMinHeight: 2*2+8*2+16,
        tdPadding: 2
}
```
此时行高为36像素

**Comment by wzk-jiuyinghuo** [comment]
我们目前有这样一个需求，我们需要建立一个治疗单模板，然后治疗师在治疗单的模板上进行编辑，是否可以设置为只能对控件进行操作编辑，而整个治疗单模板不能编辑

**Comment by Hufe921** [comment]
> 我们目前有这样一个需求，我们需要建立一个治疗单模板，然后治疗师在治疗单的模板上进行编辑，是否可以设置为只能对控件进行操作编辑，而整个治疗单模板不能编辑

可以新增表单模式。不过提交新的issue feature
