### ISSUE TITLE
关于病程连续展示

### ISSUE THREAD

**Issue by Hao-Hu** [Hufe921/canvas-editor#216]
### What problem does this feature solve?

非常感谢您开源的项目
对于病程的连续显示
1.是否有区块的概念
2.区块是否有独立的特性，如是否只读，边框显示且边框显示不能独立占据像素(即区块的边框线显示的时候，不影响行间距的高度)

### What does the proposed API look like?

改功能是病程连续显示的主要方式，希望您能够考虑是否增加相应的功能。

**Comment by lehno** [comment]
That is an amazing feature, thanks very much
