### ISSUE TITLE
询问具体使用方法

### ISSUE THREAD

**Issue by lszqg** [Hufe921/canvas-editor#220]
作者你好！我这边按照文档说明的实例化完成之后只有一个编辑框，没有工具栏，想询问下具体使用方法（在vue里面用的，还有无法绑定v-model）

**Comment by Hufe921** [comment]
1. npm包目前只关注编辑器核心层（代码层面src/editor），工具栏可参考示例自行实现
2. v-model属于vue语法糖，编辑器与前端框架无关。

- 设置编辑器值方式：

1. 实例化编辑器时传入数据[（参考地址）](https://hufe.club/canvas-editor-docs/guide/start.html#step-3-%E5%AE%9E%E4%BE%8B%E5%8C%96%E7%BC%96%E8%BE%91%E5%99%A8)
2. 通过命令设置数据[（参考地址）](https://hufe.club/canvas-editor-docs/guide/command-execute.html#executesetvalue)

- 获取编辑器值方式：

1. 通过命令获取编辑器值[（参考地址）](https://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue)
2. 监听事件获取编辑器值[（参考地址）](https://hufe.club/canvas-editor-docs/guide/eventbus.html#saved)

**Comment by XPoet** [comment]
作者您好。目前文档和代码仓库找不到顶部工具栏的使用示例代码，可否在文档里贴一份官方 Demo 的代码地址
