### ISSUE TITLE
后续会提供解析html文本展示功能吗？

### ISSUE THREAD

**Issue by ProLiok** [Hufe921/canvas-editor#223]
### What problem does this feature solve?

非常感谢作者上次的回复，今天发现更新了新版本有个获取html文本的方法就尝试了下使用，后面发现目前编辑器无法自动解析html文本并展示

### What does the proposed API look like?

就来问下后续会提供api解析html文本或者编辑器自动解析html文本？

**Comment by Hufe921** [comment]
v0.9.42
