### ISSUE TITLE
怎样才能知道内容被人工修改过呢？

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#224]
### What problem does this feature solve?

大佬好，在测试过程中，我想知道内容是否被人工修改过，contentChange事件在编辑器初始化的时候会执行一次，setValue的时候又会被执行一次。像这种光标都没有定位到渲染区域，但是contentChange缺执行了两次，不能判断内容确实被人工编辑过。除非通过contentChange去计算该事件的执行次数。但是这种方法也不完全正确。请问还有其他方案吗？

### What does the proposed API look like?

希望能通过一个属性或者某个方法，获取到该内容被人工编辑过。

**Comment by Hufe921** [comment]
初始化时不应该触发contentChange已修改，setValue属于内容改变需执行回调。
如果不需要执行回调可以在setValue时，设置变量进行判断

**Comment by yicheng2022** [comment]
> 初始化时不应该触发contentChange已修改，setValue属于内容改变需执行回调。 如果不需要执行回调可以在setValue时，设置变量进行判断

setValue是否是没有将header数据set进去？测试的时候发现setValue后立即getValue，发现取不到header,footer数据
