### ISSUE TITLE
getHTML 无法获取到分页符信息

### ISSUE THREAD

**Issue by guangzezhu** [Hufe921/canvas-editor#225]
### version

0.9.41

### Steps to reproduce

文档插入分页符，执行 await instance.command.getHTML()

### What is expected?

const {
  header: string
  main: string
  footer: string
} = await instance.command.getHTML()

获取到的main字符串 包含分页符信息，如<pageBreak>

### What is actually happening?

没有分页符信息，

空白文档插入分页符后，获取到的html为空字符串 ""

**Comment by Hufe921** [comment]
html无分页符标签

**Comment by guangzezhu** [comment]
能否将分页符信息转换为备注元素：/<!-- my page break --/>
并提供分页符配置，自定义备注内容，如 
```
// 配置项
{
    pagebreak_separator: "this is my page break"
}

// 结果 getHTML() main: ....<!-- this is my page break -->
```

```
// element.ts createDomFromElementList
...
else if (element.type === ElementType.PAGE_BREAK) {
    const pageBreak =  document.createComment('page_break')
    clipboardDom.append(pageBreak)
}
...
```
需求背景：
    用户编辑文档，插入分页符；后端导出word文档时，根据分页符信息分页

相似功能：
1. https://www.tiny.cloud/docs/tinymce/6/pagebreak/

**Comment by liwenjingf** [comment]
你好，最后怎么解决的分页符问题呢

**Comment by guangzezhu** [comment]
> 你好，最后怎么解决的分页符问题呢

1. 在源码中找到 element.ts createDomFromElementList，将分页符节点转成dom的注释节点；
2. 打包canvas-editor引到项目里
