### ISSUE TITLE
插入的表格高度超过2页时，第三页内容不展示

### ISSUE THREAD

**Issue by guangzezhu** [Hufe921/canvas-editor#228]
### version

0.9.41

### Steps to reproduce

**分页模式下**
1. executeInsertTable 命令插入表格
 ```
instance.command.executeInsertTable(100, 6)
```
2. 或者executeAppendElementList 方法插入表格，代码插入表格 6列 100行
```
onInsertCustomTable () {
      const table = {
        value: '',
        type: 'table',
        trList: [
        ],
        width: 558,
        height: 42,
        colgroup: []
      }

      // colgroup
      const colgroup = []
      const colNum = 6
      for (let i = 0; i < colNum; i++) {
        colgroup.push({
          width: 558 / colNum
        })
      }
      table.colgroup = colgroup

      // trList
      const rowNum = 100
      for (let i = 0; i < rowNum; i++) {
        const trList = {
          height: 42,
          tdList: []
        }
        for (let j = 0; j < colNum; j++) {
          const td = {
            colspan: 1,
            rowspan: 1,
            value: `${i + 1}-${j + 1}`
          }
          trList.tdList.push(this.getCell(td))
        }
        table.trList.push(trList)
      }

      // insert table
      this.$refs.CanvasEditor.instance.command.executeAppendElementList([table])
    }
```

### What is expected?

插入行列数正确的表格
![表格30](https://github.com/Hufe921/canvas-editor/assets/23500552/3c892f81-ffd2-47e5-b832-1b61fc8c8a50)

### What is actually happening?

1. 执行插入指令
2. 插入的表格过高时（高度超过两页，可能原因：行过多、单元格内容高度过多=高），编辑器中的表格截断多余行；
![表格60行 -- 1](https://github.com/Hufe921/canvas-editor/assets/23500552/1aae6bd8-30a6-45b4-a74c-fd0f3a5705f2)

3. 此时鼠标点击第二页表格中的单元格，编辑器变化，展示表格外框，但不展示page

![表格60 -- 2](https://github.com/Hufe921/canvas-editor/assets/23500552/cb4a3636-5fb0-4058-820e-30bb01b1c5ee)

### Any additional comments?

相似问题: https://github.com/Hufe921/canvas-editor/issues/41

**Comment by Hufe921** [comment]
相同问题，请等待后续方案
