### ISSUE TITLE
页面不会根据光标的位置进行滚动.

### ISSUE THREAD

**Issue by lingyih** [Hufe921/canvas-editor#229]
### version

0.9.41

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

键盘按键切换光标位置到最底部,或者最上面,继续往下,或往上,光标会继续动,但是页面不滚动,会导致无法看见想看的数据.

### What is expected?

光标在底部或者顶部的时候按键盘切换位置的时候,页面也会滚动

### What is actually happening?

页面不会根据光标的位置滚动.

**Comment by Hufe921** [comment]
v0.9.43
