### ISSUE TITLE
功能增加

### ISSUE THREAD

**Issue by zheng-d-d** [Hufe921/canvas-editor#230]
### What problem does this feature solve?

今天试用了新发布的executeSetHTML方法后，这个方法会将页面编辑的所有东西都替换成插入的文本，考虑到后续可能会想插入别的文档识别出来的html文本，能不能把那个html转编辑器可识别的数据格式的方法提供出来

### What does the proposed API look like?

今天试用了新发布的executeSetHTML方法后，这个方法会将页面编辑的所有东西都替换成插入的文本，考虑到后续可能会想插入别的文档识别出来的html文本，能不能把那个html转编辑器可识别的数据格式的方法提供出来

**Comment by Hufe921** [comment]
HTML格式太灵活，编辑器无法兼容所有HTML格式，建议将其他地方的HTML文本，通过一定方法转换成IElement的数据结构进行插入
