### ISSUE TITLE
希望新增文档内容跳转功能

### ISSUE THREAD

**Issue by zhouchangmin** [Hufe921/canvas-editor#233]
### What problem does this feature solve?

比如 我想在 编辑区 加上 普通类型 非标题文字 ’ 动态文字‘ ，希望能给这个节点 加上 uuid,然后不管 这个节点的名字 怎么变，变成 ’动态文字1212‘，也能光标 跳转到该位置

### What does the proposed API look like?

比如 我想在 编辑区 加上 普通类型 非标题文字 ’ 动态文字‘ ，希望能给这个节点 加上 uuid,然后不管 这个节点的名字 怎么变，变成 ’动态文字1212‘，也能光标 跳转到该位置

**Comment by Hufe921** [comment]
详细使用场景是？
