### ISSUE TITLE
getImage 方法能否添加一个参数。当获取当前页面图片时，图片里能否不显示页面控件的大括号和占位符。

### ISSUE THREAD

**Issue by lingyih** [Hufe921/canvas-editor#236]
### What problem does this feature solve?

因为病历需要打印，给患者，所以希望打印出的东西不带控件的大括号或者当控件没输入值得时候打印不显示占位符。

### What does the proposed API look like?

增加一个或者两个参数，是否显示控件的大括号和占位符。

**Comment by Hufe921** [comment]
v0.9.44
