### ISSUE TITLE
在表格下新建一个文本为客户签名，要求客户签名几个字具右对齐

### ISSUE THREAD

**Issue by luzhanmin** [Hufe921/canvas-editor#237]
### What problem does this feature solve?

现在只能居左对齐，如何在渲染编辑器的时候展示的内容，指定行居右对齐

### What does the proposed API look like?

大佬解答一下

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executerowflex
