### ISSUE TITLE
希望文档可以添加每页固定部分与数据部分

### ISSUE THREAD

**Issue by ljm000** [Hufe921/canvas-editor#239]
### What problem does this feature solve?

1、传入一个数据结构
2、可以定义页面中的固定行与数据行，比如定义每页出现的页头行与页尾行
3、当数据行传入数据后，自动的展开，当撑满一页后。自动的翻页显示，翻页显示的页面同时也会显示每页出现的固定行。

![image](https://github.com/Hufe921/canvas-editor/assets/12406935/21da0b62-3aa7-4589-978b-42090649485d)

### What does the proposed API look like?

可以实现每页出现的固定部分，传入数据可以自动展开

**Comment by Hufe921** [comment]
可以使用页眉页脚的形式实现：https://hufe.club/canvas-editor-docs/guide/start.html
