### ISSUE TITLE
下划线距离文字太远

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#247]
### What problem does this feature solve?

目前，使用下划线时，显示的下划线距离上面的文字太远，比其它软件，例如word，差异性太大
![image](https://github.com/Hufe921/canvas-editor/assets/73809241/b4ab8cd1-0d65-47fd-aa58-a0f6c1471d06)

### What does the proposed API look like?

建议增加相关配置，或者缩减距离

**Comment by Hufe921** [comment]
v0.9.45
