### ISSUE TITLE
无法直接调整整体字体大小

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#251]
### What problem does this feature solve?

在使用的过程中，发现没有 api 能够直接调整全部内容的字体大小，只能执行 executeSelectAll ，在进行字体大小的调节。但是实际使用中，可能不会调节部分内容的字体大小，而是字节调整全部内容的字体大小

### What does the proposed API look like?

增加可以直接调整全部内容字体大小的 api

**Comment by Hufe921** [comment]
需求较为特殊，请具体描述使用场景

**Comment by jimpeo** [comment]
> 需求较为特殊，请具体描述使用场景

生成一份报告，使用canvas-editor仅生成内容区域，内容区域要求字体大小一直，但是支持字体大小的调节

**Comment by Hufe921** [comment]
真正需要的功能是不是页面缩放？https://hufe.club/canvas-editor-docs/guide/command-execute.html#executepagescaleadd
