### ISSUE TITLE
单位的问题

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#252]
### What problem does this feature solve?

在使用是，发现部分width、height、size相关的配置，仅支持数字类型，插件默认的单位为 px，但是在一些场景下，会使用除px外其它的单位，例如：cm、pt

### What does the proposed API look like?

width、height、size相关的配置，支持单位配置

**Comment by Hufe921** [comment]
可以通过将cm pt转换成px后进行配置
