### ISSUE TITLE
初始赋值及图片用url显示

### ISSUE THREAD

**Issue by liwenjingf** [Hufe921/canvas-editor#253]
### What problem does this feature solve?

1.初始value只能设对象，能像其他富文本一样直接赋html字符串吗？
2.上传或粘贴图片只能是base64吗？我用的url，粘贴不知道在哪里修改成url

### What does the proposed API look like?

1.初始value只能设对象，能像其他富文本一样直接赋html字符串吗？
2.上传或粘贴图片只能是base64吗？我用的url，粘贴不知道在哪里修改成url

**Comment by Hufe921** [comment]
1. html字符串使用[executesetHTML](https://hufe.club/canvas-editor-docs/guide/command-execute.html#executesethtml)进行数据设置
2. value传入url即可
