### ISSUE TITLE
希望有个配置能够隐藏裁剪标记 

### ISSUE THREAD

**Issue by Carlos920** [Hufe921/canvas-editor#259]
### What problem does this feature solve?

希望有个配置能够隐藏裁剪标记 
![image](https://github.com/Hufe921/canvas-editor/assets/32257015/a77cf461-557b-4834-8f19-8babd1c591d5)

### What does the proposed API look like?

希望能够像这样
![image](https://github.com/Hufe921/canvas-editor/assets/32257015/87656308-3ca8-49e6-8fd6-3ca6978bbffd)

**Comment by Hufe921** [comment]
设置margin颜色为背景色即可，如设置：marginIndicatorColor:#ffffff
https://hufe.club/canvas-editor-docs/guide/option.html
