### ISSUE TITLE
getHTML无法获取到分页符，#225已有人提出

### ISSUE THREAD

**Issue by liwenjingf** [Hufe921/canvas-editor#261]
### What problem does this feature solve?

麻烦作者能不能加下这个功能呢。在setHTML的时候，针对分页符加个类似这种标识呢。不然现在的分页符感觉没有意义，保存完再次回显的时候就没了呢

### What does the proposed API look like?

getHTML希望能获取到分页符标识，以便数据回显的时候识别

**Comment by Hufe921** [comment]
不要将html作为编辑器的数据结构去存储及还原！
使用command.getValue去获取编辑器结构化数据。
