### ISSUE TITLE
存在两个实例时，光标会同时显示

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#262]
### version

0.9.45

### Steps to reproduce

new Editor 多次后，光标会存在于多个实例中

### What is expected?

需要在多实例的情况下，光标仅存在于当前实例中

### What is actually happening?

需要在多实例的情况下，光标仅存在于当前实例中

**Comment by Hufe921** [comment]
仅一个编辑器光标闪动且可输入文字；
其他编辑器光标是不闪动，不可输入文字的失活显示状态；

**Comment by jimpeo** [comment]
> 
可以增加失焦的 api 吗，业务中自主控制光标是否显示

**Comment by lingyih** [comment]
失焦的api预计什么时候能加上?

**Comment by lingyih** [comment]
@Hufe921  大佬  失焦这个api 近期有加的计划吗?

**Comment by haiyunxiong** [comment]
怎么添加两个实例？我添加第二个实例的时候会把第一个的内容清空掉
