### ISSUE TITLE
Is it possible to add indentation/tab for lists?

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#265]
### What problem does this feature solve?

Is it possible to add indentation/tab for lists?

![image](https://github.com/Hufe921/canvas-editor/assets/22320158/26fc1621-d284-41e8-9f78-e5f39ac8c525)

Currently if you add a tab to a list, the text is moved to the next line, and the list marker stays at the same position as the previous line.

![image](https://github.com/Hufe921/canvas-editor/assets/22320158/aae64606-533a-4ea8-927c-b7128791df4b)

I tried to change the code, reusing the rowMargin property in Element.ts, using the same logic that the css uses for some properties: "0 0 0 0' (top, right, bottom and left). Changed the Draw.ts file method drawRow(), ListParticle.ts drawListStyle() method, and some other files with adaptations that were necessary due to rowMargin's type change, and helper functions, I even got the result I wanted.

![image](https://github.com/Hufe921/canvas-editor/assets/22320158/e0ed0b07-a778-4ac2-9922-9737e0ab2dfa)

But when the cursor passes over the region you notice that it has extra spacing. Maybe that's right, because it was just right-aligned, not added a tab.

https://github.com/Hufe921/canvas-editor/assets/22320158/efc80a5d-3025-4b75-aa3d-cb07b3f4e363

Do you have any tweak suggestions, or do you intend to tweak this in the future? Or do you have no plans for that either?

### What does the proposed API look like?

Make it possible to add indentation to lists.

**Comment by douglasmatheus** [comment]
If you can help by guiding how to proceed, I can better understand the structure of the project, and help with changes to new features by PR.

**Comment by Imran17507** [comment]
@douglasmatheus Just out of curiosity, how long did it take you to study the codebase and how long did it take you to implement the sublist / nested list / tab for lists?

**Comment by douglasmatheus** [comment]
Hi @Imran17507 , the implementation didn't take long once I found the right places. It took some time to understand the logic, but nothing too complicated as it is well separated and organized.

However, the processing is relatively complex, but I've been following the implementations for a while, with each new feat I look at the changes to familiarize myself with the code, so it wasn't that complicated.
