### ISSUE TITLE
通过ctrl + c 复制出来文本，在粘贴回去，会自动加上背景颜色

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#266]
### version

0.9.45

### Steps to reproduce

通过ctrl + c 复制出来文本，在粘贴回去，会自动加上背景颜色

### What is expected?

希望去除粘贴文本的字体颜色

### What is actually happening?

希望去除粘贴文本的字体颜色

**Comment by Hufe921** [comment]
使用chrl+shift+v进行纯文本粘贴

**Comment by jimpeo** [comment]
> 使用chrl+shift+v进行纯文本粘贴

实际是无法控制用户粘贴的操作的，目前采用监听内容变化事件，每次内容有变化时，强制将color属性去除，但是如果设置实例仅支持某些格式，需要将不支持的格式逐步清除相关属性，例如：bold，在不支持粗体时，需要将 value 中所有 bold 属性去除，希望能够增加相关的限制功能

**Comment by jimpeo** [comment]
> 使用chrl+shift+v进行纯文本粘贴

实际是无法控制用户粘贴的操作的，目前采用监听内容变化事件，每次内容有变化时，强制将color属性去除，但是如果设置实例仅支持某些格式，需要将不支持的格式逐步清除相关属性，例如：bold，在不支持粗体时，需要将 value 中所有 bold 属性去除，希望能够增加相关的限制功能

**Comment by Hufe921** [comment]
是某种场景下，粘贴时都不需要带样式吗

**Comment by jimpeo** [comment]
> 



> 是某种场景下，粘贴时都不需要带样式吗

仅支持某几个格式，粘贴时别的格式需要格式化处理成普通文本，像图片这种就需要去除掉，目前通过监听的方式可以处理一部分，但是需要每种格式都去在监听事件中处理

**Comment by Hufe921** [comment]
看来需要加上自定义粘贴处理功能了。
重复：https://github.com/Hufe921/canvas-editor/issues/260
