### ISSUE TITLE
重新渲染的编辑器内容，打印时，控件会显示大括号

### ISSUE THREAD

**Issue by wzk-jiuyinghuo** [Hufe921/canvas-editor#270]
### version

0.9.46

### Steps to reproduce

设置好模板，保存后，重新加载出来，选择打印，然后控件有大括号

### What is expected?

![image](https://github.com/Hufe921/canvas-editor/assets/120085726/022d07bc-1de1-48bf-b477-b81f4a054abd)

### What is actually happening?

正常应该没有大括号

**Comment by Hufe921** [comment]
提供一个最小可复现demo，或完整的复现步骤
