### ISSUE TITLE
Command implementation to get page information (current/other)

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#272]
### What problem does this feature solve?

I would like to know if it would be possible to implement a command that would return the information of the current page, or any other specified.

### What does the proposed API look like?

The information returned as: page size (height, width), margins, orientation, page content size. This last one in particular, knowing the already occupied size of the page, it would be possible to make auxiliary functions for content displacement with page breaks.

In my case I need to do something similar to the 'page-break-inside', 'page-break-before' and 'page-break-after' css properties. I'm not sure if it's possible to obtain this information currently, and if it's something complicated to implement.
Thank you for your dedication and work on this project.

**Comment by Hufe921** [comment]
1. https://hufe.club/canvas-editor-docs/en/guide/command-get.html#getvalue
2. https://hufe.club/canvas-editor-docs/en/guide/command-get.html#getoptions
Do these two APIs meet your requirements?

**Comment by douglasmatheus** [comment]
Not entirely, as it would need to know the space already occupied on the current page. For example, on the page I have one or more tables with content, at the end of the page the last table (or any other element) will not fit completely and will break to the next page.

What I would like is to programmatically identify this content break, and add a page break before it so that the content starts on the next page, avoiding breaking it. Something similar to the CSS properties 'page-break-inside', 'page-break-before' and 'page-break-after'.

Is it possible to do this treatment with the current functions? if you can at least guide me, so that I implement something for myself.

**Comment by douglasmatheus** [comment]
This situation I want to treat

![image](https://github.com/Hufe921/canvas-editor/assets/22320158/b0d33e10-1f52-438d-8924-d470cf66ba18)

**Comment by Hufe921** [comment]
Paging is automatic, why insert line breaks?

**Comment by Hufe921** [comment]
Now the editor cannot perform table pagination well, so do you want to force a page break to be added to the current pagination area, even if the paper size is changed in the future, it can still ensure that there is a page break in one place?

**Comment by douglasmatheus** [comment]
Yes, I would like to force a page break. I know that there may be situations where the content will be long enough that you can't do anything and let pagination occur naturally.

In my case the paper size will always be fixed and will not change, which makes things easier. What will happen is the content will load initially, or maybe append elements one at a time, so I just need to identify the pages that will have elements at the end that will have wrapped content, and add the page break so that the element starts on the next page.

**Comment by Hufe921** [comment]
Forcing page breaks through page breaks is unreliable. For example, when the text before a page break increases or decreases, the position of the page break will also change.
I will soon focus on the table pagination feature

**Comment by douglasmatheus** [comment]
Yes, I understand that, as I mentioned in my case, I already have all the necessary content and it will not change.

I just want to identify when a page won't have enough space for the next content, I can add the page break as I'll make sure this content won't be changed anymore.

Is there any way to identify the remaining space on the page?

**Comment by douglasmatheus** [comment]
I greatly appreciate all your attention and help. If you have any way of receiving a donation, I would like to do so, as a way of thanking you for your initiative and willingness.
