### ISSUE TITLE
mode设置为readonly状态时，实例变成空白，不显示内容

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#273]
### version

0.9.45

### Steps to reproduce

mode设置为readonly状态时，实例变成空白，不显示内容

### What is expected?

mode设置为readonly状态时，实例变成空白，不显示内容

### What is actually happening?

mode设置为readonly状态时，实例变成空白，不显示内容

**Comment by Hufe921** [comment]
提供一个最小可复现demo，或完整的复现步骤

**Comment by jimpeo** [comment]
> 提供一个最小可复现demo，或完整的复现步骤

已找到问题，由于为动态的 options，其中 defaultSize 设置为 “”“”了，建议增加校验，defaultSize 为空时，默认赋值 minSize

**Comment by Hufe921** [comment]
1. 非特殊情况，通过命令（https://hufe.club/canvas-editor-docs/guide/command-execute.html#executemode） 去设置编辑模式
2. 即使某种情况下，需要更改默认配置, 也获取完整内部配置后（https://hufe.club/canvas-editor-docs/guide/command-get.html#getoptions ），再去修改配置
