### ISSUE TITLE
Please to convert a pdf file to the mock ? or add feature import pdf

### ISSUE THREAD

**Issue by vonhatduc** [Hufe921/canvas-editor#275]
### What problem does this feature solve?

Please to convert a pdf file to the mock ? or add feature import pdf

### What does the proposed API look like?

Please to convert a pdf file to the mock ? or add feature import pdf

**Comment by Hufe921** [comment]
You can use third-party tools to parse PDF into the data format required by the editor, and it will not be included in the official implementation for now
