### ISSUE TITLE
width property works with all types, or just specific ones ?

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#277]
### version

0.4.97

### Steps to reproduce

I'm setting the data like this:

```
editor.command.executeSetValue({main: [
	{
      "value": "Prod",
      "font": "Arial",
      "size": 18,
      "bold": true,
      "width": 200
    },
    {
      "value": " sad ",
      "font": "Arial",
      "size": 18,
      "bold": true,
      "width": 400,
      "groupIds": [
        "1"
      ]
    },
    {
      "value": "sadf",
      "font": "Arial",
      "size": 18,
      "bold": true
    }
]})
```

### What is expected?

Define the width for the element, and it will be applied correctly.

### What is actually happening?

Trying to set a width for certain elements, I noticed that the defined width is not applied. Is there any correct way to work, or what?

**Comment by douglasmatheus** [comment]
I see, thanks for clarifying. What would the text width configuration look like?

**Comment by Hufe921** [comment]
```javascript
{
 value: 'ABC',
 width: 50
}
```
![image](https://github.com/Hufe921/canvas-editor/assets/27001251/b8691002-4227-45aa-85e2-d93b2139ce4a)
