### ISSUE TITLE
会支持导入导出word吗

### ISSUE THREAD

**Issue by Hyan08** [Hufe921/canvas-editor#280]
### What problem does this feature solve?

会支持导入导出word吗

### What does the proposed API look like?

会支持导入导出word吗

**Comment by Hufe921** [comment]
考虑以插件的形式提供，可以关注此项目后续更新，[canvas-editor-plugin](https://github.com/Hufe921/canvas-editor-plugin)

**Comment by HoChine** [comment]
> 考虑以插件的形式提供，可以关注此项目后续更新，[canvas-editor-plugin](https://github.com/Hufe921/canvas-editor-plugin)

导出word的功能最近有计划吗？
