### ISSUE TITLE
是否可以通过配置调整字间距？

### ISSUE THREAD

**Issue by jimpeo** [Hufe921/canvas-editor#288]
### What problem does this feature solve?

目前发现，canvas-editor在书写英文段落时，字间距过小，字母之间过于紧凑

### What does the proposed API look like?

是否有调整字间距的功能？

**Comment by Hufe921** [comment]
letterSpacing：设置间距
https://hufe.club/canvas-editor-docs/guide/schema.html

**Comment by jimpeo** [comment]
> letterSpacing：设置间距 https://hufe.club/canvas-editor-docs/guide/schema.html

之前也发现这个地方，但是这个需要将 data 中每个 element 添加 letterSpacing 属性，是否有全局的配置？
