### ISSUE TITLE
是否新增源码模式，可以编辑html代码？

### ISSUE THREAD

**Issue by pittQ** [Hufe921/canvas-editor#289]
### What problem does this feature solve?

![image](https://github.com/Hufe921/canvas-editor/assets/65379888/26bed91b-e544-4b2f-9721-1bc7f41d644a)
如图

### What does the proposed API look like?

![image](https://github.com/Hufe921/canvas-editor/assets/65379888/26bed91b-e544-4b2f-9721-1bc7f41d644a)
如图

**Comment by Hufe921** [comment]
编辑器的数据结构和HTML无关。
https://hufe.club/canvas-editor-docs/
