### ISSUE TITLE
点击组件时获取能否把组件的信息都返回回来？

### ISSUE THREAD

**Issue by codepandy** [Hufe921/canvas-editor#292]
### What problem does this feature solve?

当点击组件时，希望获取组件的所有信息，但是我看rangeStyleChange事件只是返回了部分的属性，能否把当前元素对象直接返回？希望点击的时候可以拿到curElement这个对象

### What does the proposed API look like?

rangeStyleChange(payload,curElement)

**Comment by Hufe921** [comment]
instance.command.getRangeContext()
