### ISSUE TITLE
如何扩展自定义属性？

### ISSUE THREAD

**Issue by codepandy** [Hufe921/canvas-editor#293]
### What problem does this feature solve?

获取到控件后， 想添加一些扩展的自定义属性，但是保存后，获取的数据，自定义的属性都会丢失，这个是在哪处理的？如何实现自定义属性呢？

### What does the proposed API look like?

希望可以扩展对象属性。

**Comment by Hufe921** [comment]
请详细说明一下你的使用方法（代码），及使用场景

**Comment by codepandy** [comment]
使用场景：医生在编辑模板的时候，有些字段需要和国家的一些编码进行关联，因此控件对象上需要绑定额外的字段，方便保存的时候相关的数据去进行验证；
另外有些字段有校验的功能，比如必填，提示，格式等等，能否提供这些参数
![image](https://github.com/Hufe921/canvas-editor/assets/16410281/118e244a-d1f1-49be-9cd4-266b32c8fcb0)

**Comment by Hufe921** [comment]
现在可以增加扩展属性功能，但是控件的验证规则、格式等需后续更新

**Comment by codepandy** [comment]
嗯嗯，好的，感谢大佬

**Comment by codepandy** [comment]
@Hufe921 大佬，现在能增加扩展属性，但是无法更改，能否扩展`setControlValue`方法，或者提供一个设置`extension`的方法`setControlExtensionById(payload)`

**Comment by codepandy** [comment]
大佬威武
