### ISSUE TITLE
vue-router切换后页面空白问题

### ISSUE THREAD

**Issue by kendrickcheung007** [Hufe921/canvas-editor#294]
我按照这里的步骤在vue页面进行实例化：https://hufe.club/canvas-editor-docs/guide/start.html#step-3-%E5%AE%9E%E4%BE%8B%E5%8C%96%E7%BC%96%E8%BE%91%E5%99%A8

页面主动刷新没有问题，但是点击路由来回跳转之后，页面空白，控制台无输出。

**Comment by Hufe921** [comment]
编辑器与框架无关，经测试也正常：https://codesandbox.io/s/inspiring-meadow-mkfq9j?file=/src/views/Home.vue
请确认项目代码是否使用正确，或提供最小可复现demo

**Comment by kendrickcheung007** [comment]
> 编辑器与框架无关，经测试也正常：https://codesandbox.io/s/inspiring-meadow-mkfq9j?file=/src/views/Home.vue 请确认项目代码是否使用正确，或提供最小可复现demo

感谢回答，打扰了。已经确认是项目父组件存在问题，跟编辑器无关。
