### ISSUE TITLE
调用executeSetControlValue时报错

### ISSUE THREAD

**Issue by codepandy** [Hufe921/canvas-editor#302]
### version

0.9.52

### Steps to reproduce

给控件设置值时，\core\range\RangeManager.ts中shrinkBoundary方法，startElement 有可能不存在，导致报错。
代码修改如下可解决：
```
- if (startElement.controlComponent === ControlComponent.PLACEHOLDER)
+ if (startElement && startElement.controlComponent === ControlComponent.PLACEHOLDER)
```

### What is expected?

不报错，加上对象存在判断

### What is actually happening?

报错，没做对象存在判断

**Comment by Hufe921** [comment]
有没有最小可复现步骤或者代码

**Comment by codepandy** [comment]
@Hufe921 复现步骤如下：
创建一个病历先进行保存，病历里面有内容，比如姓名，conceptId是123456
然后重新打开病历，填充之前保存的值
这时对病历里面的文本控件进行赋值
```
instance.command.executeSetControlValue({conceptId:'123456',value:"张三"})
```
这时就报错了。
