### ISSUE TITLE
从官网下载的npm i @hufe921/canvas-editor --save 依赖不全？

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#304]
### version

current

### Steps to reproduce

- 按照官网顺序，入门页面，项目报错信息为：无法加载http://localhost:5174/node_modules/@hufe921/src/editor/core/draw/Draw.ts 的内容（HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE）
- 追查 路径发现@hufu921依赖包下只有个canvas-editor文件夹，且为空。

- 整个报错信息为：
TypeError: Cannot read properties of null (reading 'append')
    at Draw._wrapContainer (Draw.ts:974:12)
    at new Draw (Draw.ts:162:21)
    at new Editor (index.ts:215:17)
    at AboutView.vue:10:1

### What is expected?

怎么解决呢？upupup！！！

### What is actually happening?

#  整个报错信息为：
TypeError: Cannot read properties of null (reading 'append')
    at Draw._wrapContainer (Draw.ts:974:12)
    at new Draw (Draw.ts:162:21)
    at new Editor (index.ts:215:17)
    at AboutView.vue:10:1

**Comment by Hufe921** [comment]
请确认是否正确安装：https://www.npmjs.com/package/@hufe921/canvas-editor

**Comment by 55555778** [comment]
> 请确认是否正确安装：https://www.npmjs.com/package/@hufe921/canvas-editor

![image](https://github.com/Hufe921/canvas-editor/assets/90385480/da629fc8-ada9-4f57-a174-ea89a8833820)
![image](https://github.com/Hufe921/canvas-editor/assets/90385480/6fbf17e7-e922-4075-af68-fdda97d78809)

- 其中一个代码报错是：无法加载 http://localhost:5173/node_modules/@hufe921/src/editor/index.ts 的内容（HTTP 错误：状态代码 404，net::ERR_HTTP_RESPONSE_CODE_FAILURE）

- 完整组件代码如下
``` <template>
  <div class="about">
    <div class="canvas-editor"></div>
  </div>
</template>

<script lang="ts">
import Editor from '@hufe921/canvas-editor'

new Editor(document.querySelector('.canvas-editor') as HTMLDivElement, {
  main: [
    {
      value: 'Hello World'
    }
  ]
})
</script>

<style>
@media (min-width: 1024px) {
  .about {
    min-height: 100vh;
    display: flex;
    align-items: center;
  }
}
</style>
```
### 大佬救命！！！

**Comment by Hufe921** [comment]
<img width="270" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/27001251/c149832a-a221-43fe-8ddd-4d1d61799797">
正确安装会有dist文件，可以尝试删除node_modules后，安装特定版本，如 npm i @hufe921/canvas-editor@0.9.52 --save

**Comment by 55555778** [comment]
> <img alt="image" width="270" src="https://user-images.githubusercontent.com/27001251/278269667-c149832a-a221-43fe-8ddd-4d1d61799797.png"> 正确安装会有dist文件，可以尝试删除node_modules后，安装特定版本，如 npm i @hufe921/canvas-editor@0.9.52 --save

- 有dist文件了还是报错，不知道什么问题。

**Comment by 55555778** [comment]
[report-test.zip](https://github.com/Hufe921/canvas-editor/files/13184418/report-test.zip)
文件如下，望大佬指正！！！ upup

**Comment by Hufe921** [comment]
onMounted后再获取dom。。。
