### ISSUE TITLE
表单模式控件插入签名图片, 无法删除,回退,控件无法继续输入值. 编辑模式正常.

### ISSUE THREAD

**Issue by lingyih** [Hufe921/canvas-editor#306]
### version

0.9.53

### Steps to reproduce

表单模式控件插入签名图片, 无法删除,回退,控件无法继续输入值. 

### What is expected?

可以正常删除,回退 ,输入值.

### What is actually happening?

表单模式控件插入签名图片, 无法删除,回退,控件无法继续输入值. 编辑模式正常.

**Comment by Hufe921** [comment]
v0.9.54
