### ISSUE TITLE
在已经生成基础数据的 场景中，想要通过点击  add 按钮，在最下面增加一些数据，该如和实现呢

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#309]
### What problem does this feature solve?

![image](https://github.com/Hufe921/canvas-editor/assets/90385480/a5784dcd-6e4f-49f6-9029-fe06ba0bcc4b)
```点击+号，可以模块数据，放到最后面。```

1. 是在main.ts文件内，将数据全部转化为{
        value: 'd',
        highlight: '#b3b342',
        metrics: {
          width: 8.751998901367188,
          height: 16,
          boundingBoxAscent: 11.423999786376953,
          boundingBoxDescent: 0
        },
        style: '16px Yahei'
      },
      数据结构，push进data数据，之后在执行强制刷新instance.command.executeForceUpdate({})方法？
 2. 还是在mock.ts 内执行呢？

### What does the proposed API look like?

- 其中我在目录里 使用了 Sortablejs插件，已经实现了拖动一级目录可以同步canvas内的内容切换。

- 推荐给 大佬坐在后期拓展中。 实现 一二三.... 级目录的上下拖拽，将内容进行换位。

- 期待大佬的提示，解决上述问题。

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeappendelementlist
