### ISSUE TITLE
License

### ISSUE THREAD

**Issue by alfmoh** [Hufe921/canvas-editor#31]
Great project.
Is there a license for this project? For example, MIT, Apache, etc. If there is, could you please add the license information to the project.
Thank you

**Comment by Hufe921** [comment]
license has been added,please see: [bd0fd09](https://github.com/Hufe921/canvas-editor/commit/bd0fd0961885a15bdddc08731aa483643d3c5c55)
thanks

**Comment by alfmoh** [comment]
Thank you.
