### ISSUE TITLE
完全控制右键菜单，删除右键内部菜单

### ISSUE THREAD

**Issue by 10jinzhi** [Hufe921/canvas-editor#310]
### What problem does this feature solve?

可以删除打印功能。有关表格的操作会报错，我想重写然后catch

### What does the proposed API look like?

instance.register.contextMenuList([]);这样子会清空右键菜单。
  const contextMenuList = await instance.register.getContextMenuList();这样获取到的菜单数据符合格式定义，方便复制粘贴二次加工。

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/300
