### ISSUE TITLE
纸张方向为横向时，设置页边距出错

### ISSUE THREAD

**Issue by guxianghui111** [Hufe921/canvas-editor#315]
### version

0.9.53

### Steps to reproduce

https://hufe.club/canvas-editor/
打开界面后，设置纸张方向为横向后，在设置页边距，改变上边距，界面上变动的是左边距，改变右边，距界面上变动的是上边距，4个设置边距的方向都错了。

### What is expected?

边距设置错误

### What is actually happening?

边距设置正确

**Comment by Hufe921** [comment]
设置横向时，相当于纸张向左旋转90度，[top,right,bottom,left]=>[right,bottom,left,top]
按此规则设置即可
