### ISSUE TITLE
导出文档功能

### ISSUE THREAD

**Issue by zhaoxuanHome** [Hufe921/canvas-editor#316]
### What problem does this feature solve?

我想把canvas-editor编辑器编写的内容导出成docx文件。
1、引入插件并使用：
import docxPlugin from '@hufe921/canvas-editor-plugin-docx';
//使用插件  导出文档方法
function executeWord() {
        instance.use(docxPlugin);
	if (instance && instance.command && instance.command.executeExportDocx) {
		instance.command.executeExportDocx({
			fileName: fileName.value
		});
	}
}

2、导出文档问题，导出文件使用微软office打开：
 1）字体类型、大小
编辑器内：微软雅黑字体，字号大小默认小四；
导出文件使用微软office打开：中文正文，字号21；
 2）表格内文字位置无法设置（居中）
 3）表格无法设置底纹颜色

### What does the proposed API look like?

1、导出文档格式参考微软 office
2、表格的自适应

**Comment by Hufe921** [comment]
请在https://github.com/Hufe921/canvas-editor-plugin 插件项目中提issues

**Comment by XiYang66** [comment]
请问这个API
**instance.executeExportDocx({
  fileName: string
})**
是否支持获取word文件流？
