### ISSUE TITLE
在操作文档的时候导致表格分裂成2个, 后续合并在一个页面中时无法复原

### ISSUE THREAD

**Issue by HaishengLiang** [Hufe921/canvas-editor#317]
### What problem does this feature solve?

1、在对文档进行内容调整的时候导致表格进入下一页被分割成了2个表格
2、继续添加内容使得被分割的表格进入同一页后, 两个表格无法整合还原
如下:
![image](https://github.com/Hufe921/canvas-editor/assets/1995687/f7576438-2e0a-4d40-888d-0ada4c6b3c54)
希望能进行整理 自动或者手动均可

### What does the proposed API look like?

无

**Comment by HaishengLiang** [comment]
当一个单元格的文本超出一页长度会出现展示异常  
![image](https://github.com/Hufe921/canvas-editor/assets/1995687/cf6d2121-15c6-42f8-8df1-cf1b051454b9)

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/41
