### ISSUE TITLE
excel复制表格时，会新增一个图片出来

### ISSUE THREAD

**Issue by wdzyy** [Hufe921/canvas-editor#318]
### version

最新

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/22287693/bd3770d2-9990-4ae2-b514-3621e07cbf1d)

当从excel复制表格数据过来时，h会识别成file和text/ 这几个类型，导致最终会把表格转化成一个图片插入在表格后面。

### What is expected?

不插入图片

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/22287693/c49979ae-da97-4991-a77c-6bbb5268a692)

**Comment by wdzyy** [comment]
我在本地做了绕过处理。不知道作者是否可以看下这个问题是否需要修复。

**Comment by HaishengLiang** [comment]
复制word的表格的时候好像也会有这个现象
