### ISSUE TITLE
如何获取和修改Element的值，比如日期

### ISSUE THREAD

**Issue by codepandy** [Hufe921/canvas-editor#322]
### What problem does this feature solve?

之前增加了修改控件的值，但是能编辑的不止congtrol，还有element，能否增加获取和修改element的方法？

另外能否增加编辑element属性的方法，比如deletable这个属性。

### What does the proposed API look like?

getElementById
setElementValueById

**Comment by HaishengLiang** [comment]
我的理解 , 日期属于控件的范畴
这块可能可以合并一下
这样就可以复用control的api

当然element的api是另一个设计了
不知道我的理解是否正确
如有错误, 望指正
