### ISSUE TITLE
期望除了文本、选择外, 能够有一个表格类的控件

### ISSUE THREAD

**Issue by HaishengLiang** [Hufe921/canvas-editor#325]
### What problem does this feature solve?

在做一些外部数据导入的控制场景中需要导入表格类数据
虽然可以使用api来完成输入
但是这样的输入要么在编辑的时候会被用户修改, 要么就是再下次修改的时候无法识别原来的数据
能否有个表格的控件可以控制输入数据
期待  

### What does the proposed API look like?

无

**Comment by Hufe921** [comment]
表格类控件不太合适。
如果提供一个接口可以获取到这个表格，并可以设置可编辑属性，是否满足需求
