### ISSUE TITLE
打印表格问题

### ISSUE THREAD

**Issue by wzk-jiuyinghuo** [Hufe921/canvas-editor#326]
### version

0.9.46

### Steps to reproduce

再编辑页面展示表格完整，但是再打印页面表格串行

### What is expected?

![image](https://github.com/Hufe921/canvas-editor/assets/120085726/bb7424b6-6db1-461e-997f-cb489673c8d2)

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/120085726/466a0e10-52dd-4c6e-a5a0-357a3a738b90)

**Comment by Hufe921** [comment]
提供一下完整的data，或最小可复现demo（https://codesandbox.io/）

**Comment by wzk-jiuyinghuo** [comment]
[content.txt](https://github.com/Hufe921/canvas-editor/files/13359363/content.txt)
[options.txt](https://github.com/Hufe921/canvas-editor/files/13359365/options.txt)
content和options

**Comment by wzk-jiuyinghuo** [comment]
您好，我现在uniapp上可以实现编辑器，但是在只读模式下，点击编辑器还是回呼出键盘，麻烦请问下您这边有没有什么办法可以解决这个问题
