### ISSUE TITLE
如何在mock.ts里进行请求数据成功之后，再执行数据处理呢？

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#327]
### What problem does this feature solve?

- 目前正在做初始化项目数据。
- 已经做了 数据拖动，删除标题内的数据，插入数据，动态更新目录数据。

在mockts里进行请求数据之后， 尝试用了异步处理下面的数据初始化，但会报错。

### What does the proposed API look like?

目前尝试了 异步，和方法拆分。

**Comment by 55555778** [comment]
大佬 创个交流群吧，让菜鸟们互相帮助一下

**Comment by Hufe921** [comment]
mock.ts 仅为了演示编辑器项目，可以使用@hufe921/canvas-editor 官方npm包去二次开发
