### ISSUE TITLE
初始化之后没有富文本的操作栏，如何实现呀？

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#330]
### What problem does this feature solve?

    <script setup lang="ts">
    import Editor, { RowFlex, EditorMode } from '@hufe921/canvas-editor'
    import { onMounted } from 'vue'

    const setEdit = () => {
     new Editor(
     document.querySelector('.canvas-editor')!,
     {
      header: [
        {
          value: 'Header',
          rowFlex: RowFlex.CENTER
        }
      ],
      main: [
        {
          value: 'Hello World'
        }
      ],
      footer: [
        {
          value: 'canvas-editor',
          size: 12
        }
      ]
      },
      {
      // 全局配置
      mode: EditorMode.READONLY
      }
     )
     }
     onMounted(() => {
          setEdit()
           })
      </script>

       <template>
      <main>
       <div class="canvas-editor"></div>
      </main>
     </template>

<img width="664" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/90385480/9d5fb8af-1d36-4ee4-af6d-a80329f3eac7">

### What does the proposed API look like?

- 是否需要填写什么配置项呢？

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/start.html
