### ISSUE TITLE
 动态高亮关键字

### ISSUE THREAD

**Issue by xingliang123** [Hufe921/canvas-editor#332]
### What problem does this feature solve?

在编辑内容的时候（在控件中输入），如何遇到关键字进行变色

### What does the proposed API look like?

在编辑内容的时候（在控件中输入），如何遇到关键字进行变色

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executesearch
试一下这个api是否满足

**Comment by xingliang123** [comment]
这个是内容查找的吧。可能是我没有描述清楚 我想实现的是：每个控件都可以设置关键字，当该控件中包含该关键字时，该字变色
不同的控件可以设置不同的关键字，不同的颜色。比如说：病例诊断：癌细胞；这个病例诊断是一个文本框控件，癌字为关键字变红。  标本名称：样本呈阳性 。 标本名称也是一个文本框控件。阳性变为绿色

**Comment by xingliang123** [comment]
这个功能可以提供一个示例吗

**Comment by Hufe921** [comment]
```
  instance.command.executeSetControlHighlight([
    {
      conceptId: '1',
      ruleList: [
        {
          backgroundColor: 'red', // 可选，默认使用搜索颜色配置
          alpha: 0.6, // 可选，默认使用搜索透明度配置
          keyword: '高'
        },
        {
          keyword: '低'
        }
      ]
    }
  ])
```

**Comment by xingliang123** [comment]
可以修改字体的颜色吗？而不是修改背景色

**Comment by Hufe921** [comment]
重新发起一个issue

> 可以修改字体的颜色吗？而不是修改背景色
