### ISSUE TITLE
工具栏按钮点了之后不能取消

### ISSUE THREAD

**Issue by xingliang123** [Hufe921/canvas-editor#334]
### version

0.9.53

### Steps to reproduce

双击选工具栏按钮之后，不能取消了

### What is expected?

双击选工具栏按钮之后，不能取消了

### What is actually happening?

双击选工具栏按钮之后，不能取消了

### System Info

```shell
双击选工具栏按钮之后，不能取消了
```

### Any additional comments?

双击选工具栏按钮之后，不能取消了

**Comment by Hufe921** [comment]
提issue需描述清楚问题，及复现步骤
