### ISSUE TITLE
使用instance.command.executeSetValue 替换数据之后，再使用 await instance.command.getCatalog() 获取来的id数据不同了。

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#335]
### What problem does this feature solve?

有什么办法更新目录数据的吗？

### What does the proposed API look like?

有更新全局数据的方法吗？

**Comment by Hufe921** [comment]
具体描述一下 想要实现的需求效果

**Comment by 55555778** [comment]
已经解决啦
