### ISSUE TITLE
表格断行了

### ISSUE THREAD

**Issue by yicheng2022** [Hufe921/canvas-editor#336]
### version

0.9.56

### Steps to reproduce

1、表格分页了
2、删除前面一页的几行
3、后面一页的表格会自动顶到前面一页
4、但是顶回来的表格与前面这页的表格断行了

### What is expected?

不应该断行

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/103647012/7bd28a6e-8f35-442c-a955-83e1364e5df7)

**Comment by Hufe921** [comment]
#41
