### ISSUE TITLE
插件使用

### ISSUE THREAD

**Issue by xingliang123** [Hufe921/canvas-editor#337]
### What problem does this feature solve?

使用版本 ：0.9.53
使用方式：将源码引入到项目中
这样是不能使用新开发的插件的吗？
PDF预览可以发布成插件包吗 

### What does the proposed API look like?

使用版本 ：0.9.53
使用方式：将源码引入到项目中
这样是不能使用新开发的插件的吗？
PDF预览可以发布成插件包吗

**Comment by Hufe921** [comment]
1. 不推荐使用源码的方式进行开发（插件设置了peerDependencies:@hufe921/canvas-editor,所以不能在源码中使用插件），请使用官方npm包。
2. 如果生成可复制文字的pdf，前端生成会受限于字体文件无法用于生产环境，建议由后端生成。如果仅是截图并插入到pdf内，可以在插件仓库提issue
