### ISSUE TITLE
什么状态下会加入一个<br>标签呢？ 字体下拉列表掉下来了。

### ISSUE THREAD

**Issue by 55555778** [Hufe921/canvas-editor#339]
### What problem does this feature solve?

![image](https://github.com/Hufe921/canvas-editor/assets/90385480/43fac965-ea9a-4a14-b379-dbae65632559)
问题是这样的！

### What does the proposed API look like?

多了两个<br>标签

**Comment by Hufe921** [comment]
检查自己项目代码有无问题
