### ISSUE TITLE
增加默认控件样式设置

### ISSUE THREAD

**Issue by HoChine** [Hufe921/canvas-editor#340]
instance.command.executeSetRange(startIndex: number , endIndex: number)

比如，我想要在第二页的某处位置文字后面（比如：日期:{date}）插入一段日期，
在不主动鼠标点击获取焦点的情况下，executeInsertElementList会找不到插入的位置。

所以想到到先去设置选区再执行插入api，但是我又找不到${date}所在位置的startIndex，所以无法设置选区。
希望能够得到指点，如何去完成这个需求。

**Comment by Hufe921** [comment]
具体需求是什么

**Comment by HoChine** [comment]
需要在指定的某处插入一段文本，但找不到某处的位置去插入。

**Comment by Hufe921** [comment]
为什么会有这个使用场景，不应该根据光标所在位置，或者追加到文档末尾/开始处。

如何查找到一段文本，关键词搜索？

**Comment by HoChine** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/24770734/bcd5accb-7f8d-4520-8a34-c52714293bdb)

假如我接口获取到数据，想要把数据追加到相应的位置，这时候就是没有光标位置的场景。
我获取到不到【项目名称：】这几个关键词所在的具体位置，无法在它后面插入对应的文本。

我目前的做法就是搜索到【项目名称：】 ,然后整体替换为  【项目名称：XXXXXX】,也能勉强实现。
但还是想来问一下，有没有办法能让我把光标定位到【项目名称：】 这个关键词后面，这样就可以拥有更多的灵活性去插入文本。

**Comment by Hufe921** [comment]
应该用文本控件来承载数据，并根据唯一id去动态插入数据，如演示地址https://hufe.club/canvas-editor/ 中的“其他补充”
如：
项目名称：{请输入项目名称}
任务名称：{请输入任务名称}

**Comment by HoChine** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/24770734/ac4d8e2e-be1d-43d7-9eb8-99c79b2c56fa)

这个使用的时候，只填入占位符，不设置默认值，会丢失样式。
编辑文档时有样式，数据保存后，再重新渲染，文本控件的文字样式会丢失。

如果占位符和默认值都有的话，样式就会被保存，是设计如此吗？

**Comment by Hufe921** [comment]
文本控件内样式不会丢失，可以给出一个复现demo

**Comment by HoChine** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/24770734/270c1fed-ba14-42a0-b83c-31b0e599b24d)

[demo.zip](https://github.com/Hufe921/canvas-editor/files/13455018/demo.zip)

**Comment by sunjianfengHub** [comment]
@HoChine 后来有解决吗？这个控件模式没有带有默认样式配置的功能，我希望控件出生就是‘初号’，但似乎并不具备如此的有效配置
