### ISSUE TITLE
关于连页模式下，文档的Header标题不显示的问题

### ISSUE THREAD

**Issue by kendrickcheung007** [Hufe921/canvas-editor#341]
## 一、描述

1. 这是分页模式下的

![image](https://github.com/Hufe921/canvas-editor/assets/90102209/9932a303-177b-4c61-9dd7-31fd34448d2d)

2.  这是连页模式下的

![image](https://github.com/Hufe921/canvas-editor/assets/90102209/67c0e050-bc4f-4405-9903-d8b9bc9dda51)

## 二、需求

我想连页模式下也显示header，可以设置吗

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/200
连页模式下header直接写在内容区即可
