### ISSUE TITLE
大佬，getRangeContext这个函数删除了吗？

### ISSUE THREAD

**Issue by codepandy** [Hufe921/canvas-editor#343]
### What problem does this feature solve?

这个函数是不是删除了，能否再加上，或者有没有其他方法能来获取当前点击的内容或控件

### What does the proposed API look like?

希望恢复这个函数

**Comment by Hufe921** [comment]
没删除啊

**Comment by codepandy** [comment]
新拉的代码确实没有
![新代码](https://github.com/Hufe921/canvas-editor/assets/16410281/c08f28d0-9d28-415d-ab52-40ddcd027a51)
![老代码](https://github.com/Hufe921/canvas-editor/assets/16410281/bdd66c8b-66d4-455c-af0a-d481986b0624)

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/blob/main/src/editor/core/command/Command.ts#L204C9-L204C9

**Comment by codepandy** [comment]
我的错
