### ISSUE TITLE
希望可以增加判断是否被编辑、记录下编辑内容、页面脚本、每页出现功能

### ISSUE THREAD

**Issue by exqmjmz** [Hufe921/canvas-editor#344]
### What problem does this feature solve?

作者您好，canvas-editor是一个很好的富媒体文本编辑器。
在产品文档查阅和开发过程中，发现找不到类似的接口实现以下功能：

1、判断这次加载的文件是否被编辑过
2、记录哪些内容被删除、修改、新增
3、数据加载进来后执行页面样式处理脚本
4、段落、行、表格，每页重复出现

关于第一点需求，具体应用场景描述：
在用户加载进来这批数据后，能够监听页面上数据的变动，当用户修改时记录成已修改，如果修改后又还原成了原本的样式。那么这时候可以重新记录成未修改，这时候需要做加载前数据与加载后所修改数据进行比对。

关于第二点需求，具体应用场景描述
用户记录下用户修改数据，
如果是在行、段落、单元格内删除内容，并重新输入新的内容这时候可以记录下修改前是什么内容，修改后是什么内容；
如果是删除后未在该行、段落、单元格新增内容，记录为删除；
如果是在空白行、段落、单元格新增内容，记录为新增。

关于第三点需求，具体应用场景描述
数据加载进来后，需要再对页面进行二次处理，比如根据某些逻辑条件标注数据颜色、自动向上合并或向右合并单元格、根据某些条件自动输出不同的表格模版。不一定需要通过代码脚本实现，也可以通过占位符的方式实现类似功能。
其他产品实现方式：
以下是docx-templates这个库实现的方式
https://github.com/guigrpa/docx-templates

![image](https://github.com/Hufe921/canvas-editor/assets/12406935/954a12b2-1eef-4f18-b470-964794ee6269)
![image](https://github.com/Hufe921/canvas-editor/assets/12406935/bf2810ff-2acb-4271-91ab-369374990e87)

http://guigrpa.github.io/2017/01/01/word-docs-the-relay-way/
![image](https://github.com/Hufe921/canvas-editor/assets/12406935/6ffb1923-7ae6-4ab2-a8e6-ddd590e11e0c)
![image](https://github.com/Hufe921/canvas-editor/assets/12406935/32641e33-132a-4b8d-8842-f97deaac5c41)

关于第四点需求，具体应用场景描述
能对行、段落、表格，设置换页后可重复出现在不同页，比如以下案例，header、footer是重复固定段落，data是数据行。data数据不固定，如果data数据过多导致换页，header、footer换页后重复显示。
![image](https://github.com/Hufe921/canvas-editor/assets/12406935/f99af614-936f-4f17-b7f4-939f41edec0b)

### What does the proposed API look like?

/

**Comment by yang317621308** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/33524998/2a133876-384a-4f82-89f1-f03929806bc2)
上图中，报表头，和尾部均可控制是否每页打印，中间的明细网格，可做数据循环，循环体会根据页面剩余尺寸，显示数据行，如果当前页面无法显示全，会自动分页至下页。直至数据全部渲染完毕。希望作者可以考虑一下。此软件是锐浪的报表插件。

**Comment by Hufe921** [comment]
1. 可以通过contentChange来判断内容是否更改，考虑添加更加方便的api进行查询或重置状态。不过修改之后又修改回去，不算修改的特性。因为性能不考虑去做。
2. 痕迹模式待增加
3和4更像是报表软件，我要考虑一下要不要实现

**Comment by yang317621308** [comment]
3和4，确实是报告的功能，不过在现实场景中，感觉比较实用，希望考虑实现一下此功能。
