### ISSUE TITLE
新增区域和区域特性建议

### ISSUE THREAD

**Issue by haiyunxiong** [Hufe921/canvas-editor#345]
### What problem does this feature solve?

建议新增区域和区域特性建议，场景如下图：
![微信截图_20231127174729](https://github.com/Hufe921/canvas-editor/assets/127080793/483bdc71-40ec-45d4-bcfd-942ea1933726)

### What does the proposed API look like?

1、报告医生不能修改某些区域的内容（区域内容制度）
2、可以设置某些区域内容对齐方式

**Comment by Hufe921** [comment]
1. 控件增加只读设置
2. 控件内文本左对齐方式设置

**Comment by haiyunxiong** [comment]
这个功能什么时候可以完善呢？

**Comment by Hufe921** [comment]
1. 控件增加只读设置
使用`disabled: true`属性，限制只读
2. 控件内文本左对齐方式设置
使用
`indentation: ControlIndentation.VALUE_START` 控制缩进规则

![image](https://github.com/Hufe921/canvas-editor/assets/27001251/c9b6a0a4-c1d6-4e17-8c8b-4f803b40304c)
```
{
    conceptId: '1',
    type: ControlType.TEXT,
    value: [
      {
        value: '一. 高血压\n二. 过敏性鼻炎\n三. 上呼吸道感染',
        font:''
      }
    ],
    placeholder: '其他补充',
    prefix: '{',
    postfix: '}',
    indentation: ControlIndentation.VALUE_START
  }
```
