### ISSUE TITLE
希望增加 页码 的自定义设置

### ISSUE THREAD

**Issue by HoChine** [Hufe921/canvas-editor#346]
在编写实验报告的场景下，常规来说 封面和目录是不计入页码的
正文是从目录之后才开始算页码的，希望能够增加一个自定义页码起始页的api.

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/option.html#%E9%A1%B5%E7%A0%81%E9%85%8D%E7%BD%AE
