### ISSUE TITLE
作者能否考虑在页面中插入附件📎的功能

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#356]
### What problem does this feature solve?

作者能否考虑在页面中插入附件📎的功能

### What does the proposed API look like?

在页面中插入附件非常重要特别是在协作中会有一些文档/文件，如：PDF报告，一些视频（胃镜，肠镜）需要给协作方查看。如果能在页面中添加附件对方可以点击查看会非常完美。

**Comment by Hufe921** [comment]
1. 可以将附件上传至服务器，在获取url后，将url地址插入文档
2. 在线的pdf、视频也可以用[block元素](https://hufe.club/canvas-editor-docs/guide/schema.html)插入文档直接给三方查看
