### ISSUE TITLE
火狐浏览器下： 输入文字时，会出现多添加一遍文字

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#357]
### version

0.9.57

### Steps to reproduce

图片提不上去

### What is expected?

在官网的demo中也有这种情况

### What is actually happening?

无

**Comment by Hufe921** [comment]
1. 请确保使用正确的json格式
2. 正文添加文字，指的是如何添加
提供最小可复现demo

**Comment by 18259669383** [comment]
1. 列举控件添加的时候，默认值添加失败：
![Snipaste_2023-12-06_16-23-44](https://github.com/Hufe921/canvas-editor/assets/93261537/c9b6cafe-d1a0-4641-ad42-38edf68e3c41)
![Snipaste_2023-12-06_16-23-58](https://github.com/Hufe921/canvas-editor/assets/93261537/5e7c4ed7-3fb2-4022-9dff-b90f94697f13)
![Snipaste_2023-12-06_17-04-44](https://github.com/Hufe921/canvas-editor/assets/93261537/321f6359-1b50-4d5e-8e59-e099c99f1478)
2. 正文添加文字的时候，会出现多添加一遍文字：
添加文字的方式就是正常的打字输入。不过是在编辑模式下，可以在作者你的官网demo中尝试一下就能明白，或者说这是一个特殊的设定？

**Comment by Hufe921** [comment]
1. 默认值应为code
2. 使用的什么输入法

**Comment by 18259669383** [comment]
1. 是的，第一个问题是我提出错误了，
2. 使用的是搜狗输入法

**Comment by Hufe921** [comment]
无法复现，写一下系统环境npx envinfo --system --binaries --browsers，并录个屏看看效果
