### ISSUE TITLE
在word上编辑好的表格，再复制到编辑器中格式没有复制过去

### ISSUE THREAD

**Issue by wzk-jiuyinghuo** [Hufe921/canvas-editor#358]
### What problem does this feature solve?

您好，我在word中编辑好的表格模板，在复制到粘贴到编辑器中出现了以下几个问题：
1、表格的行高和列宽并没有是对应的编辑好的行高；
2、表格在分页的时候出现了问题；
![image](https://github.com/Hufe921/canvas-editor/assets/120085726/42267c67-a398-44dd-a816-b6552c78bd3b)
3、如果复制的表格高度超过了一页纸的高度，表格回自动进入到第二页，然后在表格模板点击空格，会回到第一页；

### What does the proposed API look like?

麻烦问一下，是现在编辑器本身就无法带格式粘贴，还是我操作的过程有些问题！

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/41
