### ISSUE TITLE
关于此项目的发展方向和趋势

### ISSUE THREAD

**Issue by wenbei421** [Hufe921/canvas-editor#359]
### What problem does this feature solve?

你好，通过对你的一些信息了解，你的网站备案域名在安徽，作者你是否在合肥，此项目开源的目的是什么，你会一直维护下去吗？有没有意愿加入医疗软件公司，带更多的人来维护此项目，发挥你的才能，微信号：wenbei_7650。

### What does the proposed API look like?

无

**Comment by Hufe921** [comment]
非常感谢你对本项目的关注。我将继续努力维护并致力于项目的发展，同时热切期待更多人的参与。
开源的目的是基于canvas的富文本编辑器非常少，希望通过这个项目为大家提供有益的资源。

**Comment by wenbei421** [comment]
目前有在公司任职吗？，是业余时间在维护此项目，还是全职在维护，有没有兴趣加入公司？
