### ISSUE TITLE
火狐浏览器下，打印的时候会多出一页

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#360]
### version

0.9.58

### Steps to reproduce

![微信图片_20231211153228](https://github.com/Hufe921/canvas-editor/assets/93261537/f8372c1d-bd87-4996-ac27-8bcf632d31bc)
![Snipaste_2023-12-11_15-33-17](https://github.com/Hufe921/canvas-editor/assets/93261537/caf3889d-295c-48c8-8316-9d1342cae4f2)
可使用官网的demo，进行查看

### What is expected?

无

### What is actually happening?

无

**Comment by 18259669383** [comment]
然后附加一个问题，instance.command.executeForceUpdate(options?: IForceUpdateOption) <----强制渲染文档的API，
我想实现的是一个动态切换模板的功能，但是不知道如何去修改数据源

**Comment by Hufe921** [comment]
火狐浏览器什么版本

**Comment by 18259669383** [comment]
> 火狐浏览器什么版本
![图片](https://github.com/Hufe921/canvas-editor/assets/93261537/c6d3c795-0ce7-4577-aea2-847027f0c47d)

**Comment by 18259669383** [comment]
![Snipaste_2023-12-12_16-30-05](https://github.com/Hufe921/canvas-editor/assets/93261537/095d4f71-65d2-4a27-a4d5-9f6ad3f268d1)

**Comment by Hufe921** [comment]
1. 使用自适应页面宽度，不要缩放

<img width="109" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/27001251/40fdfc38-7477-4165-9921-b0dbfe047b4b">

2.  火狐对字体名称要求比较严格，可以把字体设置成Microsoft YaHei，另外建议使用chrome、edge等chromium类浏览器

```
const options: IEditorOption = {
  defaultFont: 'Microsoft YaHei'
}
```

**Comment by 18259669383** [comment]
> 1. 使用自适应页面宽度，不要缩放
> 
> 
> <img alt="image" width="109" src="https://private-user-images.githubusercontent.com/27001251/289756976-40fdfc38-7477-4165-9921-b0dbfe047b4b.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzODk4MDksIm5iZiI6MTcwMjM4OTUwOSwicGF0aCI6Ii8yNzAwMTI1MS8yODk3NTY5NzYtNDBmZGZjMzgtNzQ3Ny00MTY1LTk5MjEtYjBkYmZlMDQ3YjRiLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFJV05KWUFYNENTVkVINTNBJTJGMjAyMzEyMTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjMxMjEyVDEzNTgyOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNkNzk0YTgxY2M0NDE3OGUyNmU1MzQ2YzEwM2FmM2JlOGE0YzE4ODQwYTEzYjNiNjU3MjNjNTQ4YThkOGUzODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3K0vZSU9c8cLjTTg_GbrB_ZqKW36-9wDciXjKJmKmPk">
> 
>     2. 火狐对字体名称要求比较严格，可以把字体设置成Microsoft YaHei，另外建议使用chrome、edge等chromium类浏览器
> 
> 
> ```
> const options: IEditorOption = {
>   defaultFont: 'Microsoft YaHei'
> }
> ```

好的，感谢
