### ISSUE TITLE
为什么焦点要一直绑定在面板上

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#365]
### version

0.9.58

### Steps to reproduce

![Snipaste_2023-12-15_14-57-08](https://github.com/Hufe921/canvas-editor/assets/93261537/b6495e4f-82c4-4315-a567-f88a8223da1a)
我在右侧的输入框中修改，但是焦点一直在面板中

### What is expected?

无

### What is actually happening?

无

**Comment by Hufe921** [comment]
因为调用了[executeLocationCatalog](https://github.com/Hufe921/canvas-editor/blob/main/src/main.ts#L1014)
