### ISSUE TITLE
作者你好，有没有vue2版本的呢，如果有 可以加我QQ1960512171详谈

### ISSUE THREAD

**Issue by zxrql** [Hufe921/canvas-editor#366]
### What problem does this feature solve?

作者你好，有没有vue2版本的呢，如果有 可以加我QQ1960512171详谈

### What does the proposed API look like?

作者你好，有没有vue2版本的呢，如果有 可以加我QQ1960512171详谈

**Comment by Hufe921** [comment]
编辑器与前端框架无关。
可使用官方npm包进行外围功能（菜单，容器等）开发，或使用官方仓库demo二次开发。
官方文档：https://hufe.club/canvas-editor-docs/
