### ISSUE TITLE
鼠标悬浮的时候是否能添加上提示的信息

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#367]
### What problem does this feature solve?

1. 鼠标经过页眉，和页脚区域的时候显示提示操作信息
![Snipaste_2023-12-19_16-57-01](https://github.com/Hufe921/canvas-editor/assets/93261537/27afd89d-4646-4b59-b92c-2ea52b3c62a0)

2. 正文如果不存在内容或着内容没在可视区域内的情况下，点击红色框的位置，会自动滚动到输入的位置，这个我看代码是刻意为之，会不会影响用户体验
![Snipaste_2023-12-19_17-02-17](https://github.com/Hufe921/canvas-editor/assets/93261537/08575fa5-57fe-491f-88e5-d452f365de94)

### What does the proposed API look like?

无

**Comment by 18259669383** [comment]
3. 该模板是由docx中复制粘贴到canvas-editor 中，在由它进行导出的数据，然后使用executeSetValue进行一个动态切换，但是我在切换模板的时候会出现这个情况，这个issue是否是要放在表格合并中
![Snipaste_2023-12-19_17-16-57](https://github.com/Hufe921/canvas-editor/assets/93261537/d4f4ae35-1b4a-4520-bf63-ba2fd8a82e5e)

**Comment by 18259669383** [comment]
还有一个问题，我看文档中写到有一个控件拖拽的功能，指的是哪一个控件可以进行一个拖拽

**Comment by Hufe921** [comment]
> 3\. executeSetValue

executeSetValue的数据提供一下

**Comment by 18259669383** [comment]
> > 3. executeSetValue
> 
> executeSetValue的数据提供一下

数据我明天去公司的时候回复，我现在拿不到

**Comment by 18259669383** [comment]
> > 还有一个问题，我看文档中写到有一个控件拖拽的功能，指的是哪一个控件可以进行一个拖拽
> 
> 选中一段文字，点击拖蓝区域，拖拽

好的，感谢解惑

**Comment by 18259669383** [comment]
> > 3. executeSetValue
> 
> executeSetValue的数据提供一下

[
[data.json](https://github.com/Hufe921/canvas-editor/files/13721521/data.json)
](url)

**Comment by BOKE2014** [comment]
> > 还有一个问题，我看文档中写到有一个控件拖拽的功能，指的是哪一个控件可以进行一个拖拽
> 
> 选中一段文字，点击拖蓝区域，拖拽

请问在线DEMO是不是没有这个拖拽功能？

**Comment by 18259669383** [comment]
> > > 还有一个问题，我看文档中写到有一个控件拖拽的功能，指的是哪一个控件可以进行一个拖拽
> > 
> > 
> > 选中一段文字，点击拖蓝区域，拖拽
> 
> 请问在线DEMO是不是没有这个拖拽功能？

作者的demo是有这个功能的，你选中（文本或者控件）之后，直接拖选中的区域，就能看到

**Comment by BOKE2014** [comment]
> > > > 还有一个问题，我看文档中写到有一个控件拖拽的功能，指的是哪一个控件可以进行一个拖拽
> > > 
> > > 
> > > 选中一段文字，点击拖蓝区域，拖拽
> > 
> > 
> > 请问在线DEMO是不是没有这个拖拽功能？
> 
> 作者的demo是有这个功能的，你选中（文本或者控件）之后，直接拖选中的区域，就能看到

好的，多谢！一会儿试试。

**Comment by Hufe921** [comment]
```
const options: IEditorOption = {
  zone: {
    tipDisabled: false // 开启提示（消耗性能）
  }
}

```
