### ISSUE TITLE
多次切换模板数据

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#369]
### version

0.9.58

### Steps to reproduce

使用executeSetValue作为切换数据的api，但是如果同一个模板多次使用executeSetValue会出现整个网页奔溃

### What is expected?

可以多次点击

### What is actually happening?

![Snipaste_2023-12-21_08-34-13](https://github.com/Hufe921/canvas-editor/assets/93261537/45c92b5d-02d4-4129-8cb8-9cfaaaafb5a2)
![Snipaste_2023-12-21_08-34-33](https://github.com/Hufe921/canvas-editor/assets/93261537/e0a71e5a-56fa-4303-854e-4b94daac971a)
![Snipaste_2023-12-21_08-36-17](https://github.com/Hufe921/canvas-editor/assets/93261537/30cc04ad-e762-4eb1-9a76-81fa97c01dd7)

**Comment by 18259669383** [comment]
附上代码
![Snipaste_2023-12-21_08-39-20](https://github.com/Hufe921/canvas-editor/assets/93261537/2d1e5dba-57a2-41dd-9a07-652b9739e9db)

**Comment by Hufe921** [comment]
json数据发一下
