### ISSUE TITLE
右键菜单中菜单项的图标

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#370]
### What problem does this feature solve?

![Snipaste_2023-12-21_09-15-05](https://github.com/Hufe921/canvas-editor/assets/93261537/7056e0de-1848-474c-a6bb-3c1a144af934)
这个右键菜单项的图标引入的方式，是否能更直观一点，或者说是我的使用方式存在着问题

### What does the proposed API look like?

能否直接引入一个svg，或者说一个路径的方式

**Comment by Hufe921** [comment]
使用CSS可以更加灵活设定样式，避免路径打包等问题
