### ISSUE TITLE
提示错误信息

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#372]
### What problem does this feature solve?

有些时候调用API，会传递一个错误的数据，虽然是我自己传输错误，但插件并没有反馈，也没有任何的反应，这个时候我就会以为是别的地方出现的错误

### What does the proposed API look like?

想说，能不能在出现这个情况的时候，控制台抛出错误

**Comment by Hufe921** [comment]
建议使用typescript进行约束
