### ISSUE TITLE
字显示成这样可能是啥原因？

### ISSUE THREAD

**Issue by yumi-toushou** [Hufe921/canvas-editor#373]
### version

last

### Steps to reproduce

粘贴进一大段文本

### What is expected?

期望字显示正常

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/62413654/47e7a41e-f4a7-44a4-bda8-e1309a8d25d5)

**Comment by Hufe921** [comment]
提供一下浏览器及版本信息

**Comment by yumi-toushou** [comment]
chrome    104.0.5112.124

**Comment by Hufe921** [comment]
升级一下浏览器，部分版本浏览器canvas渲染文本会出现残影。也可以试试在渲染完成之后强制使用 [executeforceupdate](https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeforceupdate)强制更新一下
