### ISSUE TITLE
通过executeSetHTML设置的标签元素携带的font-family会丢失

### ISSUE THREAD

**Issue by sevenbeking** [Hufe921/canvas-editor#380]
步骤：
1.在富文本编辑一段文字（设置了字体），通过instance.command.getHTML()获取并保存至服务器
2.初始化编辑器之后，通过executeSetHTML设置内容值，字体会丢失。
示例：
`
//赋值
instance.command.executeSetHTML({
  header: ``,
  main: `<span style="font-family: 华文楷体; font-size: 48px;">123</span>`,
  footer: ``
})
`

**Comment by sevenbeking** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/52279735/68e63954-f6b0-4f44-afdd-4c0572d159af)

**Comment by sevenbeking** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/52279735/99d0e498-34db-4e27-ae41-ef6567c3cd38)
![image](https://github.com/Hufe921/canvas-editor/assets/52279735/c60563a5-b281-485b-80e2-f29db8474bb9)

**Comment by Hufe921** [comment]
不要通过html进行数据的保存及还原，应该使用编辑器本身的结构化数据

**Comment by sevenbeking** [comment]
因为存储的数据需要给其他地方使用，所以项目要求存储的数据必须使用html结构
