### ISSUE TITLE
实现一个给模板添加数据的过程中出现的图片加载异常

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#381]
### version

0.9.59

### Steps to reproduce

当使用executeSetValue 切换完模板之后，我自己给模板中的控件添加值的时候（一个是模板的json，另一个是模板对应的json，两者进行一个匹配的操作），其中文本控件是没有问题，但我更改完模板的img对应的base64，然后在用executeSetValue 设置覆盖完的json时，图片加载不出来

### What is expected?

无

### What is actually happening?

如果描述不清晰的话，那么我会提供代码

**Comment by Hufe921** [comment]
提供一下代码

**Comment by 18259669383** [comment]
> 提供一下代码

抱歉，我昨天尝试了很久，确实会出现图片加载错误，但今天复现的时候，又可以了...
