### ISSUE TITLE
页眉或页脚功能禁用时，同时需禁用区域提示功能

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#386]
### What problem does this feature solve?

在非编辑模式下，如：只读模式等，disable页眉页脚的探测功能。

### What does the proposed API look like?

目前各种模式下页眉页脚的探测都是激活的，大佬可考虑优化一下提升用户体验。谢谢！

**Comment by abcjingtong** [comment]
有兴趣可以看看  http://hcview.cn/demo/HCEmrViewLib/index.html

**Comment by Hufe921** [comment]
探测功能是什么意思

**Comment by abcjingtong** [comment]
应该是说各种模式下，鼠标移动或点击页眉都有交互反应或响应，这个其实是正常的，因为并没有严格的定义只读时不允许复制操作。
