### ISSUE TITLE
表单模式下control控件内容可以被删除

### ISSUE THREAD

**Issue by zaoangod** [Hufe921/canvas-editor#387]
### version

分支：main，版本：v0.9.61

### Steps to reproduce

代码使用的是main分支示例代码

### What is expected?

在表单模式下，control控件不可以被删除

### What is actually happening?

在表单模式下 control 控件可以被删除
![image](https://github.com/Hufe921/canvas-editor/assets/15064137/5db1c48c-4e7e-4f59-8305-6e75db187518)
![image](https://github.com/Hufe921/canvas-editor/assets/15064137/7c9a2bdf-2508-4a13-98cf-83f94f253723)

**Comment by Hufe921** [comment]
设置控件属性：deletable
https://hufe.club/canvas-editor-docs/guide/schema.html
