### ISSUE TITLE
大神，文本控件怎么设置边框样式？

### ISSUE THREAD

**Issue by apistor** [Hufe921/canvas-editor#388]
### version

release: v0.9.61

### Steps to reproduce

创建一个文本控件，想给该输入框加一个边框。

### What is expected?

![微信截图_20240106170608](https://github.com/Hufe921/canvas-editor/assets/23349118/7dba388e-81ac-481b-b49b-0395451cf6b9)

### What is actually happening?

大神，我这边怎么才能给文本控件加边框呢？

**Comment by Hufe921** [comment]
{
      type: ElementType.CONTROL,
      value: '',
      control: {
        conceptId: '4',
        type: ControlType.TEXT,
        value: null,
        placeholder: '',
        prefix: '\u200c',
        postfix: '\u200c',
        minWidth: 160,
        underline: true,
        border: true // 设置边框
      }
    }
