### ISSUE TITLE
选择控件后，没有办法再修改控件的属性

### ISSUE THREAD

**Issue by apistor** [Hufe921/canvas-editor#391]
### version

release: v0.9.61

### Steps to reproduce

是否可以提供一个事件，可以弹出控件属性页面，重新修改控件属性。

### What is expected?

![微信截图_20240109141249](https://github.com/Hufe921/canvas-editor/assets/23349118/779d800c-f033-4a9f-8ee9-e5a28bc6b35b)

### What is actually happening?

目前修改只能删掉，重新插入。

**Comment by yang317621308** [comment]
希望作者大佬能增加一下该功能谢谢。

**Comment by apistor** [comment]
@Hufe921    这功能什么时候可以 安排上呀？

**Comment by yang317621308** [comment]
wx:yang317621308,联系我
