### ISSUE TITLE
3个文本控件样式问题（下划线、边框、宽度调整）

### ISSUE THREAD

**Issue by apistor** [Hufe921/canvas-editor#393]
### version

release: v0.9.61

### Steps to reproduce

三个文本控件样式：
1、下划线（实线、虚线）
2、边框 
3、输入域宽度可以调整（见下图）

### What is expected?

![微信截图_20240109142406](https://github.com/Hufe921/canvas-editor/assets/23349118/f66e1d99-9bac-4408-a98c-681b1e03df86)

### What is actually happening?

希望可以实现！

**Comment by Hufe921** [comment]
宽度设置：
```
 {
      type: ElementType.CONTROL,
      value: '',
      control: {
        conceptId: '4',
        type: ControlType.TEXT,
        value: null,
        placeholder: '',
        prefix: '\u200c',
        postfix: '\u200c',
        minWidth: 160, // 最小宽度
        underline: true
      }
    }
```
