### ISSUE TITLE
大佬将来有没有打算集成一些AI功能

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#394]
### What problem does this feature solve?

最近看到几个集成了AI功能的editor，大佬将来有没有这方面的考虑？

### What does the proposed API look like?

最近看到几个集成了AI功能的editor，大佬将来有没有这方面的考虑？

**Comment by Hufe921** [comment]
编辑器core不会内嵌ai接口，可以编写插件使用ai的能力。https://github.com/Hufe921/canvas-editor-plugin
