### ISSUE TITLE
下拉选，设置占位符，不显示

### ISSUE THREAD

**Issue by yang317621308** [Hufe921/canvas-editor#395]
### version

最新

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/33524998/0a6d56d3-a217-4fb4-8434-ece428c48359)
![image](https://github.com/Hufe921/canvas-editor/assets/33524998/96b99017-f5db-4533-a33f-c5ce3ecf9804)

### What is expected?

希望尽快修复该bug

### What is actually happening?

无

**Comment by Hufe921** [comment]
使用“code”而不是“代码”
```
[{"value":"有","code":"1"}]
```
