### ISSUE TITLE
希望图片上传时压缩一下，增加了以下代码，哪里有问题呢？

### ISSUE THREAD

**Issue by WaterCountry** [Hufe921/canvas-editor#396]
### What problem does this feature solve?

我在图片上传这里增加了一段压缩图片的代码，上传图片时，显示图片不正常，请帮助指正，谢谢
`  const imageDom = document.querySelector<HTMLDivElement>('.menu-item__image')!
  const imageFileDom = document.querySelector<HTMLInputElement>('#image')!
  imageDom.onclick = function () {
    imageFileDom.click()
  }
  imageFileDom.onchange = function () {
    const file = imageFileDom.files![0]!
    const fileReader = new FileReader()
    fileReader.readAsDataURL(file)
    fileReader.onloadend = function () {
      // 计算宽高
      const image = new Image()
      let value = fileReader.result as string      
      image.src=value
      const cv = document.createElement('canvas')
      const ctx = cv.getContext('2d') as CanvasRenderingContext2D

      image.onload = function () {  
        ctx.drawImage(image, 0, 0)         
        value= cv.toDataURL('image/jpeg', 0.7)       
        instance.command.executeImage({
          value,
          width: image.width,
          height: image.height
        })
        imageFileDom.value = ''
      }   
    }
  }`

### What does the proposed API look like?

无

**Comment by Hufe921** [comment]
https://developer.mozilla.org/zh-CN/docs/Web/HTML/Element/canvas#height
设置一下默认canvas的宽高

**Comment by WaterCountry** [comment]
多谢，解决了。

      // 计算宽高 
      const image = new Image()
      let value = fileReader.result as string      
      image.src=value
      const cv = document.createElement('canvas')
      const ctx = cv.getContext('2d') as CanvasRenderingContext2D 
      let imgtype = file.type
      image.onload = function () {
        let w = image.width
        let h = image.height
        if(w>800){
          const z=w/800
          w=800
          h=h/z
        }
        cv.width = w
        cv.height = h
        ctx.drawImage(image, 0, 0,w,h)
        const  dovalue = cv.toDataURL(imgtype, 0.5)
        //console.log('原来',value.length/1024,'kb\n压缩', dovalue.length/1024,'kb',imgtype)
        if(dovalue.length<value.length){
          value = dovalue
          //console.log('使用压缩图片')
        }
        else{
          //console.log('使用原来图片')
        }
        instance.command.executeImage({
          value,
          width: w,
          height: h
        })
        imageFileDom.value = ''
      }
