### ISSUE TITLE
是否可以加上 控件、表格的复制粘贴 功能

### ISSUE THREAD

**Issue by apistor** [Hufe921/canvas-editor#397]
### version

release: v0.9.61

### Steps to reproduce

目前只可以复制粘贴文本，但插入的控件、表格 无法复制与粘贴。

### What is expected?

是否可以加上 控件、表格的复制粘贴 功能

### What is actually happening?

希望可以自由的复制黏贴，给书写带来快捷。

**Comment by BOKE2014** [comment]
在表格的最右侧点击两次可以实现复制整个表格，然后再粘贴就成功了，但是使用起来比较麻烦：（

**Comment by apistor** [comment]
表格试了一下可以复制黏贴，但控件不可以。

**Comment by BOKE2014** [comment]
> 表格试了一下可以复制黏贴，但控件不可以。

控件确实不能复制也不能修改已有控件的参数。每次只能重新做，这个比较麻烦。
