### ISSUE TITLE
批注优化

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#399]
### What problem does this feature solve?

经测试发现：添加多个标注（包括标准文字比较多）的时候，右侧显示标注的card无法显示全。再有如何编辑和删除标注？
![Uploading 截屏2024-01-11 13.34.03.png…]()

### What does the proposed API look like?

经测试发现：添加多个标注（包括标准文字比较多）的时候，右侧显示标注的card无法显示全。再有如何编辑和删除标注？

**Comment by Hufe921** [comment]
编辑器仅关注核心（src/editor），批注仅是编辑器演示demo，具体交互可自行优化
