### ISSUE TITLE
[bug] 表单模式，页眉中有文本控件，还是需要双击页面才能输入。

### ISSUE THREAD

**Issue by apistor** [Hufe921/canvas-editor#400]
### version

release: v0.9.61

### Steps to reproduce

1、在页面中添加文本控件
2、点击表单模式
3、往文本控件输入内容

### What is expected?

![微信图片_20240111151118](https://github.com/Hufe921/canvas-editor/assets/23349118/9ec5cc87-15e8-486f-83bd-5a9591301160)

### What is actually happening?

希望可以直接输入，不再双击页眉

**Comment by Hufe921** [comment]
区域切换和编辑器模式无关，需要双击才能切换，具体可参考office word、wps等
