### ISSUE TITLE
文本控件中添加回车换行 样式没有生效

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#407]
### version

0.9

### Steps to reproduce

文本控件中换行 然后把当前文书内容保存起来 再重新打开回车变成了空格 没有生效

### What is expected?

文本控件中换行 然后把当前文书内容保存起来 再重新打开回车变成了空格 没有生效

### What is actually happening?

文本控件中换行 然后把当前文书内容保存起来 再重新打开回车变成了空格 没有生效

**Comment by Hufe921** [comment]
升级最新版本试试

**Comment by myNameWZH** [comment]
好的 大佬

**Comment by myNameWZH** [comment]
升级了 发现还是不行 o(╥﹏╥)o

**Comment by myNameWZH** [comment]
可以了
