### ISSUE TITLE
表格跨页的问题 表格分割的问题

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#408]
### version

0.9

### Steps to reproduce

这两个是一个表格 分割开了 而且第一页有时候会空大白 表格超出一页了 不知道是我版本的问题还是什么 大佬 帮忙解下疑惑吧 谢谢

### What is expected?

![Snipaste_2024-01-14_11-59-28](https://github.com/Hufe921/canvas-editor/assets/26762613/f9f30b44-b925-4a67-ba19-c5937e0621bd)
![Snipaste_2024-01-14_11-59-49](https://github.com/Hufe921/canvas-editor/assets/26762613/1a545054-f125-403f-b0cf-7e812ea98a61)

### What is actually happening?

这两个是一个表格 分割开了 而且第一页有时候会空大白 表格超出一页了 不知道是我版本的问题还是什么 大佬 帮忙解下疑惑吧 谢谢

### System Info

```shell
这两个是一个表格 分割开了 而且第一页有时候会空大白 表格超出一页了 不知道是我版本的问题还是什么 大佬 帮忙解下疑惑吧 谢谢
```

### Any additional comments?

这两个是一个表格 分割开了 而且第一页有时候会空大白 表格超出一页了 不知道是我版本的问题还是什么 大佬 帮忙解下疑惑吧 谢谢

**Comment by myNameWZH** [comment]
好像有同样的问题 我持续关注一下

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/41
