### ISSUE TITLE
无法动态的设置编辑器初始化的options的属性值？

### ISSUE THREAD

**Issue by flywin8** [Hufe921/canvas-editor#409]
### version

v0.9.62

### Steps to reproduce

目前有getOptions命令，但是没有setOptions的命令

### What is expected?

通过默认内容，动态计算水平和垂直居中，包括行高、行间距、文字大小，通过executeSetOptions命令执行修改默认参数属性

### What is actually happening?

无法实现动态修改编辑器初始化中的所有属性值

**Comment by flywin8** [comment]
目前采用的下面方式实现的动态修改
`const editorOption = await instance?.command.getOptions()
editorOption.defaultRowMargin = 2
instance?.command.executeForceUpdate()
`

**Comment by Hufe921** [comment]
可以采用这种方式
