### ISSUE TITLE
获取页面base64图片，是否支持按比例缩放

### ISSUE THREAD

**Issue by flywin8** [Hufe921/canvas-editor#413]
### version

^0.9.62

### Steps to reproduce

通过 await this.instance.command.getImage({ pixelRatio:0.5 }) 拿到的base64尺寸变了，内容变小了，但是整个容器出现了偏移，没有达到按比例缩放的效果
![image](https://github.com/Hufe921/canvas-editor/assets/13073744/48301a0a-d990-443e-89ab-67fa91143434)

### What is expected?

希望通过await this.instance.command.getImage({ pixelRatio:0.5 }) 获取到原来400*200的尺寸的0.5倍大小图片，200*100

### What is actually happening?

发生了内容偏移，图片并没有缩放

**Comment by Hufe921** [comment]
dataurl在浏览器直接访问会有长度限制，从而导致base64被截断，直接用image标签渲染试试
