### ISSUE TITLE
换行时行间距、行布局没有继承

### ISSUE THREAD

**Issue by 10jinzhi** [Hufe921/canvas-editor#415]
### version

0.9.53

### Steps to reproduce

![换行问题1](https://github.com/Hufe921/canvas-editor/assets/139574453/036c942d-fd32-4da5-8df7-25a9c463d3ea)
这是文字过长自动换行的效果：编辑器好像不知道它换行了，行距没有正常工作。
![换行问题](https://github.com/Hufe921/canvas-editor/assets/139574453/cb5856b8-39ad-4d9f-8f94-50e16c76c114)
在光标处输入回车：并没有换行，只是恢复了行距功能。

### What is expected?

正常工作

### What is actually happening?

没有正常工作

**Comment by Hufe921** [comment]
不换行是正常的，因为那里仅是纸张宽度不够的折行非换行。具体可以参考wps。腾讯文档登
