### ISSUE TITLE
更小的表格单元格最小高度

### ISSUE THREAD

**Issue by 10jinzhi** [Hufe921/canvas-editor#417]
### What problem does this feature solve?

有些表格如电话簿，内容只有一行，不需要太高的单元格，希望有更小的表格单元格最小高度。现在表格单元格最小高度是42。希望能更小，比如20或15。

### What does the proposed API look like?

现在表格单元格最小高度是42。希望能更小，比如20或15。

**Comment by Hufe921** [comment]
const options: IEditorOption = {
  tdPadding: [5, 5, 5, 5],
  defaultTrMinHeight: 26 // 最小行高：字体大小+tdPadding[0]+tdPadding[2]
}
![image](https://github.com/Hufe921/canvas-editor/assets/27001251/f6e43aad-af5b-4124-a04e-1d1dfec651ed)
