### ISSUE TITLE
在 Vue 2.x 中怎么使用组件

### ISSUE THREAD

**Issue by huangyunfei007** [Hufe921/canvas-editor#418]
### What problem does this feature solve?

vue2.x 修改为 ts 语法
![1705655713272](https://github.com/Hufe921/canvas-editor/assets/26923089/2c04519e-428f-48c4-b868-e98a21109eba)
无法创建绘画对象

### What does the proposed API look like?

提供一个vue的组件示例

**Comment by Hufe921** [comment]
这是ts告诉你，可能找不到这个dom(.canvas-editor)，让你加判断逻辑
建议好好学习一下ts。。。。
