### ISSUE TITLE
火狐浏览器下-双击页眉显示的问题

### ISSUE THREAD

**Issue by 18259669383** [Hufe921/canvas-editor#423]
### version

0.9.63

### Steps to reproduce

![图片](https://github.com/Hufe921/canvas-editor/assets/93261537/3bc7d93c-52f9-416d-841a-07338eb7cad1)

### What is expected?

暂无

### What is actually happening?

这个“双击页眉”显示在它不该显示的位置，这张图片的问题是在官网发现的，我并没有实际去测试，不知是否是demo的问题还是，这个功能确实有问题

**Comment by Hufe921** [comment]
无法复现，大概是怎么操作的

**Comment by 18259669383** [comment]
> 无法复现，大概是怎么操作的
使用火狐火狐浏览器，鼠标划入编辑器内就能看到
