### ISSUE TITLE
MAC Edge浏览器保持PDF无响应

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#424]
### version

最新

### Steps to reproduce

输出PDF点击保存无响应，必须把浏览器最小化或者缩放一下才行。

### What is expected?

点击后正常响应

### What is actually happening?

<img width="1269" alt="截屏2024-01-23 17 54 29" src="https://github.com/Hufe921/canvas-editor/assets/35056286/1205861b-d6fc-4764-bbd0-617e01c9218d">
<img width="660" alt="截屏2024-01-23 17 55 13" src="https://github.com/Hufe921/canvas-editor/assets/35056286/6afbd0d5-81fb-4031-a0b2-08ff62951dc6">

最小化或缩放一下才能恢复正常状态
MACOS Monterey 12.7.2
Microsoft Edge
版本 120.0.2210.144 (正式版本) (x86_64)

**Comment by Hufe921** [comment]
无法复现，到这一步就和编辑器无关了，就是纯浏览器逻辑，可以尝试升级浏览器试试
