### ISSUE TITLE
“更改图片”改为“替换图片”是不是更贴切

### ISSUE THREAD

**Issue by BOKE2014** [Hufe921/canvas-editor#432]
### What problem does this feature solve?

“更改图片”改为“替换图片”是不是更贴切？
该功能并不是对图片进行编辑，实际上就是打开一个新图片替换现有的图片。
<img width="1280" alt="截屏2024-01-30 17 01 50" src="https://github.com/Hufe921/canvas-editor/assets/35056286/ac322a23-b845-4e04-83a9-569aa5625204">

### What does the proposed API look like?

只是一个建议，谢谢！

**Comment by Hufe921** [comment]
可以自定义右键菜单及修改
