### ISSUE TITLE
关于executeSetControlValue设置为空字符串报错问题

### ISSUE THREAD

**Issue by sunjianfengHub** [Hufe921/canvas-editor#439]
### version

0.9.66

### Steps to reproduce

window.editor.command.executeSetControlValue({
      conceptId: '1',
      value: ''
    })

### What is expected?

当设置为空串应当展示placeholder

### What is actually happening?

执行clearValue中的const value = this.getValue() 这段，getValue报错，大概是在this.control.getRange()找节点的时候报错

**Comment by Hufe921** [comment]
没有复现，提供一下操作步骤及编辑器data

**Comment by sunjianfengHub** [comment]
如此复现：
![image](https://github.com/Hufe921/canvas-editor/assets/52647113/eebb5e53-efcb-4617-bcdd-7984070ae044)
很奇怪我在官网demo上尝试如此是没有这个问题的，我下载github上的v0.9.66本地是有这个问题的

**Comment by sunjianfengHub** [comment]
似乎可行
