### ISSUE TITLE
控件默认样式

### ISSUE THREAD

**Issue by biubiubiu-max** [Hufe921/canvas-editor#441]
### version

0.9.66

### Steps to reproduce

control: {
    type: ElementType.CONTROL,
    conceptId: 'jcjdname',
    underline: true,
    value: [],
    placeholder: '请输入名称',
    prefix: '{',
    postfix: '}',
    deletable: false
  }

### What is expected?

可设置样式、字体大小等样式

### What is actually happening?

ElementType.CONTROL节点模式下如何设置字体大小、样式、位置等，我设置似乎无效

**Comment by Hufe921** [comment]
重复: https://github.com/Hufe921/canvas-editor/issues/340

**Comment by sunjianfengHub** [comment]
这是需要手动设置吗？我想在初始化配置的时候就是‘初号’，`const data: IElement[] = [{
  type: ElementType.CONTROL,
  value: ' ',
  size: 29,
  rowFlex: RowFlex.CENTER,
  control: {
    type: ControlType.TEXT,
    conceptId: 'jcjdname',
    underline: true,
    value: null,
    placeholder: '请输入名称',
    prefix: ' ',
    postfix: ' ',
    deletable: false
  }
}, {
  value: '有限公司\n年度报告',
  size: 29,
  rowFlex: RowFlex.CENTER
}]`
因为这些配置项将会入库，并且这个控件初始化必须就是这么大居中
