### ISSUE TITLE
指令参数无效化

### ISSUE THREAD

**Issue by sunjianfengHub** [Hufe921/canvas-editor#445]
### version

0.9.66

### Steps to reproduce

这里有两份代码结果图，请问是否为异常结果，具体没有细看。
<img width="1419" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/52647113/519fbf94-8a83-49d6-befd-179429dedaa5">
![image](https://github.com/Hufe921/canvas-editor/assets/52647113/0b29a528-75bf-4469-879e-21a71acb072c)

### What is expected?

可能需要更新文档或者怎样

### What is actually happening?

本地调试发生了ts类型报错，看到此处的不一样

**Comment by Hufe921** [comment]
等待稍后版本更新
