### ISSUE TITLE
增加文档的修改记录

### ISSUE THREAD

**Issue by HiJerry** [Hufe921/canvas-editor#450]
### What problem does this feature solve?

能否增加修改记录，就是类似word，开启修订模式后，每次文件的修改记录都可以查看到。
<img width="1071" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/1432205/84782dd7-1ae4-4d38-90ab-68f6a4438281">

### What does the proposed API look like?

能否增加修改记录，就是类似word，开启修订模式后，每次文件的修改记录都可以查看到。
<img width="1071" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/1432205/84782dd7-1ae4-4d38-90ab-68f6a4438281">

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/312
