### ISSUE TITLE
后续是否有计划集成echarts，这样可以生成更多自动化的东西

### ISSUE THREAD

**Issue by zhangsai521314** [Hufe921/canvas-editor#454]
### What problem does this feature solve?

自动报表需求

### What does the proposed API look like?

自动报表需求

**Comment by Hufe921** [comment]
考虑以插件或自定义组件的形式集成，编辑器不会直接集成echarts的库

**Comment by Hufe921** [comment]
使用块元素进行集成，如以下代码
```
const srcdoc = `<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
  <style>
    * {
      margin: 0;
      padding: 0;
    }

    #chart-container {
      position: relative;
      height: 100vh;
      overflow: hidden;
    }
  </style>
</head>

<body>

  <div id="chart-container">
  </div>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/echarts/5.5.0/echarts.min.js"
    integrity="sha512-k37wQcV4v2h6jgYf5IUz1MoSKPpDs630XGSmCaCCOXxy2awgAWKHGZWr9nMyGgk3IOxA1NxdkN8r1JHgkUtMoQ=="
    crossorigin="anonymous" referrerpolicy="no-referrer"></script>
  <script>
    const chart = echarts.init(document.getElementById("chart-container"));

    chart.setOption({
      xAxis: {
        type: "category",
        data: ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"]
      },
      yAxis: {
        type: "value"
      },
      series: [{
        data: [120, 200, 150, 80, 70, 110, 130],
        type: "bar",
        showBackground: true,
        backgroundStyle: {
          color: "rgba(180, 180, 180, 0.2)"
        }
      }]
    });

    window.addEventListener('resize', chart.resize);
  </script>
</body>

</html>`
elementList.push({
  value: '',
  type: ElementType.BLOCK,
  height: 400,
  block: {
    type: BlockType.IFRAME,
    iframeBlock: {
      srcdoc
    }
  }
})
```

**Comment by zhangsai521314** [comment]
@Hufe921 此种实现不了想在文档两行文字中间加入图表啊

**Comment by Hufe921** [comment]
这样的效果？
<img width="753" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/27001251/1374312a-0697-429d-9121-7adf1dc9f767">

**Comment by zhangsai521314** [comment]
> 这样的效果？ <img alt="image" width="753" src="https://private-user-images.githubusercontent.com/27001251/323551588-1374312a-0697-429d-9121-7adf1dc9f767.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM0OTA0MjgsIm5iZiI6MTcxMzQ5MDEyOCwicGF0aCI6Ii8yNzAwMTI1MS8zMjM1NTE1ODgtMTM3NDMxMmEtMDY5Ny00MjlkLTkxMjEtN2FkZjFkYzlmNzY3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDE5VDAxMjg0OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlOTFmNTE4NDJlYzBjMjZmNjg1MTgyMDA1YWUzNTE1MDI4ZWE1ZWU4NjgwYWNkZmVmZThlNGY0MGZlMGMxMzImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jTYycGPw8P7O7wq4mBeaDZiIzRHoEpL5OQ003bJ_7nc">

对的，就是这种效果，不知道你这是贴图，还是echarts的图表对象？
