### ISSUE TITLE
Date 渲染存在缺陷

### ISSUE THREAD

**Issue by HerbertHe** [Hufe921/canvas-editor#457]
### version

0.9.97

### Steps to reproduce

默认 date 的渲染逻辑为每个字符进行一个个单字渲染，这会对 rtl 情况下的渲染造成困扰，改为类 LaTeX 或者字符串整体渲染会更好

### What is expected?

将 date 选择作为整体渲染，在渲染逻辑和坐标计算上，这种方式存在逻辑问题。

- 单字符坐标计算存在问题

`ctx.direction='rtl'` 情况下的文本的绘制会自动根据文字进行计算顺序，但其计算坐标仍为 LeftTop 点坐标，渲染逻辑为坐标轴对称，如果整体修改 positionList 的话会导致渲染错误

- Date 单字符绘制存在问题

如上所述，`2000-01-01 10:10:10` 作为一个整体在逻辑上无论是 rtl 还是 ltr 默认渲染为 `2000-01-01 10:10:10`。其原因在于作为一个整体，其中不存在 RTL 字符，所以不存在倒向渲染的问题。

一旦变成单字符绘制之后，rtl 渲染结果就变成了 `01:01:01 10-10-0002` ，这种方式是不正确的

- 单字符绘制逻辑存在问题

原则上来说，Date 是一个整体，如果进行类文本输入的话，会造成删除部分仍为 Date 类型的逻辑错误问题。直接使用 DatePicker 是个相对来说不错的主意，Date 数据应该是由 DatePicker 设置的单向不可变的。

### What is actually happening?

将 date 作为整体渲染，个人更倾向于 canvas 字符串的方式，这样可以直接把 RTL 渲染的逻辑扔给浏览器自行进行处理解决。

渲染成图片的方式不算是一个好的解决方案，虽然跟字符串的逻辑一样，在默认上就是强制 LTR 的

### Any additional comments?

从 ltr 改造成 rtl 确实存在很多的逻辑修复，还算是完成了可用情况下的大部分问题，为了尽早 PR，还是想可以有个联系方式进行前阶段讨论。

email to <hi@ibert.me>

**Comment by Hufe921** [comment]
date内部必须逐字绘制，因为会涉及到分页、换行、样式处理
其实整体思路上，我不赞同使用ctx. direction，原因如下：
1. 这是一个实验性属性
2. 本项目的渲染逻辑完全不依赖浏览器渲染逻辑（如坐标、分页等）
3. 会造成以后开发瓶颈，如某个组件或文字需要ltr

应该从编辑器底层逻辑方面入手，如Position（位置信息）、Draw（渲染）、Cursor（光标）等

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/451
