### ISSUE TITLE
换页导致表格拆分

### ISSUE THREAD

**Issue by GH-ID-CHC** [Hufe921/canvas-editor#464]
### version

0.9.68

### Steps to reproduce

在第一页创建一个表格，然后使用换行将表格进行移动至下一页。
发现表格会出现拆分的情况
![QQ截图20240314093508](https://github.com/Hufe921/canvas-editor/assets/64997017/021ceff4-ba15-4300-be04-680eb5667b81)

### What is expected?

表格完整

### What is actually happening?

表格经过换页会自动分裂

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/41
