### ISSUE TITLE
表格添加斜线保存以后再打开没有斜线了

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#466]
### version

0.9.54

### Steps to reproduce

<img width="1160" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/fba424ee-de9e-47fd-8141-64fed346dbe7">

### What is expected?

<img width="1160" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/1e29e2a9-ba76-4028-8207-8359bfe995db">

### What is actually happening?

<img width="1160" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/ba193aa1-50de-4a43-93f6-bf4c2ed7bf9b">

**Comment by myNameWZH** [comment]
![Uploading image.png…]()

**Comment by myNameWZH** [comment]
![Uploading image.png…]()

**Comment by Hufe921** [comment]
升级至最新版本解决
