### ISSUE TITLE
优化RTL时格式文本绘制方案

### ISSUE THREAD

**Issue by HerbertHe** [Hufe921/canvas-editor#468]
### version

0.9.68

### Steps to reproduce

现阶段在 TextParticle 中存在格式文本绘制因样式改变自动 complete 的问题，例如：

<img width="633" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/30955264/516887b7-df42-4395-b185-e0e298d16557">

实际上，会因为 hyperlink 作为格式文本，导致一行其实是分成三次来进行绘制的，开启 RTL 之后就会导致问题

<img width="613" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/30955264/ed281068-e20c-4ca3-9ee5-df747f84ed82">

这里的 hyperlink renderer 已经进行了修改，将 hyperlink 的绘制交给 textParticle 去完成，因为就文本而言，不应该因样式的改变而自动 complete，需要进行整段绘制，不改变 curX 的坐标，并且记录 text 的格式文本信息，便于之后的绘制。

### What is expected?

需要对 this.text 的格式进行重构，加入样式颜色等信息，~~取消因样式的修改而打断整段的绘制进行。~~ 通过计算前后文关系对字符进行重排，通过 rtl 定向开发进行重构。

需要对 `textParticle.record` 和 `textParticle._render` 方法进行重构。

### What is actually happening?

按行整段绘制不同的格式文本数据

**Comment by Hufe921** [comment]
不分段绘制无法 达到样式效果，比如你写一段html：
```
<span style="color:red;">123</span><span style="color:green;">456</span>
```
也是需要不同的标签或css去表达样式

**Comment by HerbertHe** [comment]
@Hufe921 已经想到解决方案了，把所有的 text 排成队列，然后在 rtl 的时候计算交换 x 坐标的位置来干预绘制，这个 issue 还是 reopen 吧，刚测了一下是完全可以同样实现的，这个问题不解决就不可能实现 rtl 了。

**Comment by HerbertHe** [comment]
```ts
if (this.textRenderQueue.length === 0) return
    const { direction } = this.options
    this.ctx.save()
    // TODO 针对 rtl 进行重排
    if (direction === 'rtl') {
      this._reQueue()
    }
    this.textRenderQueue.forEach(({ value, color, style, x, y }) => {
      this.ctx.font = style
      this.ctx.fillStyle = color || this.options.defaultColor
      this.ctx.fillText(value, x, y)
    })
    this.ctx.restore()
  }
```

```ts
export interface ITextRenderItem {
  value: string
  style: string
  color?: string
  x: number
  y: number
}
```

**Comment by HerbertHe** [comment]
record:

```ts
public record(
    ctx: CanvasRenderingContext2D,
    element: IRowElement,
    x: number,
    y: number
  ) {
    this.ctx = ctx
    const { value, style, color } = element
    // 主动完成的重设起始点
    // if (this.textRenderQueue.length === 0) {
    //   this._setCurXY(x, y)
    // }
    // 样式发生改变
    if (
      (this.curStyle && element.style !== this.curStyle) ||
      element.color !== this.curColor
    ) {
      this.textRenderQueue.push({
        value,
        style,
        color,
        x,
        y
      })
    } else {
      if (this.textRenderQueue.length !== 0) {
        const last = this.textRenderQueue.pop()!
        this.textRenderQueue.push({
          ...last,
          value: (last.value += element.value)
        })
      } else {
        this.textRenderQueue.push({
          value,
          style,
          color,
          x,
          y
        })
      }
    }
    this.curStyle = element.style
    this.curColor = element.color
  }
```

**Comment by HerbertHe** [comment]
@Hufe921 上面采用了两段绘制，差别在于不能在样式改变的时候就进行释放，还是在整行渲染的时候进行释放最为合适。在 rtl 的情况下，通过文本值来进行计算调整x的坐标，以此来达到交换位置的目的。因为 textParticle 已经是绘制流程的最底层了，所以绘制坐标的交换并不会影响整体的其他功能。

**Comment by HerbertHe** [comment]
@Hufe921 

https://github.com/HerbertHe/canvas-editor/commit/0da70699d69cdb89d5ba0bf9deed475a101687b1 在 rtl 下文本绘制进行了成功实现，重新计算 underline 等坐标

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/428
