### ISSUE TITLE
优化 RTL 时 underline、strikeout 等绘制方案

### ISSUE THREAD

**Issue by HerbertHe** [Hufe921/canvas-editor#469]
### version

0.9.98

### Steps to reproduce

#468 在文本绘制方案的 issue 中，由于需要对每行的元素绘制队列进行二次排序，与单元素绘制 underline、strikeout 等产生冲突。

文本绘制方案改为了 **按行绘制**，而不是 **按元素绘制**

因为 underline 等样式依赖 elementPosition，因此需要在文本渲染队列重排时，在整行结束的时机触发，对 position 坐标进行重新赋值。因此 underline、strikeout 的绘制也应该在文本重排之后进行实现，需要对其 record 和 render 方法进行重构。

### What is expected?

整体绘制方案改为 **按行绘制**，而非 **按元素绘制**，否则在单行文本渲染时，会导致不正确的 underline 等坐标的记录，这部分需要进行重构。

### What is actually happening?

按行计算出正确的样式坐标，然后在行结束对整行进行绘制

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/428
