### ISSUE TITLE
表格复制粘贴最后一个单元格丢失

### ISSUE THREAD

**Issue by zhaoxuanHome** [Hufe921/canvas-editor#470]
### version

0.98

### Link to minimal reproduction

https://hufe.club/canvas-editor

### Steps to reproduce

1、下载 github  main主干代码，运行项目(0.98版本)。
2、前置条件：路由地址：192.168.2.75（此IP是本机地址）
    1）插入表格
选中菜单栏任意数目表格，点击插入。
    2）复制表格
在表格右侧双击选中表格，复制粘贴。表格缺失最后一个格子。

3、前置条件：路由地址：localhost/127.0.0.1
    1）插入表格（操作方式同上）
    2）复制表格（操作步骤同上）
表格正常没有异常现象。

![动画](https://github.com/Hufe921/canvas-editor/assets/36555730/24b3d3e3-89bd-42d3-806f-6822a7c068a4)

### What is expected?

无论是本地ip地址访问项目还是localhost/127.0.0.1访问都能正常复制粘贴表格。不丢失最后一个单元格。

### What is actually happening?

使用ip地址本地运行或者线上部署，复制粘贴表格都会缺失最后一个单元格。
使用localhost/127.0.0.1能够正常使用。
猜测：
**复制操作**时单元格已经丢失！

**Comment by Hufe921** [comment]
因为http不支持粘贴板ClipboardItem会降级使用document.execCommand('copy')进行html复制，但是这个api现在好像存在问题，需要再研究一下
