### ISSUE TITLE
优化 RTL 时，range 范围的获取方案

### ISSUE THREAD

**Issue by HerbertHe** [Hufe921/canvas-editor#472]
### version

0.9.69

### Steps to reproduce

#469 相关

<img width="637" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/30955264/0330e21c-ad4e-45eb-b109-89880b1709be">

对已完成的渲染效果来说，underline 和 strikeout 是正确绘制的，其差别在于绘制的实际坐标在重排之后进行了重新计算。

可参考下面的实现：

```ts
this.textRenderQueue = result.map((r, idx) => {
      const x = startX - offsetX
      // TODO 赋值 rtlPositions, 方便进行后续取值
      const res = {
        ...r,
        positions: r.positions.map(p => ({
          ...p,
          rtlCoordinate: {
            leftTop: [x, p.coordinate.leftTop[1]],
            leftBottom: [x, p.coordinate.leftBottom[1]],
            rightTop: [x + r.width[idx], p.coordinate.rightTop[1]],
            rightBottom: [x + r.width[idx], p.coordinate.rightBottom[1]]
          }
        })),
        x
      } as ITextRenderItem

      offsetX += r.width.reduce((prev, curr) => {
        return prev + curr
      })
      return res
    })
```

在完成重排之后，会根据 position 的指针修改新增的 `rtlCoordinate` 属性。直接修改之前的 `coordinate` 属性，会导致原始位置丢失，触发重新渲染的时候坐标错误，因此已经被证实不可行了。

但这同时也带来了新的问题，range manager 只设置索引的动作并不完全正确，因为文本重排导致了绘制坐标发生了整体的改变。因此 range 的确认靠索引来实现是存在不合理的，尤其是 rtl 和 ltr 混排的时候，存在一左一右的问题，无法确定实际的选区范围。

### What is expected?

目前想到的解决方案是，通过鼠标 y 来计算出实际的行号，获取 rowElements 之后，再根据重排之后的 x 坐标和鼠标偏移坐标，确定实际的选区范围。选区需要记录的是 position 指针，而非索引

### What is actually happening?

在 RTL 新的文本绘制方案下，错误的选区范围会导致 range 依赖的富文本格式绘制错误，相应 command 无法进行正常工作 #468

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/428
