### ISSUE TITLE
有的电脑会出现字体看不到的问题 大概是什么原因 大佬知道吗 

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#476]
### version

0.9.68

### Steps to reproduce

<img width="1048" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/cf2cbdbb-6f2b-4e77-9b85-155bc3a4e890">

### What is expected?

<img width="1048" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/30a320de-2462-47ff-b3cf-c7a1803e7011">

### What is actually happening?

<img width="1048" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/26762613/62698b21-c3bb-491d-a13d-3a37ac7af184">

**Comment by Hufe921** [comment]
先提供一下编辑器数据，及配置看看有没有bug，再提供一下系统信息：系统版本、浏览器版本等

可能相似问题：https://github.com/Hufe921/canvas-editor/issues/373
