### ISSUE TITLE
优化 RTL 时，控件文本渲染的逻辑

### ISSUE THREAD

**Issue by HerbertHe** [Hufe921/canvas-editor#477]
### version

0.9.69

### Steps to reproduce

#468 中提到进行二次排序，批量计算实际坐标的问题，但在控件的文本分割上存在问题。在默认 LTR 的绘制实现上，通过 textSpacing 的时机和 checkbox 渲染前时机进行触发，二次混排之后采用按行渲染的方式进行触发。存在需要对控件内文本进行特殊化 id 计算的方式以解决 checkbox 等不同组件的绘制，但控件内不同组件及文本绘制应该做实质区分。

<img width="1378" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/30955264/e022adab-c0a9-4f18-ac5f-a22808fdbf7d">

针对于富文本样式渲染的问题，已经实现格式文本下的正常绘制渲染：

<img width="848" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/30955264/0eab6b02-4ae4-42db-98ff-1db2f2853b0d">

控件的渲染问题是个独立的问题。其他依赖 range 进行事件绘制，在 #472 问题中进行重新实现 

### What is expected?

将控件内不同的元素组合进行重新标记，以实现文本的正确分割

### What is actually happening?

文本分割粘连

**Comment by HerbertHe** [comment]
计划通过 `type='control'` 和 `valueSets` 进行试验性实现

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/428
