### ISSUE TITLE
导出html表格边框没有隐藏

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#480]
### version

0.9.69

### Steps to reproduce

<img width="630" alt="1" src="https://github.com/Hufe921/canvas-editor/assets/53844499/38e6a907-e889-49f3-9cdc-89e82bbced75">

### What is expected?

<img width="548" alt="2" src="https://github.com/Hufe921/canvas-editor/assets/53844499/354c7a71-2c8c-48e8-917e-8e697c9b9d74">

### What is actually happening?

<img width="548" alt="2" src="https://github.com/Hufe921/canvas-editor/assets/53844499/008777c0-5132-4d47-99f6-0e8fe67ff072">
导出为html表格内边距没有了，表格边框没有隐藏，

**Comment by douglasmatheus** [comment]
Hello, I sent a PR that adjusts this and other styles in the exported file. But I don't think @Hufe921  even analyzed it.

If you want to check the PR to see how it was done, follow the link

https://github.com/Hufe921/canvas-editor-plugin/pull/9

**Comment by Hufe921** [comment]
由于编辑器数据结构与HTML并不一致，如果想把编辑器内容完全用HTML还原不太现实，如果有这方面更精细化的需求，可以通过getValue获取编辑器数据后再转换成HTML（编辑器内部也是这样实现：src/editor/utils/element.ts：createDomFromElementList）
