### ISSUE TITLE
导出doc文件表格一页展示不全，不会在下一页展示问题

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#481]
### version

0.9.69

### Steps to reproduce

<img width="530" alt="1" src="https://github.com/Hufe921/canvas-editor/assets/53844499/cd19e235-0764-468e-911f-a332c21f8107">

### What is expected?

<img width="715" alt="2" src="https://github.com/Hufe921/canvas-editor/assets/53844499/b3468ba8-b122-4ed5-9899-69122d1db16a">

### What is actually happening?

doc复制直接粘贴到编辑器里面表格一页展示不全不会换页展示

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/41
