### ISSUE TITLE
在代码中设置图片浮于文字上方或衬于文字下方会导致整个页面加载后内容不显示

### ISSUE THREAD

**Issue by wzy719424** [Hufe921/canvas-editor#484]
### version

0.9.69

### Steps to reproduce

在页眉和内容区里，通过代码设置图片的imgDisplay属性为FLOAT_BOTTOM或FLOAT_TOP时会导致页面加载后内容不显示。
![image](https://github.com/Hufe921/canvas-editor/assets/30775497/26a1d92b-96f5-4284-9648-c19264a7e31e)
![image](https://github.com/Hufe921/canvas-editor/assets/30775497/6b845c77-a9a0-4ebc-8131-62bf684a2090)

### What is expected?

代码预先设置好的文字图片等内容，在页面加载后都能正常显示出来

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/30775497/61504ed4-1e41-4e3f-b441-7c5a161d6443)

**Comment by Hufe921** [comment]
必须有位置悬浮坐标，如：
```
imgDisplay: ImageDisplay.FLOAT_TOP,
  imgFloatPosition: {
    x: 100,
    y: 100
  },
  type: ElementType.IMAGE
```
