### ISSUE TITLE
大佬您好，我看描述没提到过交流群，能否建一个交流群大家一起交流，反馈问题更方便。

### ISSUE THREAD

**Issue by 18779758522** [Hufe921/canvas-editor#485]
### What problem does this feature solve?

大佬您好，我看描述没提到过交流群，能否建一个交流群大家一起交流，反馈问题更方便。

### What does the proposed API look like?

无

**Comment by Hufe921** [comment]
本人非全职开发此项目，只有下班后及周末休息时间才能开发，暂时没有足够精力再搞一个微信群回答问题。
直接提issues即可
