### ISSUE TITLE
打印pdf排版问题

### ISSUE THREAD

**Issue by ProLiok** [Hufe921/canvas-editor#486]
### version

0.0.69

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

打印pdf排版问题

### What is expected?

单页内容占一页

### What is actually happening?

打印pdf比例错误，页脚页码打印到当前页的第二页页头导致第二页整个空白只有第一的页脚页码信息
![2024-03-21_09-33-00](https://github.com/Hufe921/canvas-editor/assets/95992064/566ffe92-a5de-441b-b902-99a3c3ab525e)

**Comment by Hufe921** [comment]
什么浏览器？尝试切换一下页边距试试

**Comment by ProLiok** [comment]
国产linux系统，龙芯、奇安信可信、360浏览器都这样，调整了页边距也没效果
![2024-03-21_18-34-14](https://github.com/Hufe921/canvas-editor/assets/95992064/2e2ef9a1-f86c-4efc-9830-be62e988f5b8)

**Comment by Hufe921** [comment]
用主流浏览器 chrome 、edge试试，你纸张看起来不是A4而是Letter

**Comment by ProLiok** [comment]
此国产linux系统edge没有相应架构版本、chrome版本为83也会出现上诉问题
