### ISSUE TITLE
设置编辑器 HTML 数据  “字体”  不生效

### ISSUE THREAD

**Issue by lemonFishWc** [Hufe921/canvas-editor#488]
### version

1

### Steps to reproduce

1.将富文本数据的文字设置为“宋体”字体后，使用getHTML方法获取数据。
2.然后通过executeSetHTML方法将获取到的HTML数据重新设置回去，您会发现“字体”样式不生效。

### What is expected?

可以将HTML原有的font-family字体属性设置上去

### What is actually happening?

executeSetHTML 未兼容html 字体

**Comment by Hufe921** [comment]
使用getValue和setValue进行编辑数据的获取及还原。

html字体涉及到字体族的问题，编辑器无法知道具体有效的是哪个，因此默认使用的是当前文档上下文的字体
