### ISSUE TITLE
提个建议：当页很多时，能复用之前创建的Canvas吗？减少创建的Canvas数量，提升性能。

### ISSUE THREAD

**Issue by yswang0927** [Hufe921/canvas-editor#489]
### What problem does this feature solve?

目前看到每页都会创建一个Canvas，几十页就会创建几十个Canvas，是不是可以采取复用已创建的Canvas方式来减少Canvas数量，提升性能？因为当你看第三页时，前面的第1页Canvas已经不在可视范围内，可以用于渲染第4页的内容。

**Comment by Hufe921** [comment]
现在就是只渲染可见页，canvas只是创建并占位，实际内容并没有渲染
