### ISSUE TITLE
指令executeSetControlValue有关样式处理

### ISSUE THREAD

**Issue by sunjianfengHub** [Hufe921/canvas-editor#490]
### version

0.9.70

### Steps to reproduce

是这样的，首先我有一个CONTROL
`{
    value: '巴拉巴拉',
    size: 21
  },
  {
    type: ElementType.CONTROL,
    value: '',
    size: 21,
    control: {
      type: ControlType.TEXT,
      conceptId: 'test',
      underline: true,
      value: null,
      placeholder: '请输入',
      deletable: false,
      minWidth: 300
    }
  },`
  
然后我执行 ` editor.command.executeSetControlValue({conceptId: 'test',value: 'hahhahahaaha'})`，
设置的‘hahhahahaaha’值的样式是不统一的，
       if (type === ControlType.TEXT) {
          const formatValue: IElement[] = [{
            value,
          }]
        // [{value: 'hahahaha'}]
          formatElementList(formatValue, {
            isHandleFirstElement: false,
            editorOptions: this.options
          })
      //.....
}

猜测这里的节点没有复制左右节点样式，

### What is expected?

我期望我使用指令设置值的样式与control的style一致

### What is actually happening?

由于节点设置时候是 `[{value }]` 这样的默认空节点，再一个模版的control样式是不固定的，因此手动写上去一个样式也不是很能解决这种问题

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/340

**Comment by sunjianfengHub** [comment]
@Hufe921 非也，不是340中提到的问题，不是默认样式的丢失，例如：我的模板来自数据库，是一段json，正如我前面提到的，这些诸多控件中的值也来自请求的来，那么初始化的时候我就可能平凡调用executeSetControlValue赋值，但样式全部都是默认的配置项。但，假设我在配置中存在29px的control，18px的control等，在调用指令时都是默认16px，这样就不对了

**Comment by sunjianfengHub** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/52647113/e62629ed-09be-4f6e-a69a-64c7db34f8d0)

**Comment by sunjianfengHub** [comment]
> 重复：#340

@Hufe921也非，不是340中提到的问题，不是默认样式的丢失，例如：我的模板来自数据库，是一段json，正如我前面提到的，这些爆炸按钮中的值也来自请求的来，那么初始化的时候我就可能一次性多次调用executeSetControlValue赋不同地方的值，但样式全部都是默认的配置项。但是，假设我在配置中存在29px的control，18px的control等，在调用指令时都是默认16px，这样就对了

![image](https://github.com/Hufe921/canvas-editor/assets/52647113/ae764bb3-e88f-4511-b99c-e51dbc976b0f)
