### ISSUE TITLE
可以创建一个微信群吗

### ISSUE THREAD

**Issue by 315574925** [Hufe921/canvas-editor#492]
### What problem does this feature solve?

方便社区交流

### What does the proposed API look like?

可以创建一个微信群吗

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/485

**Comment by myNameWZH** [comment]
可以建个群 把使用这个编辑器的集合起来 有什么问题可以大家一起讨论 作者忙了可以不出现

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/discussions
