### ISSUE TITLE
表格高度空隙调整

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#493]
### What problem does this feature solve?

目前利用表格进行排版的时候，里面的文字空隙太大 
 
![image](https://github.com/Hufe921/canvas-editor/assets/27660604/cc4c5b7a-a15d-40d1-bb18-ae5a46484d7d)

### What does the proposed API look like?

能否调整现有表格高度类似于word正好包裹文字
![image](https://github.com/Hufe921/canvas-editor/assets/27660604/300fd73d-3035-443f-992d-3c757ae001cd)

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/417
