### ISSUE TITLE
希望新增添加部分功能API

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#495]
### What problem does this feature solve?

目前页眉页脚无法替换，以及表格行列无法复制

### What does the proposed API look like?

希望新增如下API：
1. 替换页眉
2. 替换页脚
3. 复制一行表格
4. 复制一列表格

**Comment by zhuyihe** [comment]
另外：希望未来能增加radio控件

**Comment by Hufe921** [comment]
替换页眉页脚：https://hufe.club/canvas-editor-docs/guide/command-execute.html#executesetvalue
复制表格：拖蓝选择即可复制
radio有人已经贡献pr，等待review修改
