### ISSUE TITLE
打印内容未居中对齐

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#496]
### version

0.9.71

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/ad74bb07-6254-431d-b855-d1da6982aa6e)

### What is expected?

打印内容需居中对齐

### What is actually happening?

打印内容未居中对齐

**Comment by Hufe921** [comment]
更多设置，看看选的纸张

**Comment by zhuyihe** [comment]
我的问题 默认缩放90%
