### ISSUE TITLE
希望将页眉页脚编辑的功能提取出来可以形成单独的页眉页脚编辑器

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#497]
### What problem does this feature solve?

解决能够单独编辑页眉页脚问题

### What does the proposed API look like?

形成单独的模块引入

**Comment by Hufe921** [comment]
什么使用场景

**Comment by zhuyihe** [comment]
不同的院区页眉不一样可以编辑页眉页脚保存 到不同的院区就直接加载编辑好的页眉页脚就行

**Comment by Hufe921** [comment]
页眉、页脚、正文区域数据都是通用的。
直接编辑后获取对应的数据，在通过setValue设置对应的数据即可

**Comment by smallcutefish** [comment]
如何设置页眉页脚为图片？
