### ISSUE TITLE
删除线不垂直居中

### ISSUE THREAD

**Issue by penn609** [Hufe921/canvas-editor#498]
### What problem does this feature solve?

删除线不垂直居中，偏上点，期望修复。

### What does the proposed API look like?

删除线不垂直居中，偏上点，期望修复。

**Comment by penn609** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/157893959/8e066c59-0da6-40c6-89a3-16beff10e401)

**Comment by penn609** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/157893959/dc0d1873-a70f-4b09-b707-17015c1a1bac)

**Comment by Hufe921** [comment]
修改点：
1. 复制粘贴html增加删除线格式
2. 仅文本类元素允许添加删除线
3. 页面放大缩小时删除线宽度设置
4. 以“日”字作为基线文本，测量删除线在行内居中位置
5. 上下标文字删除线位置特殊处理
