### ISSUE TITLE
光标无法定位到分割线两周，导致分割线无法删除

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#500]
### version

0.9.71

### Steps to reproduce

1.页眉添加分割线
2.删除分割线下面的空行，并且移除光标
3.光标无法定位到分割线处

### What is expected?

光标能够定位到分割线两周，能够执行删除动作

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/8e575832-d802-4b90-b13c-0cf0a4b08db1)

**Comment by Hufe921** [comment]
左右键切换或执行delete向后删除
