### ISSUE TITLE
vue3框架里npm后直接使用

### ISSUE THREAD

**Issue by supan0228** [Hufe921/canvas-editor#501]
### What problem does this feature solve?

在vue3项目框架里直接使用，想问下大神支持vue开箱即用的什么时候会出来呐，

### What does the proposed API look like?

暂无，自己写了点都被推翻了

**Comment by Hufe921** [comment]
为啥被推翻，遇到了什么难点

**Comment by supan0228** [comment]
我是直接npm之后去使用，用的时候样式还有功能头都直接不显示，调整了底层也没显示出来，最后发现需要去copy你的ts代码去实现功能，就想着如果可以直接npm后，可以通过全局或者局部导入实现所有的功能了。我今天再试下别的方法

**Comment by lgdzz** [comment]
vue3中具体怎么使用有步骤吗？现在主体出来了，但是工具栏出不来？

**Comment by Hufe921** [comment]
npm包只提供编辑器核心功能，可以当成一个无头编辑器（类似：Slatejs ProseMirror），需要参考项目文档或项目demo自行开发一个符合自己业务需求的编辑器。附文档：
https://hufe.club/canvas-editor-docs/guide/start.html

官方完全开箱即用的版本，暂时没有

**Comment by supan0228** [comment]
好的 我再看下这个 谢谢大神！

**Comment by pinghe** [comment]
demo 的源码库可以在哪里找到？
