### ISSUE TITLE
能不能提供一个失去焦点的监听事件

### ISSUE THREAD

**Issue by Arc-zlz** [Hufe921/canvas-editor#504]
### What problem does this feature solve?

提这个需求是因为保存的问题  instance.eventBus.on('saved', (payload: IEditorResult) => void)  需要用户进行保存的操作
newEdit.value.eventBus.on('contentChange', async () => {}) 自动保存 只能通过这个监听事件  但这个过于频繁  不利于后端的优化
期望作者大大加一个失去焦点的监听事件  如果进行当前插件的其他操作可以保存 谢谢 

### What does the proposed API look like?

instance.eventBus.on('blur', (payload: IEditorResult) => void)

**Comment by Hufe921** [comment]
可以监听rangeStyleChange，type===null的时候光标不在编辑器区域

**Comment by Arc-zlz** [comment]
谢谢
