### ISSUE TITLE
表格合并单元格之后无法跨页

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#505]
### version

0.9.72

### Steps to reproduce

1.合并单元格
2.回车到下一页

### What is expected?

表格合并单元格之后无法跨页

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/46e5e7df-ef93-4a79-a483-37956a535614)

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/41
