### ISSUE TITLE
能否提供保存为word功能，我们的需求是在页面上进行编辑后保存导出为可审批的文件

### ISSUE THREAD

**Issue by taotie111** [Hufe921/canvas-editor#506]
### What problem does this feature solve?

能否提供保存为word功能，我们的需求是在页面上进行编辑后保存导出为可审批的文件

### What does the proposed API look like?

一个保存按钮 保存为word或pdf文件

**Comment by Hufe921** [comment]
有导入导出插件：https://github.com/Hufe921/canvas-editor-plugin

**Comment by haizzh** [comment]
这个插件能够实现导入导出，但是格式不太兼容word格式
