### ISSUE TITLE
el-tab 打开多个编辑器的时候 instance.value.listener 会监听多个 每次监听都会监听所有打开的编辑器 有什么解决办法吗 大佬

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#509]
### version

0.9.60

### Steps to reproduce

想做个剪切板的功能 ctrl+x的时候 instance.value.command.getRangeText()就为空了 想着通过监控那一块 去确定打开的当前编辑器的选取 然后发现会多次监听 还有就是右键菜单也会因为打开多个 注册的菜单会多出来很多个 不知道你们有人遇到这样的问题部

### What is expected?

el-tab 打开多个编辑器的时候 instance.value.listener 会监听多个 每次监听都会监听所有打开的编辑器 有什么解决办法吗 大佬

### What is actually happening?

el-tab 打开多个编辑器的时候 instance.value.listener 会监听多个 每次监听都会监听所有打开的编辑器 有什么解决办法吗 大佬

### System Info

```shell
想做个剪切板的功能 ctrl+x的时候 instance.value.command.getRangeText()就为空了 想着通过监控那一块 去确定打开的当前编辑器的选取 然后发现会多次监听 还有就是右键菜单也会因为打开多个 注册的菜单会多出来很多个 不知道你们有人遇到这样的问题部
```

### Any additional comments?

想做个剪切板的功能 ctrl+x的时候 instance.value.command.getRangeText()就为空了 想着通过监控那一块 去确定打开的当前编辑器的选取 然后发现会多次监听 还有就是右键菜单也会因为打开多个 注册的菜单会多出来很多个 不知道你们有人遇到这样的问题部

**Comment by Hufe921** [comment]
先升级一下最新版本0.9.72

**Comment by myNameWZH** [comment]
最近版针对这个监控做优化了嘛 现在主要是我这边也改了一些代码 不好去直接替换掉

**Comment by Hufe921** [comment]
版本跨度较大，代码更改很多，不方便看问题。
可以用最新版本写个小demo看看能不能复现问题。
