### ISSUE TITLE
vue、react 等框架开箱即用版

### ISSUE THREAD

**Issue by haiyunxiong** [Hufe921/canvas-editor#512]
### What problem does this feature solve?

大佬，vue、react 等框架开箱即用版这个打算在什么时候做？

### What does the proposed API look like?

vue、react 等框架开箱即用版

**Comment by Hufe921** [comment]
本人利用业余时间开发此项目，非全职开发，无法回复具体时间。

参考demo使用官方npm包开发一个符合自身业务场景的编辑器，技术上没有难点。可以尝试自己写一下
