### ISSUE TITLE
checkbox未随字体变化而变化

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#515]
### version

0.9.73

### Steps to reproduce

1.添加复选框
2.选中复选框，更改字体大小

### What is expected?

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/f2be9921-4c70-4018-b03b-5f7d84d2cc30)
![Uploading image.png…]()

### What is actually happening?

复选框跟随字体变化

**Comment by Hufe921** [comment]
复选框和字体大小无关

**Comment by zhuyihe** [comment]
有没有什么办法使控件大小跟随字体变化，字体小的时候复选框比较大有影响
