### ISSUE TITLE
能否新增在表单模式下 指定某些元素是否可编辑吗？控件之外的元素

### ISSUE THREAD

**Issue by Tiny-Dong** [Hufe921/canvas-editor#519]
### What problem does this feature solve?

能否新增在表单模式下 指定某些元素是否可编辑吗？控件之外的元素

### What does the proposed API look like?

能否新增在表单模式下 指定某些元素是否可编辑吗？控件之外的元素

**Comment by Hufe921** [comment]
使用场景说明一下

**Comment by Tiny-Dong** [comment]
在编辑模式下设计一个整张的模板，里边填充好预设的标签和占位字段，形如： 姓名 {name}，简介 {description};
![image](https://github.com/Hufe921/canvas-editor/assets/41326730/972d466d-c0d9-4975-9d30-08b709ea3017)

当给到用户端使用时 name从系统填充不需要编辑，形如description在的table td 可支持编辑 且不让用户看到 {description}的字样.

**Comment by Hufe921** [comment]
通过disabled=true属性可以设置控件只读

**Comment by savelifeme** [comment]
@Tiny-Dong 这个问题拟解决了吗？
