### ISSUE TITLE
设置字体无效

### ISSUE THREAD

**Issue by zhangqw2** [Hufe921/canvas-editor#524]
### version

0.9.74

### Steps to reproduce

无

### What is expected?

  const fontDom = document.querySelector('.menu-item__font')
    const fontSelectDom = fontDom.querySelector('.select')
    const fontOptionDom = fontDom.querySelector('.options')
    fontDom.onclick = function () {
      console.log('font')
      fontOptionDom.classList.toggle('visible')
    }
    fontOptionDom.onclick = function (evt) {
      const li = evt.target
      instance.command.executeFont(li.dataset.family)
    }

### What is actually happening?

没有效果
<img width="206" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/43216619/d4615fde-6381-4d44-b331-0dc6e92db74f">

**Comment by Hufe921** [comment]
1. 确认有没有拖蓝选区对应文字，再去设置字体
2. 确认电脑支持该字体

**Comment by zhangqw2** [comment]
官网的demo也不行
