### ISSUE TITLE
表单模式日期不能选择

### ISSUE THREAD

**Issue by ColinZeb** [Hufe921/canvas-editor#532]
### What problem does this feature solve?

版本 0.9.75
有办法能让表单模式日期可选择么？
我尝试修改日期对象的属性增加一个conceptId也没成功

### What does the proposed API look like?

希望能提供一个让Element对象可编辑的命令
或者可以给Eelement自定义属性值的命令，这样可以自己手动实现一些效果，例如单击事件弹框

**Comment by Hufe921** [comment]
表单模式下，仅控件元素可以编辑

**Comment by ColinZeb** [comment]
@Hufe921 那IElement能否自定义属性呢
