### ISSUE TITLE
多行选中时，每行的背景色中间能否留下空白的颜色？如图

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#533]
### What problem does this feature solve?

![4a1413d3f0c1515dea6cd3654fcbbcc](https://github.com/Hufe921/canvas-editor/assets/80032740/844680c6-f9ef-46c9-9557-c864ff9117a9)
下面是word的显示
![1714574975002](https://github.com/Hufe921/canvas-editor/assets/80032740/5b10653e-0457-43cc-962c-ad3a395f303d)

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
参考谷歌等在线文档实现

**Comment by bettersoft123** [comment]
您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。
