### ISSUE TITLE
有几个小问题，请指教。谢谢

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#534]
### What problem does this feature solve?

1：能否增加分散对齐的功能？这样排版的时候就不要中间打空格来完成对齐。
2：表格的行高最小能支持多少？感觉 defaultTrMinHeight这个参数再往小了改不起效果。
3：啥时候能提供vue即插即用的功能啊？
4：demo上，有主诉，现病史什么的，如何获取主诉等章节后面的具体内容哩？如果把主诉什么的定义成文本，但你这个文本中，又不能嵌套文本和列表，有什么办法吗？谢谢

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
1. 分散对齐（新功能请求待开发）：https://github.com/Hufe921/canvas-editor/issues/535
2. 最小行高（已关闭）：https://github.com/Hufe921/canvas-editor/issues/417
3. vue版（已关闭）：https://github.com/Hufe921/canvas-editor/issues/512
4. 根据标题获取内容（新功能请求待开发）：https://github.com/Hufe921/canvas-editor/issues/536
