### ISSUE TITLE
根据标题获取对应内容

### ISSUE THREAD

**Issue by Hufe921** [Hufe921/canvas-editor#536]
### What problem does this feature solve?

根据标题上的概念获取对应标题下的内容

### What does the proposed API look like?

getValueByTitle

**Comment by bettersoft123** [comment]
getValueByTitle这个方法还没增加吗？没看到啊

**Comment by Hufe921** [comment]
控件属性：
```
[
  {
    value: '',
    title: {
      conceptId: `123` // 定义标题概念
    },
    type: ElementType.TITLE,
    level: TitleLevel.FIRST,
    valueList: [
      {
        value: '主诉：',
        size: 18
      }
    ]
  },
  {
    value: "发热三天，咳嗽五天。"
  }
]
```

获取方法：
```
const data =  instance.command.getTitleValue({ conceptId: '123' })
[
    {
        "conceptId": "10",
        "value": "发热三天，咳嗽五天。",
        "elementList": [
            {
                "value": "发热三天，咳嗽五天。",
                "size": 16
            }
        ],
        "zone": "main"
    }
]
```

**Comment by bettersoft123** [comment]
/**插入标题 */
function insertEditorTitle(){
  instance.command.executeInsertElementList
  ([
  {
    value: '',
    title: {
      conceptId: '123' // 定义标题概念
    },
    type: ElementType.TITLE,
    level: TitleLevel.FIRST,
    valueList: [
      {
        value: '主诉：',
        size: 18
      }
    ]
  },
  {
    value: "发热三天，咳嗽五天。"
  }
])
我用这种方法感觉不行啊。
实际得到的数据集是这样的如下：
main:[
{
value:"主诉："
size:18
bold:true
}
{
value:"发热三天，咳嗽五天。
"
}
]
也没有conceptId，这个到底怎么使用哩？谢谢
我是想通过主诉这个标题，获取到主诉后面的所有内容。
