### ISSUE TITLE
表格分页后能否把分页后的第二页表格带上原来的

### ISSUE THREAD

**Issue by zp190265950** [Hufe921/canvas-editor#539]
### What problem does this feature solve?

在一定场景下，会用到表格分页第二页没有表头问题

### What does the proposed API look like?

可以提供一个配置，分页是否携带表头

**Comment by Hufe921** [comment]
有思路可以发起pr

**Comment by chengshaowei** [comment]
> 有思路可以发起pr

在第一页设置固定表头，其他页可以加载第一页的表头

**Comment by zp190265950** [comment]
> > 有想法可以发起pr
> 
> 在第一页设置固定表头，其他页面可以加载第一页的表头

我添加的一个pr，逻辑是默认把表格的第一行作为表头，携带到拆分后的第二个表格头部，你这种设置某一行作为表头，在拆分后的摆个携带吗？
