### ISSUE TITLE
浏览器扩展“ColorPick Eyedropper”，会影响字体颜色按钮，和高亮按钮

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#544]
### version

0.9.76

### Steps to reproduce

<img width="779" alt="PixPin_2024-05-08_11-46-52" src="https://github.com/Hufe921/canvas-editor/assets/53844499/7f7217e4-d605-4944-9d5c-b4630355d6ea">

### What is expected?

<img width="779" alt="PixPin_2024-05-08_11-46-52" src="https://github.com/Hufe921/canvas-editor/assets/53844499/39bdeb83-d3f7-4699-ac24-4087bed57304">

### What is actually happening?

<img width="779" alt="PixPin_2024-05-08_11-46-52" src="https://github.com/Hufe921/canvas-editor/assets/53844499/e669ebf5-1e08-4da3-a9cb-52153cdfa2eb">

**Comment by wen-shiqiang** [comment]
![Uploading PixPin_2024-05-08_13-36-57.png…]()

**Comment by wen-shiqiang** [comment]
<img width="723" alt="PixPin_2024-05-08_13-36-57" src="https://github.com/Hufe921/canvas-editor/assets/53844499/a2b60df5-b592-42f8-a791-65782bb0a538">

**Comment by Hufe921** [comment]
此插件注入的图标
![image](https://github.com/Hufe921/canvas-editor/assets/27001251/b3018419-6593-4f00-a739-86c9fed4d21c)
