### ISSUE TITLE
在微服务引用中，由于import xxx from './xxx?worker&inline'在生产环境中产生的同源策略问题

### ISSUE THREAD

**Issue by ProLiok** [Hufe921/canvas-editor#547]
### version

0.9.71

### Steps to reproduce

由于import xxx from './xxx?worker&inline'在生产环境中产生的同源策略问题导致编辑器无法进行任何操作
![2024-05-08_15-14-36](https://github.com/Hufe921/canvas-editor/assets/95992064/faa697db-d910-46fb-b563-0ea7b9670bdd)
![2024-05-08_15-15-30](https://github.com/Hufe921/canvas-editor/assets/95992064/c2ba7f48-271f-4b1a-87b9-2b20b403cd90)
![2024-05-08_15-15-59](https://github.com/Hufe921/canvas-editor/assets/95992064/fd614bf8-c31c-43f0-a165-e0a79ddb8fb2)

### What is expected?

不产生同源策略问题，可正常使用

### What is actually happening?

由于import xxx from './xxx?worker&inline'在生产环境中产生的同源策略问题导致编辑器无法进行任何操作

**Comment by Hufe921** [comment]
你是如何使用的，给出最小可复现demo

**Comment by ProLiok** [comment]
找到原因的，谢谢回复
