### ISSUE TITLE
表单模式下控件通过快捷键跳转

### ISSUE THREAD

**Issue by nakuYK** [Hufe921/canvas-editor#548]
### version

0.9.76

### Steps to reproduce

左右按键在表单模式无法切换到下一个控件，表格内再嵌入一个表格后无法选中里面的表格

### What is expected?

表单模式可以通过按键切换到不同控件，表格嵌套正常使用

### What is actually happening?

左右按键在表单模式无法切换到下一个控件，表格内再嵌入一个表格后无法选中里面的表格

**Comment by Hufe921** [comment]
不支持表格嵌套。表单模式下控件跳转考虑支持

**Comment by Hufe921** [comment]
1. 光标在控件内时：tab键跳入下一个控件， tab+shift跳转到上一个控件
2. 表单模式&光标在控件头时：左箭←跳转到上一个控件
3. 表单模式&光标在控件尾时：右箭→跳转到下一个控件
