### ISSUE TITLE
元素是否能添加唯一标识，并通过该标识获取到该元素及子元素数据

### ISSUE THREAD

**Issue by nakuYK** [Hufe921/canvas-editor#552]
### What problem does this feature solve?

例如我组合表格和图像和文字创建了一个组合模板，当我想插入该模板时想查询文档内是否已存在该模板，已有则能获取模板数据，手动对数据更新后能直接替换原数据

### What does the proposed API look like?

- 数据结构能添加唯一标识id
- 根据指定id获取元素value.data
- 根据指定id替换元素value.data

**Comment by Hufe921** [comment]
1. element增加externalId并设置唯一数据
2. 获取编辑器数据，并根据externalId进行数据更改
``` javascript
// 获取当前数据
const value = instance.command.getValue()
value.data.main.forEach(element => {
  if (element.externalId === 'xxxxxx') {
    element.value = 'new value'
  }
})
// 重设数据
instance.command.executeSetValue(value.data)
```
