### ISSUE TITLE
增加表格行线拖拽功能

### ISSUE THREAD

**Issue by zp190265950** [Hufe921/canvas-editor#555]
### What problem does this feature solve?

在canvas-editor当做模板来使用渲染的时候，某种场景下
1.每一个表格的整体高度不能改变，会使用到表格单元格行拖拽和列拖拽一样改变相邻单元格的大小，不改变整体表格的高度
2.在这种场景下，表格整体高度不能变动，并且在渲染中单元格的行高不随着内容的高度变化
以上两个需求我在使用中遇到的，已经有代码实现，如果合理我可以提交pr

### What does the proposed API look like?

通过单元格配置的方式，可以达到拖拽单元格行线改变相邻行的高度，不改变整体高度，并且行高不随着单元格内容的增加而改变高度

**Comment by zp190265950** [comment]
<img width="1141" alt="表格2" src="https://github.com/Hufe921/canvas-editor/assets/41977379/91b99f74-55fe-431f-b6a0-35b62e68eb9b">
<img width="1133" alt="表格3" src="https://github.com/Hufe921/canvas-editor/assets/41977379/a18982dd-5af5-4929-8371-a240d8b058a1">
有上图这种表格模版有多张，每一张都都只能占位一页，如果内容撑高或者拖拽行线增加整体高度，表格会到第二页，每一页必须展示和模版的一样，用户填充编辑的时候可以自己拖拽改变单元格大小，不改变整体高度

**Comment by Hufe921** [comment]
wps word有没有类似的交互

**Comment by zp190265950** [comment]
> wps word有没有类似的交互

看了下word和wps目前没有类似的交互，可能我项目中的这个场景比较特殊，那我在自己项目中定制化处理吧
