### ISSUE TITLE
获取options中的宽高和朝向没有对应

### ISSUE THREAD

**Issue by zp190265950** [Hufe921/canvas-editor#558]
### What problem does this feature solve?

博主您好，在获取配置项的时候发现width和height没有和朝向同步，需要单独根据paerDirection去转换，所见即所得应该获取的options中width和height和视图显示的一致

### What does the proposed API look like?

使用getOptions获取的配置中width和height是页面上显示的宽高

**Comment by Hufe921** [comment]
宽高设置，不随方向变化

**Comment by zp190265950** [comment]
> 宽高设置，不随方向变化

如果实例化的外面需要获取当前视图的宽高，是否可以把getOriginalWidth和getOriginalHeight方法暴漏出来
