### ISSUE TITLE
纸张横向时，打印出现空白页

### ISSUE THREAD

**Issue by ThunderYu** [Hufe921/canvas-editor#559]
### version

0.9.76

### Steps to reproduce

调整纸张方向为横向，然后点击打印

### What is expected?

正常打印

### What is actually happening?

打印预览时每一页后面都跟了一张空白页

### System Info

```shell
OS: Windows 11 10.0.22631
 Browsers:
   Edge: Chromium (123.0.2420.97), ChromiumDev (123.0.2420.10)
```

**Comment by Hufe921** [comment]
无法复现，确认一下是否有页边距设置
