### ISSUE TITLE
表格前面回车会出现两个空行

### ISSUE THREAD

**Issue by zp190265950** [Hufe921/canvas-editor#565]
### version

main

### Steps to reproduce

https://github.com/Hufe921/canvas-editor/assets/41977379/2b287236-8f4b-40e3-9d18-1faedf3eccf3

表格前面回车会出现多行

### What is expected?

正常显示

### What is actually happening?

表格前面回车会出现多行

### Any additional comments?

无

**Comment by zp190265950** [comment]
> ### version
> main
> 
> ### Link to minimal reproduction
> _No response_
> 
> ### Steps to reproduce
>  2024-05-14.13.51.18.mov 
> 表格前面回车会出现多行
> 
> ### What is expected?
> 正常显示
> 
> ### What is actually happening?
> 表格前面回车会出现多行
> 
> ### System Info
> _No response_
> 
> ### Any additional comments?
> 无
<img width="596" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/41977379/908c1565-4dc5-4856-b2b1-8a1f359b0bc4">
视频上面回车也会出现同样问题

**Comment by Hufe921** [comment]
理论上就是2个行，因为表格是行元素独占一行。如果行元素作为第一个插入的元素，代码进行了特殊处理把首行的高度减小。

**Comment by zp190265950** [comment]
> 理论上就是2个行，因为表格是行元素独占一行。如果行元素第一个插入的元素作为行元素，代码进行了特殊处理把首行的高度减小。

博主您好，这种交互下，但是首行行高好像并没有，回车添加的数据没有type，第一行的行高并没有和预想的一样设置defaultBasicRowMarginHeight
