### ISSUE TITLE
编辑器的控件和表单业务结合的可能性

### ISSUE THREAD

**Issue by ALagom** [Hufe921/canvas-editor#566]
### What problem does this feature solve?

大佬，最近在找类似的在线类word编辑器，找了一大圈，就数您这个编辑器比较牛逼了，API也多，插件也丰富。首先感谢您能给大家开源这么牛逼的产品，还能持续更新！奉献上我的膝盖！

我是想做一个文档式表单。基于您这个控件方式可以和传统的业务表单进行结合，进行数据交互。

就是用给客户提供两种填写数据的方式，例如下列效果图，用户可选择一种。

通过API给您这个编辑器中的控件进行赋值或获取值。这样对用户交互体验来说更方便，对我们系统层面来说，方便获取编辑器中的数据到数据库，后续做结构化数据分析。

不知道是否可以实现或者给一些建议呢？

![image](https://github.com/Hufe921/canvas-editor/assets/83748050/bd07ddbd-2747-4510-9d90-20a94a08b159)

### What does the proposed API look like?

正在构思……

**Comment by Hufe921** [comment]
使用编辑器的数据结构，绘制form表单？

**Comment by ALagom** [comment]
> 使用编辑器的数据结构，绘制form表单？

绘制form估计难度比较大，初步思路是基于控件的方式。
1、新建页面室，在保存数据时，我们通过getControlList和getControlValue获取页面上所有控件的值，然后调用我们系统的接口，新增更新数据。编辑器的数据还是会独立再保存一份。
2、在编辑数据时，同步调用我们的接口以及executeSetControlValue接口给控件赋值
不知道这样说 是否说清楚了

**Comment by Hufe921** [comment]
可以
