### ISSUE TITLE
添加更新编辑器配置api

### ISSUE THREAD

**Issue by 284668461** [Hufe921/canvas-editor#571]
### What problem does this feature solve?

作者你好，我想要在编辑器初始化完毕后，由用户来自定义页码是否展示和其他的size、rowFlex等相关设置，找遍了文档、示例和issue，都没发现可用的的comman命令。请问有没有此命令？没有的话可否在后面加上。
另外就是，别的配置（IHeader  等）好像也无法在编辑器初始化后再进行更改？

### What does the proposed API look like?

也许可以来个类似以下命令的api 来更新所有的配置？
`
instance.command.executeSet({
      IPageNumber:{
            rowFlex:"RIGHT"，
            fromPageNo：1
      }
})
`

**Comment by 284668461** [comment]
@Hufe921  感谢回复。销毁再重新实例化编辑器可以实现目的。文档中说 executeForceUpdate 可以强制重新渲染文档，又可以传递参数进去，但试了下使用强制渲染无法更新配置，想了解下这个executeForceUpdate  命令是在什么情况下使用？又应该传递哪些参数进去？

**Comment by Hufe921** [comment]
说明：executeForceUpdate用于强制重新渲染编辑器内容。正常情况下用不到此api，某些场景下如：通过getOptions方法获取配置后进行修改，后执行executeForceUpdate就可以看到更新配置的效果。

限制：仅对渲染时的配置（如：defaultColor、defaultSize......）有效，实例化就已经用到的配置（如：width、height）无效。
