### ISSUE TITLE
能否把Draw实例放出来，我点击表格，并不能用过现有方法获取到我点击的地方是表格内的某一行

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#573]
### What problem does this feature solve?

1

### What does the proposed API look like?

1

**Comment by Hufe921** [comment]
内部私有类不能放出来。需要什么api可以提issues并描述清楚使用场景，需要实现的功能。

**Comment by wen-shiqiang** [comment]
需要一个我点击到canvas的时候，获取到当前的组件是什么，以及当前组件的elementList，positionContext

**Comment by wen-shiqiang** [comment]
我的问题是，点击表格的某一列的单元格，我不知道这个整体是表格，我也不知道我点击的是，表格的哪一个单元格

**Comment by guozhenqianga** [comment]
> 我的问题是，点击表格的某一列的单元格，我不知道这个整体是表格，我也不知道我点击的是，表格的哪一个单元格

麻烦问下，这个功能实现了吗
