### ISSUE TITLE
点击表格的某一个的单元格，我不知道这个整体是表格，我也不知道我点击的是表格的哪一个单元格，目前的方法并不能支持

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#574]
### What problem does this feature solve?

1

### What does the proposed API look like?

1

**Comment by Hufe921** [comment]
需要清晰的描述使用场景，及想要提供的api，不要直接在标题详细描述问题！

https://hufe.club/canvas-editor-docs/guide/contextmenu-custom.html
context. isInTable 即可判断是否在表格内
