### ISSUE TITLE
添加新的编辑器API

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#575]
### What problem does this feature solve?

在使用中，发现右键并没有事件，我需要在右键表格的时候，根据表格的elementList中的自定义字段去判断，禁用表格右键菜单的某几项

### What does the proposed API look like?

1

**Comment by Hufe921** [comment]
> "表格的elementList中的自定义字段"是什么意思？是表格本身element还是单元格内的element？

**Comment by wen-shiqiang** [comment]
> > “表单的elementList中的自定义字段”是什么意思？是表单本身元素还是单元格内的元素？

是我自定义个一个字段
![Uploading 微信截图_20240517091704.png…]()

**Comment by wen-shiqiang** [comment]
![微信截图_20240517091704](https://github.com/Hufe921/canvas-editor/assets/53844499/2dc9c1a0-1bed-487a-89f1-55c44e9317aa)
是我自定义的一个字段，我需要在右键的时候通过这个字段去判断，表格右键的时候显示哪几个菜单

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/576
