### ISSUE TITLE
添加新的编辑器API

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#576]
### What problem does this feature solve?

在使用表格的时候，发现我点击到表格的某一个单元格，并不能通过现有api告诉我，这是一个表格和点击的是表格哪一行那一列，以及当前的表格的实例（elementList），希望有一个api可以在我点击到表格的时候告诉我，这是哪一行那一列，以及当前的表格整体实例

### What does the proposed API look like?

这个方法能给到的参数包括，positionContext告诉我这是不是一个表格以及是哪一行哪一列，elementList告诉我当前实例，通过这两个参数可以实现我目前的需求

**Comment by Hufe921** [comment]
1. 通过事件instance.command.getRangeContext()可以获取光标所在表格内上下文信息
```
type RangeContext = {
  isCollapsed: boolean
  startElement: IElement
  endElement: IElement
  startPageNo: number
  endPageNo: number
  rangeRects: RangeRect[]
  zone: EditorZone
  isTable: boolean
  trIndex: number | null
  tdIndex: number | null
  tableElement: IElement | null
}
```
2. 右键菜单(https://hufe.club/canvas-editor-docs/guide/contextmenu-custom.html)
```
when?: (payload: IContextMenuContext) => boolean;
interface IContextMenuContext {
  startElement: IElement | null
  endElement: IElement | null
  isReadonly: boolean
  editorHasSelection: boolean
  editorTextFocus: boolean
  isInTable: boolean
  isCrossRowCol: boolean
  zone: EditorZone
  trIndex: number | null
  tdIndex: number | null
  tableElement: IElement | null
}
```
