### ISSUE TITLE
【bug】浏览器切换tab编辑器会白屏

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#578]
### version

0.9.77

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/f2aea2e3-d4b5-4407-a825-52189cb8384d)
![image](https://github.com/Hufe921/canvas-editor/assets/27660604/127b75dc-c0d5-4026-936b-f5ed93641104)
 

### What is expected?

白屏消失

### What is actually happening?

编辑器白屏

**Comment by Hufe921** [comment]
无法重现，举出详细复现步骤，环境等

**Comment by zhuyihe** [comment]
Uploading 893b4abe6da9fd9303f68eb4e6e4595d.mp4…

我拍了视频

**Comment by zhuyihe** [comment]
浏览器版本
![image](https://github.com/Hufe921/canvas-editor/assets/27660604/398872b5-403a-4b5e-8f2c-7b892c8d408d)

**Comment by Hufe921** [comment]
增加兼容逻辑：页面可见时重新渲染。
