### ISSUE TITLE
win7系统编辑的时候出现渲染问题，请教有什么解决思路？

### ISSUE THREAD

**Issue by Demon1110** [Hufe921/canvas-editor#583]
### version

0.9.77

### Steps to reproduce

![Weixin Image_20240518181357](https://github.com/Hufe921/canvas-editor/assets/9859323/9fe6371e-417d-4406-9895-4a7403363c65)

### What is expected?

想知道什么原因导致的，如何解决？

### What is actually happening?

win7出现，其他系统没发现

### System Info

```shell
win7
```

**Comment by Hufe921** [comment]
浏览器版本是什么
