### ISSUE TITLE
添加文本，获取html时，样式没有添加上去

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#584]
### What problem does this feature solve?

![微信截图_20240520110206](https://github.com/Hufe921/canvas-editor/assets/53844499/d31f7ee6-090d-4be3-b093-c977d330d257)

获取到的html是这样的，样式并没有放到标签上，居中也没有

"<p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p><span></span><p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"border-top: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); width: 554px;\"><colgroup><col width=\"554\"></colgroup><tr style=\"height: 53px;\"><td colspan=\"1\" rowspan=\"1\" style=\"border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;\"><span></span></td></tr></table>"

### What does the proposed API look like?

![微信截图_20240520110206](https://github.com/Hufe921/canvas-editor/assets/53844499/47c76358-23e8-42b1-843c-eb2ca2d2d446)

**Comment by wen-shiqiang** [comment]
<p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p>
<span></span>
<p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p>
<table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"border-top: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); width: 554px;\">
	<colgroup>
		<col width=\"554\">
	</colgroup>
	<tr style=\"height: 53px;\">
		<td colspan=\"1\" rowspan=\"1\" style=\"border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;\">
			<span></span>
		</td>
	</tr>
</table>

**Comment by wen-shiqiang** [comment]
"<p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p><span></span><p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; color: rgb(0, 0, 0); font-size: 16px;\"></p><table cellspacing=\"0\" cellpadding=\"0\" border=\"0\" style=\"border-top: 1px solid rgb(0, 0, 0); border-left: 1px solid rgb(0, 0, 0); width: 554px;\"><colgroup><col width=\"554\"></colgroup><tr style=\"height: 53px;\"><td colspan=\"1\" rowspan=\"1\" style=\"border-right: 1px solid; border-bottom: 1px solid; vertical-align: top;\"><span></span></td></tr></table>"

**Comment by wen-shiqiang** [comment]
![微信截图_20240520111351](https://github.com/Hufe921/canvas-editor/assets/53844499/a4d201bf-8e5a-49cf-b2ea-d26ed256da7c)

**Comment by Hufe921** [comment]
控件没有值，html不解析
