### ISSUE TITLE
导出html时的问题

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#585]
### version

0.9.78

### Steps to reproduce

一行添加两个文本，导出html会换行，dom是SPAN包着P标签,所以会导致换行

### What is expected?

![微信截图_20240520154822](https://github.com/Hufe921/canvas-editor/assets/53844499/2535ef33-36cd-442a-a727-21b111edc075)

### What is actually happening?

![Uploading 微信截图_20240520154758.png…]()

**Comment by wen-shiqiang** [comment]
![微信截图_20240520154758](https://github.com/Hufe921/canvas-editor/assets/53844499/d25c63a4-4198-4853-b84e-f02b6bc458ce)

**Comment by wen-shiqiang** [comment]
![微信截图_20240520162825](https://github.com/Hufe921/canvas-editor/assets/53844499/ed4a49d1-716f-4f66-89f3-9e261ed0e508)
这种文本加输入文字也会出现这种问题

**Comment by Hufe921** [comment]
getValue获取一下编辑器数据，发出来

**Comment by wen-shiqiang** [comment]
{
    "header": [],
    "main": [
        {
            "value": "",
            "type": "control",
            "control": {
                "type": "text",
                "value": [
                    {
                        "value": "321",
                        "type": "text",
                        "rowFlex": "center"
                    }
                ],
                "placeholder": "123"
            }
        },
        {
            "value": "66666"
        }
    ],
    "footer": []
}

**Comment by wen-shiqiang** [comment]
{
    "header": "",
    "main": "<span><p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; font-size: 16px;\">321</p></span><span style=\"font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;\">66666</span>",
    "footer": ""
}

**Comment by wen-shiqiang** [comment]
"<span><p style=\"font-family: &quot;Microsoft YaHei&quot;; text-align: center; font-size: 16px;\">321</p></span><span style=\"font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;\">66666</span>"

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/586

**Comment by wen-shiqiang** [comment]
大哥，表格外层用div，textAlign是不生效的
<img width="617" alt="PixPin_2024-05-22_16-16-20" src="https://github.com/Hufe921/canvas-editor/assets/53844499/e0ccf2f2-85f8-4084-b737-9552a5ae15b4">
