### ISSUE TITLE
添加新的api

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#587]
### What problem does this feature solve?

在使用中发现导出html时，同一行数据导出html时，会出现不在一行的问题
<img width="892" alt="微信截图_20240520162825" src="https://github.com/Hufe921/canvas-editor/assets/53844499/5ff8a933-1c2a-406e-8813-efa4810d67a9">

### What does the proposed API look like?

能否在当前实例添加当前数据哪几条是在一行的字段，这样在导出html时，可以用这个字段作为一个大的容器，往这个大容器里面添加span

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/586
一个问题不要反复提交issue，在一个issue总结
