### ISSUE TITLE
【bug】连页模式上传多张图片之后切换成分页模式光标显示错误

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#589]
### version

0.9.78

### Steps to reproduce

1.连页上传多张图片
2.切换成分页模式

### What is expected?

光标正常显示

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/7eb31094-0ddd-4ee8-81fe-df948958cd88)

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/589
