### ISSUE TITLE
【bug】图片拉长显示不正确

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#590]
### version

0.9.78

### Steps to reproduce

1.上传一张图片
2.图片向下拉伸

### What is expected?

图片显示正确

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/27660604/0d368d2e-9e0b-4ca7-bafd-d08e355e794a)

**Comment by Hufe921** [comment]
图片高度过长，自行拖拽调整
