### ISSUE TITLE
希望添加滚动到页面某个位置的API

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#592]
### What problem does this feature solve?

希望点击外部按钮能滚动到页面的某个地方
我看到文档里面只有目录定位的功能

### What does the proposed API look like?

instance.command.executeScrollintoview(id)

**Comment by Hufe921** [comment]
场景是什么？

**Comment by zhuyihe** [comment]
比如通过外部接口获取的关键字
或者根据接口获取关键段落id滚动到关键的地方
再比如连续性病历，根据id滚动到病程记录
问一下大佬 如果是连续性病历应该如何展示呢？

**Comment by zhuyihe** [comment]
问下controlId怎么通过控件传入
这边传入了controlId
![image](https://github.com/user-attachments/assets/4141db16-d35d-424c-b4f0-94874ce23de3)

但是在渲染文字的时候将控件拆分，controlId随机生成了，导致无法定位
![image](https://github.com/user-attachments/assets/638dc650-4b5a-4b7d-ae65-a98817f95cb0)
