### ISSUE TITLE
页面设置缩放后，渲染出现问题

### ISSUE THREAD

**Issue by nakuYK** [Hufe921/canvas-editor#594]
### version

0.9.78

### Steps to reproduce

页面设置缩放，换行或其他操作会出现渲染问题
![image](https://github.com/Hufe921/canvas-editor/assets/44085403/64ced972-f395-41ba-a026-36a0a9c3a09c)

### What is expected?

显示正常

### What is actually happening?

显示不正常

**Comment by Hufe921** [comment]
什么浏览器 什么版本

**Comment by nakuYK** [comment]
> 什么浏览器 什么版本

Edge浏览器125.0.2535.51

**Comment by nakuYK** [comment]
![image](https://github.com/Hufe921/canvas-editor/assets/44085403/2fdf8e11-7fdb-4e52-92a7-974e11d66860)


- 设置浏览器缩放

- 在编辑器内换行或者是进行其他编辑操作

- 有时候未出现，调整缩放比例或刷新示例网站重试后照样会复现
