### ISSUE TITLE
设置控件属性：deletable 后出现问题

### ISSUE THREAD

**Issue by nakuYK** [Hufe921/canvas-editor#595]
@Hufe921 设置控件属性：deletable 后，设置控件值会保留控件内的原来的值，当聚焦控件时又是替换原来的值

_Originally posted by @nakuYK in https://github.com/Hufe921/canvas-editor/issues/553#issuecomment-2107162523_

**Comment by Hufe921** [comment]
如何复现

**Comment by nakuYK** [comment]
> 如何复现
文本控件设置属性 deletable:true，
调用 editor.command.executeSetControlValue() 修改控件值，聚焦控件和不聚焦效果不一致

**Comment by Hufe921** [comment]
无法复现，请确认版本或提供最小可复现demo地址

**Comment by nakuYK** [comment]
> 无法复现，请确认版本或提供最小可复现demo地址

搞错了，是设置为 deletable:false ，看控制台，执行executeSetControlValue() 会保留原有值，当聚焦于控件时，又不保留了
![image](https://github.com/Hufe921/canvas-editor/assets/44085403/34349b64-d9eb-4f6b-9c6d-9a844c0328e1)
