### ISSUE TITLE
能否增加一个插入空白文本的api?

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#596]
### What problem does this feature solve?

现在的增加文本控件后，在这个文本控件中不能再增加其他控件，不能嵌套，在实际使用中，比如我增加个空白文本，有id来绑定后，我就可以在这个空白文本上增加其他文本，控件等等，最终能获取到这个空白文本上所有的内容。好像目前没有这种功能。用title,感觉无法达到逾期的效果。

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
通过https://hufe.club/canvas-editor-docs/guide/command-get.html#gettitlevalue
