### ISSUE TITLE
设置编辑器宽度后，页面显示和打印预览也不正常

### ISSUE THREAD

**Issue by cgm629** [Hufe921/canvas-editor#597]
### version

0.9.78

### Steps to reproduce

step 1. 点击编辑器配置-> 将宽度设置设为1300 -> 点击确定后宽度无变化（随后将比例放大为110倍后再缩小为100%，能正常显示）
step 2.点击打印，预览的布局没有根据最新编辑器宽度进行自适应 

### What is expected?

修改编辑器配置后能够成功显示修改后的宽度，打印预览能够根据配置调整

### What is actually happening?

![image](https://github.com/Hufe921/canvas-editor/assets/58407616/ec0628ec-881d-4d65-804f-e07d38004005)
![image](https://github.com/Hufe921/canvas-editor/assets/58407616/c37dec39-7d4a-4439-954d-d56b7e4ee42a)

**Comment by Hufe921** [comment]
1. 通过指定病历修改页面宽高https://hufe.club/canvas-editor-docs/guide/command-execute.html#executepapersize，渲染配置使用https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeupdateoptions，具体讨论https://github.com/Hufe921/canvas-editor/issues/571#issuecomment-2112631326
2. 打印预览看浏览器选择纸张大小
