### ISSUE TITLE
导出html错误汇总

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#598]
### version

0.9.78

### Steps to reproduce

导出html时，两个表格同时设置居中，导出会被一个div包裹，style="text-align: center;"导出并没有居中，并且不是一行的数据被同一个div包裹了，会导致两行数据导出html时变成了一行

### What is expected?

![微信截图_20240524173743](https://github.com/Hufe921/canvas-editor/assets/53844499/1c0c6372-c6aa-4fb9-9472-8db9a8fae40d)

### What is actually happening?

![微信截图_20240524173800](https://github.com/Hufe921/canvas-editor/assets/53844499/7d50a861-eabd-4244-965d-dc56dfca1cf7)

**Comment by wen-shiqiang** [comment]
这种是两行数据设置了居中，第二行会跟第一行合并在一起
<img width="388" alt="3" src="https://github.com/Hufe921/canvas-editor/assets/53844499/89978c8a-9247-4ca9-8e96-b387d44c0b6f">
![2](https://github.com/Hufe921/canvas-editor/assets/53844499/0436167b-32ac-471c-8d5b-d0e4aa587097)

**Comment by wen-shiqiang** [comment]
图片也烧一样的问题
<img width="547" alt="5" src="https://github.com/Hufe921/canvas-editor/assets/53844499/2ca5fde2-da9b-430f-a555-3e8cd7bebef2">
<img width="532" alt="6" src="https://github.com/Hufe921/canvas-editor/assets/53844499/d7197253-9236-4209-af41-61bb294bf6a9">

**Comment by wen-shiqiang** [comment]
导出html时，有时候一段话会被分成一个字一个标签
<img width="376" alt="7" src="https://github.com/Hufe921/canvas-editor/assets/53844499/28429d3a-f5a4-4001-81e2-cfce57e60486">
<img width="590" alt="8" src="https://github.com/Hufe921/canvas-editor/assets/53844499/bb201ae6-b9f3-4348-93a5-1d6f83ae4da3">

**Comment by Hufe921** [comment]
1. 调整块元素（block元素、分页符、分割线、表格、图片上下嵌入型）为独立容器，其他默认使用换行符<br/>
2. 块元素通过flex的justifyContent属性设置行布局
3. 处理控件插入时行布局信息丢失的问题
由于html的灵活性，如有进一步转换html的需求自行通过getValue获取编辑器结构化数据转换，不再优先处理转换html的需求。
