### ISSUE TITLE
藏文换行规则错误

### ISSUE THREAD

**Issue by 289420843** [Hufe921/canvas-editor#600]
### version

v0.9.78

### Steps to reproduce

感谢您对藏文显示的支持，我也不是很懂，据我观察藏文换行跟英文类似，换行的时候单词不会才拆分开，藏文中只有后面跟随“**་**”或者"**།**"才代表一个词完成，我不是专业的，所以只能提供这些依据。
![PixPin_2024-05-24_18-12-24](https://github.com/Hufe921/canvas-editor/assets/5706753/1f474644-cbd9-4a6c-a4a1-ded666e52141)
在浏览器缩小宽度时
![PixPin_2024-05-24_18-13-38](https://github.com/Hufe921/canvas-editor/assets/5706753/6a839eac-ea24-4857-b7d6-c6fd9e0069d0)
我认为是这样划分单词的
![218CD0DD-28D0-490c-B849-AE907A9FC20D](https://github.com/Hufe921/canvas-editor/assets/5706753/1fab37dd-73d6-4288-b055-ad6e2d03772d)

### What is expected?

按照正常的规则进行换行

### What is actually happening?

换行规则错误

**Comment by Hufe921** [comment]
看看通过[letterClass](https://github.com/Hufe921/canvas-editor/issues/279)是否可以配置，如不支持编辑器暂不考虑官方支持藏文分词，可以clone项目自行修改
