### ISSUE TITLE
导出pdf分支功能不会加入到主分支吗

### ISSUE THREAD

**Issue by fqyt** [Hufe921/canvas-editor#607]
### What problem does this feature solve?

作者你好，我看到 feature/pdf 这个分支已经实现了直接导出为pdf的功能，但是文档上写着暂不考虑将该功能合并到主分支，因为有的时候用户的操作习惯可能是点击一下直接生成pdf文件，而不希望点击打印然后另存为pdf这两个步骤，如果主分支也能直接导出为pdf的话可能更好一点，谢谢

### What does the proposed API look like?

希望主分支能点击直接生成pdf文件

**Comment by Hufe921** [comment]
feature/pdf不会合并到主分支，feature/svg会。
pdf受限于字体、系统环境等，在前端生成是不合适的，应该交由后端生成。如果使用nodejs可以参考feature/pdf分支开发。

**Comment by fqyt** [comment]
> feature/pdf 不会合并到主分支，feature/svg会。 pdf 定义为字体、系统环境等，在前端生成是不合适的，应该交由报表生成。如果使用 nodejs 可以参考 feature/pdf 分支开发。

好的，感谢您的解答
