### ISSUE TITLE
输入英文字母无法正确计算字数

### ISSUE THREAD

**Issue by cgm629** [Hufe921/canvas-editor#608]
### version

0.9.79

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/58407616/07d7316b-ae7c-4c44-afc1-b3b3b3583715)

### What is expected?

能够正确计算出中英文字数

### What is actually happening?

输入英文字母无法正确计算字数

**Comment by Hufe921** [comment]
不是一个字母就是一个字，而是一个单词
