### ISSUE TITLE
点击头部，跳转到底部，而且选中了

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#609]
### version

0.9.79

### Steps to reproduce

https://github.com/Hufe921/canvas-editor/assets/53844499/e4ac54c6-b156-4a85-8a30-2792a7e16fe2

### What is expected?

1

### What is actually happening?

1

**Comment by ThunderYu** [comment]
我点出了类似的问题，进入页面后切换到连页显示，然后点击页眉的位置就会跳转到底部，另外此时鼠标移动到底部时仍然会显示“双击编辑页脚”
