### ISSUE TITLE
文本粘贴问题

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#611]
### version

0.9.79

### Steps to reproduce

1.文本在居中的时候会出现复制就不是文本了，就变成纯文本了，而且会新增几个换行

2.右键复制粘贴用不了

### What is expected?

https://github.com/Hufe921/canvas-editor/assets/53844499/3f017abd-b87e-414f-ae82-621379ea4d03

### What is actually happening?

1

**Comment by Hufe921** [comment]
iframe 下必须同源，否则编辑器依赖pai navigator.clipboard.readText不支持，可行方案：
1. 可以自行处理粘贴方法：https://hufe.club/canvas-editor-docs/guide/override.html#paste
2. 修改同源策略走代理访问，避免iframe嵌入，通过微应用进行集成等
