### ISSUE TITLE
建议优化 executeSetValue 

### ISSUE THREAD

**Issue by 284668461** [Hufe921/canvas-editor#615]
### What problem does this feature solve?

作者你好，我尝试使用 command.getValue() 使用获得文档模板数据后，使用  command.executeSetValue 命令再把数据渲染到编辑器上，发现 watermark 丢失，然后研究了下代码，发现 executeSetValue  的参数类型是  IEditorData。也就是说别的 width,height,watermark  都不能通过 executeSetValue   更新上去。还是说要用别的 api 来渲染这几项？若是没有的话建议优化下 executeSetValue  api

**补充下**： 使用 executeUpdateOptions 命令可以设置水印，但width,height 等其他属性不行。

### What does the proposed API look like?

优化api

**Comment by 284668461** [comment]
使用在github 上最新拉下来的代码测试了下， 插入以下代码进行测试了下
`
const testBtn = document.querySelector<HTMLDivElement>('.menu-item__test')!
  testBtn.onclick = function () {

    const res = instance.command.getValue()
    let resStr = JSON.stringify(res)

    resStr = resStr.replace('人民医院', '医院aaaa')
    resStr = resStr.replace('CANVAS-EDITOR', '水印aaa')

    const res2 = JSON.parse(resStr)

    instance.command.executeSetValue({
      ...res2,
      ...res2.data
    })
  }
`

发现人民医院确实变成了  医院aaaa，然后水印文字仍然是旧的 CANVAS-EDITOR

**Comment by cgm629** [comment]
用下executeUpdateOptions，宽高之类的应该是选项不是值

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeaddwatermark

**Comment by 284668461** [comment]
好吧，是我想当然了（捂脸）。下意识的以为可以用类似以下的这种方式使用  dom.setValue(dom.getValue())
