### ISSUE TITLE
连页模式下页眉页脚丢失

### ISSUE THREAD

**Issue by cgm629** [Hufe921/canvas-editor#616]
### version

0.9.79

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/58407616/54449438-dda3-48c2-a31d-bcb1e81bb7d6)

### What is expected?

连页模式可以正常显示页眉页脚

### What is actually happening?

连页模式下页眉页脚丢失

**Comment by Hufe921** [comment]
连页模式没有页眉页脚
