### ISSUE TITLE
希望可以控制最大页数

### ISSUE THREAD

**Issue by wen-shiqiang** [Hufe921/canvas-editor#617]
### What problem does this feature solve?

使用中可以无限新增页数，希望可以控制一下最大页数

### What does the proposed API look like?

1

**Comment by Hufe921** [comment]
场景是什么

**Comment by wen-shiqiang** [comment]
使用场景是配置word封面，封面只能有一页，目前使用pageSizeChange判断是否大于1，如果大于1就执行executeUndo，也能实现，但是输入中文，会新增一页，确定输入的时候在执行executeUndo，不友好

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/option.html#%E9%A1%B5%E7%A0%81%E9%85%8D%E7%BD%AE
maxPageNo
