### ISSUE TITLE
能否绘制生成一个带数据的表格

### ISSUE THREAD

**Issue by aglsv** [Hufe921/canvas-editor#623]
### What problem does this feature solve?

目前是想点击导入一个表格的数据，目前是能拿到一个数组，里面是每一个td的数据，想把这个数据绘制到页面上生成一个表格，请问有哪个方法可以实现吗

### What does the proposed API look like?

renderTable方法？

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeinsertelementlist

**Comment by aglsv** [comment]
> https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeinsertelementlist

是需要自己把数据攒一个IElement[]类型的数据吗，请问这一步有没有什么方法呢
