### ISSUE TITLE
单个单元格高度超过一页时，无法正常显示

### ISSUE THREAD

**Issue by nakuYK** [Hufe921/canvas-editor#624]
### version

0.9.79

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/44085403/deea98de-1267-44e6-a083-14135e44fdca)

### What is expected?

单元格跨页显示

### What is actually happening?

显示不正常

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/41
