### ISSUE TITLE
RIGHT TO LEFT 

### ISSUE THREAD

**Issue by alsumairi98** [Hufe921/canvas-editor#625]
Hi @Hufe921 , i hope you doing great .. 
first of all thank you for this amazing job ,I need help in how to implement RTL direction to write in Arabic language.
i try to solve this problem using "css dir" but it does work . 
![image](https://github.com/Hufe921/canvas-editor/assets/84264719/24cbf304-1691-4bac-9fdc-9fb58cc1d2fa)

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/451
