### ISSUE TITLE
能否增加对于markdown的显示和转换功能

### ISSUE THREAD

**Issue by chenkang1** [Hufe921/canvas-editor#627]
### What problem does this feature solve?

目前好像没有对于markdown的解析和展示功能，能否增加这个特性，或者能否提供以下实现思路。。非常感谢

### What does the proposed API look like?

markdown api

**Comment by Hufe921** [comment]
参考https://github.com/Hufe921/canvas-editor/blob/main/src/plugins/markdown/index.ts 
可以封装成插件https://github.com/Hufe921/canvas-editor-plugin
此仓库不维护markdown的处理
