### ISSUE TITLE
在内容中复制一个标题，样式保留但类型会被解析成正文

### ISSUE THREAD

**Issue by cgm629** [Hufe921/canvas-editor#630]
### version

0.9.79

### Steps to reproduce

先在wps中复制一个一级标题，再在canvas的内容中粘贴，样式保留但类型会被解析成正文：
![image](https://github.com/Hufe921/canvas-editor/assets/58407616/974f3273-8c58-4b12-b88b-30620ab03b95)

但如果清空全部canvas内容再粘贴，就能正确解析：
![image](https://github.com/Hufe921/canvas-editor/assets/58407616/ece5fb0c-e52d-4661-8d9a-ef1be55826e6)

### What is expected?

能够正确解析标题

### What is actually happening?

在内容中复制一个标题，样式保留但类型会被解析成正文

**Comment by Hufe921** [comment]
会根据当前上下文是否属于正文或标题，来确定复制来的html是否属于正文或标题。
