### ISSUE TITLE
当控件  disabled= true 时，仍可删除控件

### ISSUE THREAD

**Issue by 284668461** [Hufe921/canvas-editor#633]
### version

0.9.79

### Steps to reproduce

作者你好，我尝试使用 disabled 来控制控件不被用户删除，当设置    disabled: true 时，光标放在控件后无法删除控件。但当把光标放在控件前，然后按del键仍可以删除控件。不知道这是不是个bug?  

另外还有个问题，当使用 disabled 时 ，组件仅仅是只读了。
假如说我想让文档保持大体的结构，即不想让用户乱删除控件，又想让用户仍然可以编辑。
例如 一个select,  用户不可以删除它，但仍可以改变它的选项。这种方式支持不？

### What is expected?

...

### What is actually happening?

![GIF 2024-06-01 18-56-53](https://github.com/Hufe921/canvas-editor/assets/38812759/0a843898-fc02-41c5-bf75-971f062aacf8)

**Comment by Hufe921** [comment]
使用deletable

**Comment by 284668461** [comment]
好吧，感觉就应该有个单独的属性控制是否删除组件。还以为没有这个功能

**Comment by 284668461** [comment]
@Hufe921   deletable  disabled 这两个属性好像 一般的文本不支持。后续有支持的计划吗？

**Comment by 284668461** [comment]
@Hufe921   deletable  disabled 这两个属性好像不支持 一般的文本。后续有支持的计划吗？
