### ISSUE TITLE
批注优化-跟随页面滚动查看

### ISSUE THREAD

**Issue by chenkang1** [Hufe921/canvas-editor#634]
### What problem does this feature solve?

能否跟随页面滚动实时查看批注内容，并支持executeSetHTML 批注

executeSetHTML 渲染表格如何更新上去

**Comment by Hufe921** [comment]
不要用html去保存或编辑器内容，应该使用编辑器原始结构化数据去保存及还原。
批注功能参考demo自行实现，编辑器核心层不处理批注业务，只提供可以实现批注功能的api。
