### ISSUE TITLE
能否增加个区域文本控件？

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#635]
### What problem does this feature solve?

区域控件上可以放各种控件，能获取到控件的文本内容。
![QQ图片20240603115040](https://github.com/Hufe921/canvas-editor/assets/80032740/751f8379-070a-491e-a132-619fb4159ce6)

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
可以使用标题
