### ISSUE TITLE
追加元素后，光标回到之前正在编辑的位置

### ISSUE THREAD

**Issue by Tsick** [Hufe921/canvas-editor#637]
### What problem does this feature solve?

语音转文字的时候在文末追加元素，同时上面还在编辑改错。

### What does the proposed API look like?

语音转文字的时候在文末追加元素，同时上面还在编辑改错。

**Comment by Hufe921** [comment]
没懂你想要的功能是什么，
想要编辑器实现语音转文字？还是使用语音转文字app时无法插入病历
