### ISSUE TITLE
continuous disease progression display

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#639]
### What problem does this feature solve?

Hello dear author:
                  I am very pleased to come across such an excellent open-source project. However, I am currently facing difficulties with the continuous disease course display and have not found any relevant instructions in the documentation. If the current stage of the project supports it, I hope you could provide some implementation ideas. If not, I hope you could consider supporting this feature. Looking forward to...
Thank you
                                                                    

### What does the proposed API look like?

continuous disease progression display

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/216
