### ISSUE TITLE
getTitleValue无法获取标题下内容

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#640]
### version

0.9.80

### Steps to reproduce

1:插入titile
  instance.command.executeInsertTitle(
    {
    value: '',
    title: {
      conceptId: '123456' // 定义标题概念
    },
    type: ElementType.TITLE,
    level: TitleLevel.SIXTH,
    valueList: [
      {
        value: '主诉：',
        size: 16
      }
    ]
  }
  )
2:在标题下增加组件和内容 数据输出如下：
main:[
{
value:""
type:"title"
valueList:[
{
value:"主诉："
size:16
bold:true
}
{
value:""
type:"control"
control:{
conceptId:"314323"
type:"text"
value:[
{
value:"我来了"
}
]
placeholder:"ladsfasdf"
deletable:false
}
}
{
value:"我们的家在哪里？"
}
]
level:"sixth"
title:{
conceptId:"123456"
}
}
]
3：获取标题
  console.log('获取标题')
  const title = instance.command.getTitleValue(
   {
    conceptId: '123456'
   } 
  );
返回结果:
![微信图片_20240604171018](https://github.com/Hufe921/canvas-editor/assets/80032740/aab7c56f-76bd-46f0-9092-8b0c7fe190b7)

### What is expected?

如上。

### What is actually happening?

如上

**Comment by bettersoft123** [comment]
又试了下可以了，不知道什么原因。可能还是有bug

**Comment by Hufe921** [comment]
标题需单独插入并带有conceptId
