### ISSUE TITLE
how to save the docs

### ISSUE THREAD

**Issue by buhu2k** [Hufe921/canvas-editor#642]
### What problem does this feature solve?

怎么保存文档？写了一半，下次怎么继续？
如何能转成word?

### What does the proposed API look like?

n/a

**Comment by buhu2k** [comment]
最重要的是，这个挺赞的

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-get.html#getvalue

**Comment by buhu2k** [comment]
getHTML? 保存？
这个文档好像没有明确说怎么保存？

**Comment by liushuai05** [comment]
> getHTML? 保存？ 这个文档好像没有明确说怎么保存？

兄弟 你解决了嘛  感觉大佬写的文档有点抽象 完全没搞明白 我现在想搞个按钮点一下保存到数据库 下次加载页面自动加载出来  感觉有点难度
