### ISSUE TITLE
能否支持从外部拖入文本时自定义处理插入，而不是默认作为文本输入呢？

### ISSUE THREAD

**Issue by dskin** [Hufe921/canvas-editor#643]
### What problem does this feature solve?

当我从外部进行拖动时，不一定作为文本或图片进行插入，可能自定义处理为插入文本控件或其他的行为

### What does the proposed API look like?

希望能暴露出自定义处理drop方法的API

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/override.html#drop
