### ISSUE TITLE
生成带文字层的pdf

### ISSUE THREAD

**Issue by aglsv** [Hufe921/canvas-editor#647]
### What problem does this feature solve?

看了下之前的pdf分支，生成的pdf带文字层，逻辑上就是在jspdf里面再画一遍吗？现在版本的代码的嵌套程度比较高，请问是否还支持复制修改一套生成pdf用的绘制方法呢？

### What does the proposed API look like?

通过jspdf绘制一套带文字层的pdf

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/374
