### ISSUE TITLE
复选框和单选框控件内容折行展示

### ISSUE THREAD

**Issue by aglsv** [Hufe921/canvas-editor#652]
### What problem does this feature solve?

目前的单选框和复选框的控件，里面的选项都是默认并排展示，现在想让他们单个选项就能占一行，请问这个有办法实现吗，如果我想修改实现的话是应该修改Draw.computeRowList方法吗，还是应该修改Draw.drawRow方法

目前我是在formatElementList方法中，在生成单选框复选框的时候，在框子前面加了个换行符，不知道是否符合规范

### What does the proposed API look like?

单选框复选框控件选项一个占一行

**Comment by Hufe921** [comment]
加换行符是一个思路。
你可以列举一下需求想要实现的场景及程度，考虑官方实现

**Comment by MzoroHaHa** [comment]
我也有这个需求
![image](https://github.com/user-attachments/assets/82c3bdc2-c05a-4e11-b9fa-3f7405d7c2d9)

列表在表单模式下的选中有时候不好用
