### ISSUE TITLE
文本框中，复制进入大量的文字后，点击删除键盘快速删除，会导致内存急剧飙升。页面卡顿，在老旧机器上会直接导致页面崩溃。如果暂停删除后，内存会在十几秒内释放至正常水平。希望能处理下。

### ISSUE THREAD

**Issue by yang317621308** [Hufe921/canvas-editor#655]
### version

当前最新版本

### Steps to reproduce

文本框中，复制进入大量的文字后，点击删除键盘快速删除，会导致内存急剧飙升。页面卡顿，在老旧机器上会直接导致页面崩溃。如果暂停删除后，内存会在十几秒内释放至正常水平。希望能处理下。

### What is expected?

希望能处理一下，谢谢。

### What is actually happening?

患者诉胸闷、气短、头晕较前明显减轻，食纳尚可，夜休一般，二便如常。查体：BP：141/85mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率72次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。辅助检查：血常规、凝血功能、心损未见明显异常。徐多思主治医师查看患者后示：1、根据患者症状、体征及相关辅助检查，目前诊断冠心病成立，给予氯吡格雷抗血小板聚集、阿托伐他汀钙调脂稳斑、单硝酸异山梨脂等治疗。2、患者既往患有高血压病史，给予川芎嗪改善脑供血不足，替米沙坦控制血压。3、患者既往患有糖尿病病史，给予口服达格列净、阿卡波糖控制血糖。遵嘱执行。
                               医师签名：        徐多思/       白阳辉
2024-06-05                徐多思主任查房记录
    患者诉胸闷、气短、头晕较前明显减轻，食纳尚可，夜休一般，二便如常。查体：BP：138/80mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率75次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。辅助检查：胸片：心影增大；双肺实质未见明显病变。心脏超声：左方、左室增大，室间隔增厚；节段性室壁运动异常；左室收缩功能正常范围；左室顺应性减低。腹部超声：脂肪肝。心电图：1、窦性心律；2、心电轴不偏；3、异常ST-T改变；4、左心室高电压（左心室大可能）。糖化血红蛋白：6.7mmol/L。同型半胱氨酸：37.9umol/L。高血压五项、甲功八项、心肌酶谱未见明显异常。徐多思主任查看患者后示：患者目前血糖控制稳定，继续目前治疗方案。
                               医师签名：        徐多思/       白阳辉
2024-06-08                  徐多思主任查房记录
    患者诉胸闷、气短、头晕较前明显好转，食纳尚可，夜休尚可，二便如常。查体：BP：135/80mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率71次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。辅助检查：24小时：收缩压偏高，舒张压正常（155/64mmHg）；白天：收缩压偏高，舒张压正常（157/66mmHg）；夜间：收缩压偏高，舒张压正常（148/60mmHg）。动态心电图：室性早搏（单发、二联律），室上性早搏（单发、成对），ST-T改变，左心室高电压。患者症状好转，请示徐多思主任，予以出院。出院嘱：1、畅情志、适劳逸；2、定期监测血压、血糖，按时口服药物治疗；3、不适随诊。
                                医师签名：        徐多思/       白阳辉
2024-06-09                    出院小结
    患者以“间断胸闷、气短30年余，加重伴头晕1天”之主诉入院。患者诉30年前无明显诱因出现胸闷、气短，就诊于外院，诊断“冠心病”，出院后给予长期口服氯吡格雷、阿托伐他汀钙、单硝酸异山梨酯片。此后，上述症状间断发作，无咳嗽、咳痰，无恶心、呕吐，无肩背部抽痛。1天前上述症状再次发作，伴有头晕，就诊于我院，门诊以“高血压病、冠心病”收住入院。自发病以来，神志清，精神尚可，食纳尚可，夜休尚可，二便如常。查体：T：36.2℃ P：69次/分 R：19次/分 BP：143/85mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率69次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。（2024-05-30 外院）心电图：1、窦性心律，2、心电轴不偏，3、异常ST-T改变，4、左心室高电压（左心室大可能）。入院诊断：1、冠状动脉粥样硬化性心脏病 不稳定型心绞痛 心功能II级；2、高血压3级（很高危）；3、2型糖尿病。入院后完善血常规、凝血功能、心损、高血压五项、甲功八项、心肌酶谱未见明显异常。胸片：心影增大；双肺实质未见明显病变。心脏超声：左方、左室增大，室间隔增厚；节段性室壁运动异常；左室收缩功能正常范围；左室顺应性减低。腹部超声：脂肪肝。心电图：1、窦性心律；2、心电轴不偏；3、异常ST-T改变；4、左心室高电压（左心室大可能）。糖化血红蛋白：6.7mmol/L。同型半胱氨酸：37.9umol/L。24小时：收缩压偏高，舒张压正常（155/64mmHg）；白天：收缩压偏高，舒张压正常（157/66mmHg）；夜间：收缩压偏高，舒张压正常（148/60mmHg）。动态心电图：室性早搏（单发、二联律），室上性早搏（单发、成对），ST-T改变，左心室高电压。入院后给予改善循环，营养心肌，调控血压、调控血糖、抗血小板聚集、调脂稳斑，对症支持等治疗。出院情况：患者诉胸闷、气短、头晕较前明显好转，食纳尚可，夜休尚可，二便如常。查体：BP：135/80mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率71次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。出院诊断：1、不稳定型心绞痛 冠状动脉粥样硬化性心脏病 心功能Ⅱ级(NYHA分级)；2、高血压3级（很高危）；3、2型糖尿病；4、颈动脉硬化。出院嘱：1、畅情志、适劳逸；2、定期监测血压、血糖，按时口服药物治疗；3、不适随诊。患者以“间断胸闷、气短30年余，加重伴头晕1天”之主诉入院。患者诉30年前无明显诱因出现胸闷、气短，就诊于外院，诊断“冠心病”，出院后给予长期口服氯吡格雷、阿托伐他汀钙、单硝酸异山梨酯片。此后，上述症状间断发作，无咳嗽、咳痰，无恶心、呕吐，无肩背部抽痛。1天前上述症状再次发作，伴有头晕，就诊于我院，门诊以“高血压病、冠心病”收住入院。自发病以来，神志清，精神尚可，食纳尚可，夜休尚可，二便如常。查体：T：36.2℃ P：69次/分 R：19次/分 BP：143/85mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率69次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。（2024-05-30 外院）心电图：1、窦性心律，2、心电轴不偏，3、异常ST-T改变，4、左心室高电压（左心室大可能）。入院诊断：1、冠状动脉粥样硬化性心脏病 不稳定型心绞痛 心功能II级；2、高血压3级（很高危）；3、2型糖尿病。入院后完善血常规、凝血功能、心损、高血压五项、甲功八项、心肌酶谱未见明显异常。胸片：心影增大；双肺实质未见明显病变。心脏超声：左方、左室增大，室间隔增厚；节段性室壁运动异常；左室收缩功能正常范围；左室顺应性减低。腹部超声：脂肪肝。心电图：1、窦性心律；2、心电轴不偏；3、异常ST-T改变；4、左心室高电压（左心室大可能）。糖化血红蛋白：6.7mmol/L。同型半胱氨酸：37.9umol/L。24小时：收缩压偏高，舒张压正常（155/64mmHg）；白天：收缩压偏高，舒张压正常（157/66mmHg）；夜间：收缩压偏高，舒张压正常（148/60mmHg）。动态心电图：室性早搏（单发、二联律），室上性早搏（单发、成对），ST-T改变，左心室高电压。入院后给予改善循环，营养心肌，调控血压、调控血糖、抗血小板聚集、调脂稳斑，对症支持等治疗。出院情况：患者诉胸闷、气短、头晕较前明显好转，食纳尚可，夜休尚可，二便如常。查体：BP：135/80mmHg。神志清晰，查体合作，全身浅表淋巴结无肿大，颈软，气管居中，双侧甲状腺无肿大。胸廓正常，呼吸音清音，未闻及干湿啰音，心率71次/分，节律齐，心音正常，无杂音。腹部平软、无压痛及反跳痛。脊柱及四肢关节活动正常，双下肢无浮肿。生理反射存在，病理反射未引出。出院诊断：1、不稳定型心绞痛 冠状动脉粥样硬化性心脏病 心功能Ⅱ级(NYHA分级)；2、高血压3级（很高危）；3、2型糖尿病；4、颈动脉硬化。出院嘱：1、畅情志、适劳逸；2、定期监测血压、血糖，按时口服药物治疗；3、不适随诊。

测试用数据。

**Comment by Hufe921** [comment]
复制大量文字又一个一个删除的场景是什么？直接选区删除不行？

短时间内大量删除操作时编辑器有计算内存消耗和重新渲染逻辑，内存回落在合理范围，暂不更改。
