### ISSUE TITLE
分页显示bug

### ISSUE THREAD

**Issue by yang317621308** [Hufe921/canvas-editor#657]
### version

最新

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/33524998/51ae7538-f045-442d-9428-02dfcb700a43)
如上图，有类似的模版，给中间测试控件中复制进文字后，因文字过多。一页显示不下，table中的第二行会换至第二页，第一列独占第一页。
![image](https://github.com/Hufe921/canvas-editor/assets/33524998/6573c879-fded-42fa-95ec-8a446576ab26)
![image](https://github.com/Hufe921/canvas-editor/assets/33524998/f6bff1d9-7cba-4723-a63a-9eeecade45a5)
![image](https://github.com/Hufe921/canvas-editor/assets/33524998/f0d084c5-d6ae-4ce9-833e-da1172c8afb8)
第二页显示不完的数据也并未分页

### What is expected?

希望能正常分页显示。

### What is actually happening?

希望能正常分页显示。

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/41
