### ISSUE TITLE
设置控件默认样式属性executeSetControlProperties不生效

### ISSUE THREAD

**Issue by 2206487433** [Hufe921/canvas-editor#658]
### version

0.9.83

### Steps to reproduce

![image](https://github.com/Hufe921/canvas-editor/assets/39872057/6b265553-ea27-4040-ba1a-00ccc1dd4526)
修改代码后生效
![image](https://github.com/Hufe921/canvas-editor/assets/39872057/3e1c56f6-b4f9-4417-ac39-e010a85c59a7)
没怎么看代码，只是简单修改，希望作者修复一下这个问题

### What is expected?

![image](https://github.com/Hufe921/canvas-editor/assets/39872057/1d14c610-b804-4977-a6f2-83adf26f64d8)
点击控件属性修改
![image](https://github.com/Hufe921/canvas-editor/assets/39872057/a5f54f46-a3aa-4d56-9e11-2bbd0da9f827)

### What is actually happening?

-）（-

**Comment by Hufe921** [comment]
无法复现
