### ISSUE TITLE
希望能够提供一个api，设置文档光标位置

### ISSUE THREAD

**Issue by wusanmao23333** [Hufe921/canvas-editor#659]
### What problem does this feature solve?

扩展使用自定义 markdown 插件,  文档失去焦点，找不到光标所在位置，直接继续回车会报错。希望执行完自定义插件之后，调用api, 能够聚焦，继续编辑。

### What does the proposed API look like?

api可以设置光标具体的位置，开始位置，结尾位置，或者其他，默认为结尾的位置。

**Comment by Hufe921** [comment]
你写的这个插件是将markdown转成编辑器的数据结构，然后插入编辑器吗

**Comment by wusanmao23333** [comment]
我是在编辑文档回车的时候，获取到文档 main 的数据，使用正则生成文档渲染的数据格式，在数据都处理好了之后，使用 executeSetValue 命令，重新渲染文档。不知道这个方案是否合适，是想模拟 markdown 编辑的方式，实时编辑文档实时渲染，或者您有什么更好的实现方案？
