### ISSUE TITLE
是否支持医学表达式

### ISSUE THREAD

**Issue by xeg369** [Hufe921/canvas-editor#660]
### What problem does this feature solve?

能否支持医学表达式   比如月经史 

### What does the proposed API look like?

能否支持医学表达式   比如月经史

**Comment by Hufe921** [comment]
暂不支持。可以自己写一个插件如：
1. 写一个月经史弹窗
2. 输入信息之后转换成图片（svg、png、jpg等）
3. 使用executeInsertElementList插入图片并可以把信息附加到extension字段用于二次编辑

**Comment by xeg369** [comment]
我研究一下

**Comment by tiyunchen** [comment]
> 我研究一下

有研究怎么实现吗？我在困惑如何劫持图片预览的事件

**Comment by xeg369** [comment]
事情有点多，搁置了，等过一段时间忙完我研究一下

&nbsp;


1048695252
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2025年4月10日(星期四) 晚上7:27
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [Hufe921/canvas-editor] 是否支持医学表达式 (Issue #660)












    
我研究一下
  
有研究怎么实现吗？我在困惑如何劫持图片预览的事件

—
Reply to this email directly, view it on GitHub, or unsubscribe.
You are receiving this because you authored the thread.Message ID: ***@***.***&gt;
  tiyunchen left a comment (Hufe921/canvas-editor#660)
  
我研究一下
  
有研究怎么实现吗？我在困惑如何劫持图片预览的事件
