### ISSUE TITLE
表单模式下的编辑限制优化

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#662]
### version

0.9.83

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

1. 表单模式下，表格单元格可调整高度和宽度，重现步骤如下
       1）插入表格，并在任意单元格内插入文本控件
       2）将编辑器模式调整为表单模式
       3）在文本控件中输入内容，此时表格的辅助工具会显示，如下图，使用辅助工具就可以单元格的调整宽高了
![image](https://github.com/Hufe921/canvas-editor/assets/107550628/d49a2b57-5122-49bd-b4c7-0af99d99da16)

2. 表单模式下，图片可调整尺寸
       1）将编辑器模式调整为表单模式
       2）点击图片，此时辅助工具会显示，即可调整尺寸

### What is expected?

1. 表单模式下，表格单元格可调整高度和宽度
2. 表单模式下，图片可调整尺寸

### What is actually happening?

表单模式下，单元格和图片的尺寸不可调整

**Comment by winnerlxh** [comment]
这个问题解决了吗
