### ISSUE TITLE
老师，executeSetHTML 两次才能渲染图片

### ISSUE THREAD

**Issue by junceo** [Hufe921/canvas-editor#664]
### version

0.9.83

### Steps to reproduce

				let main = `<p>为台州市制造业原材料和其他产品提供了更加便捷的运输条件。</p>
			   <p><img src="data:image/png;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=" alt="" /></p>
			  <p> 临海东站物流仓储中心投运后，金台铁路货运功能进一步提升。浙江交通集团供图</p>`;
				this.editorCtx.command.executeSetHTML({
					main: main,
				})
				setTimeout(() => {
					this.editorCtx.command.executeSetHTML({
						main: main,
					})
				},10)

### What is expected?

				this.editorCtx.command.executeSetHTML({
					main: main,
				}) 

### What is actually happening?

需要两次executeSetHTML 编辑器中才会显示图片，拷贝进去一样。

### System Info

```shell
System:
    OS: macOS 14.5
    CPU: (11) arm64 Apple M3 Pro
    Memory: 126.73 MB / 18.00 GB
    Shell: 5.9 - /bin/zsh
  Binaries:
    Node: 22.2.0 - /opt/homebrew/bin/node
    npm: 10.7.0 - /opt/homebrew/bin/npm
    pnpm: 8.15.5 - /opt/homebrew/bin/pnpm
  Browsers:
    Chrome: 126.0.6478.114
    Safari: 17.5
```

### Any additional comments?

拷贝进去也一样，需要拷贝两次。

**Comment by Hufe921** [comment]
加一下width height
```html
  const text = `<p>为台州市制造业原材料和其他产品提供了更加便捷的运输条件。</p>
		   <p><img src="data:image/png;base64,R0lGODlhAQABAIAAAAUEBAAAACwAAAAAAQABAAACAkQBADs=" alt="" style="width:200px;height:200px;"/></p>
		  <p> 临海东站物流仓储中心投运后，金台铁路货运功能进一步提升。浙江交通集团供图</p>`
```
