### ISSUE TITLE
希望 watermark 的 options  可以扩展 repeat 的属性

### ISSUE THREAD

**Issue by wusanmao23333** [Hufe921/canvas-editor#665]
### What problem does this feature solve?

希望能够扩展 watermark 的 options 属性，能够实现文档多个水印，目前只是在文档的中间位置只有一个。

### What does the proposed API look like?

扩展的重复属性，值可以参考 background-repeat 的属性值

**Comment by the-lemonboy** [comment]
这个任务可以分配给我吗？
