### ISSUE TITLE
缩放比例(scale)调整后单词与标点断行(wordBreak)失效

### ISSUE THREAD

**Issue by JiaJunLee** [Hufe921/canvas-editor#666]
### version

0.9.79

### Steps to reproduce

1. 在任意行尾部输入英文内容
2. 调整缩放比例

![image](https://github.com/Hufe921/canvas-editor/assets/25827340/f905ee63-c25a-4203-a17c-7fc9fe5a8d9f)
![image](https://github.com/Hufe921/canvas-editor/assets/25827340/c1319b75-5694-4091-b48b-1782ff19d386)

### What is expected?

缩放比例变化时，wordBreak配置也应该生效

### What is actually happening?

文档中存在英文内容，用户缩放编辑器时，可能导致结尾单词被折行

**Comment by Hufe921** [comment]
wordBreak配置的什么

**Comment by JiaJunLee** [comment]
> wordBreak配置的什么

wordBreak: WordBreak.BREAK_WORD

**Comment by Hufe921** [comment]
无法复现，发一下系统信息，浏览器版本，屏幕分辨率，缩放比等

**Comment by JiaJunLee** [comment]
Reproduce:
https://codesandbox.io/p/sandbox/canvas-editor-word-break-bug-reproduce-lgwnpj

Local ENV:
BROWSER & OS: Chrome 126 on Windows 10
COMPUTER SCREEN: 1920 x 1080 Pixels
BROWSER WINDOW SIZE: 1920 x 1050 Pixels
