### ISSUE TITLE
宋体，缩放比例后，文字排版会错乱，光标位置也不正确

### ISSUE THREAD

**Issue by xiangyongjun** [Hufe921/canvas-editor#667]
### version

0.9.83

### Steps to reproduce

1.将字体设置为宋体
2.在文本控件输入符号中文数字等内容后
3.设置比例为110%
![微信图片_20240629154416](https://github.com/Hufe921/canvas-editor/assets/44317707/5ada47a4-9411-4f12-a5cc-61e694c13123)

### What is expected?

缩放比例后排版也应该正常

### What is actually happening?

宋体在缩放比例后排版错乱，光标错位

**Comment by Hufe921** [comment]
浏览器及版本信息发一下

**Comment by xiangyongjun** [comment]
> 浏览器及版本信息发一下

Microsoft Edge 126.0.2592.68 64位

**Comment by Hufe921** [comment]
设置编辑器渲染模式：
```
renderMode?: RenderMode // 渲染模式：极速（多个字组合渲染）、兼容（逐字渲染：避免浏览器字体等环境差异）。默认：极速
```

**Comment by xiangyongjun** [comment]
> 设置编辑器渲染模式：
> 
> ```
> renderMode?: RenderMode // 渲染模式：极速（多个字组合渲染）、兼容（逐字渲染：避免浏览器字体等环境差异）。默认：极速
> ```

大佬牛逼
