### ISSUE TITLE
OFD格式文件识别

### ISSUE THREAD

**Issue by zhaoxuanHome** [Hufe921/canvas-editor#668]
### What problem does this feature solve?

国内大量文件统一更改为OFD格式文件，不管是识别这种文件和生成这种格式文件。希望boss采取建议，
PDF互相转换OFD
WORD互相转换OFD

### What does the proposed API look like?

PDF互相转换OFD
WORD互相转换OFD
https://www.nbdaj.gov.cn/yw/bddt/202101/t20210113_34103.shtml

**Comment by Hufe921** [comment]
此仓库不考虑实现，可以编写插件自行完成OFD格式与编辑器数据结构的映射
