### ISSUE TITLE
executeSetControlHighlight 指令不生效

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#673]
### version

0.9.84

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

1、调用 getControlList 获取某个控件的 conceptId
2、调用 executeSetControlHighlight 设置控件高亮。
此时并不会生效，传入的参数如下图

![image](https://github.com/Hufe921/canvas-editor/assets/107550628/d2d65311-63de-4780-a2e2-10f60abc40f1)

### What is expected?

希望控件可以正常高亮

另外，是否可以继续优化，将 ruleList 作为可选的参数，仅需 conceptId 即可设置控件高亮，这样使用起来会更加方便

### What is actually happening?

控件没有高亮

**Comment by Hufe921** [comment]
其他补充  是背景提示文本，非输入内容

**Comment by junestars** [comment]
> 其他补充 是背景提示文本，非输入内容

即便是输入的内容也没有效果
![image](https://github.com/Hufe921/canvas-editor/assets/107550628/2e2eacfa-1c9f-469f-873d-e8eb50b8959b)
