### ISSUE TITLE
表单模式下控件相关 API 被禁用，无法使用

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#679]
### version

0.9.85

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

在表单模式下，setControlProperties、setControlExtension、setControlValue API 因为页面只读而无法调用

重现步骤
  1、将页面设置为表单模式
  2、调用上述三个 API

### What is expected?

希望 API 可以正常调用，特别是 setControlValue。

**使用场景**：当表单模式下，需要自动填充一些控件的值时，setControlValue API 不可或缺

### What is actually happening?

API 调用无效

**Comment by Hufe921** [comment]
表单模式下为什么会调用这几个属性

**Comment by junestars** [comment]
> 表单模式下为什么会调用这几个方法

表单模式下，如果能够自动填充一些控件的值会有更好的用户体验。

比如一些填序号的输入控件，一些需要填当天日期的日期控件
比如一些控件的值会受其它控件值的影响等

这些都需要 setControlValue 的支持
