### ISSUE TITLE
标题增加可禁用属性

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#680]
### What problem does this feature solve?

像控件加的这个两个属性就deleteable,disabled比较好控制。否则不能删除，但是可以编辑，这样就有问题了。谢谢
![)K%PHKX%~6{N_(6%`8I40LY](https://github.com/Hufe921/canvas-editor/assets/80032740/2f775d12-fc45-4d11-94b1-98623aaf9e24)
![E(IS0L`7VFX}Y(Q9~7D`4PK](https://github.com/Hufe921/canvas-editor/assets/80032740/c8590aad-e659-4c95-b5b3-4b399731972a)
![REX6)3GP}S)1)M4@20(GUQN](https://github.com/Hufe921/canvas-editor/assets/80032740/0615d42c-16ad-4ea0-9d3d-4a8a52cf624a)

### What does the proposed API look like?

如上

**Comment by bettersoft123** [comment]
![)K%PHKX%~6{N_(6%`8I40LY](https://github.com/Hufe921/canvas-editor/assets/80032740/2fa6f581-f81b-49ee-9a3e-f4b66aeebdac)

**Comment by bettersoft123** [comment]
顺带把draw.ts也改下，我改了个地方，就是高亮的地方，否则每次都要改。谢谢。
![PHA}3D`_A5@U@(@R@TTC5%C](https://github.com/Hufe921/canvas-editor/assets/80032740/7afe485b-b4d9-4ec8-85e9-888bd288ce4a)

**Comment by Hufe921** [comment]
> 顺带把draw.ts也改下，我改了个地方，就是高亮的地方，否则每次都要改。谢谢。 ![PHA}3D`_A5@U@(@R@TTC5%C](https://private-user-images.githubusercontent.com/80032740/346496701-7afe485b-b4d9-4ec8-85e9-888bd288ce4a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA0MzgwMDAsIm5iZiI6MTcyMDQzNzcwMCwicGF0aCI6Ii84MDAzMjc0MC8zNDY0OTY3MDEtN2FmZTQ4NWItYjRkOS00ZWM4LTg1ZTktODg4YmQyODhjZTRhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA4VDExMjE0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE5ZTExN2ZjODZhMmNjZTIwMTViMTY2ZDA3Mjc2MTU2MTZiZTM1MTJhYWE5YWY0NGYxNWVkZjA1YWFhMTdiM2EmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.gp48KBTkzPnEO_8kRM-Wn7AlhSb1Gp-NwIJKTF8_Xx4)

这个什么意思

**Comment by bettersoft123** [comment]
就是在高亮选择时，每行选中的时候，行间距保留一点间距。
