### ISSUE TITLE
mac中文输入相关问题

### ISSUE THREAD

**Issue by fionazs** [Hufe921/canvas-editor#681]
### version

-

### Steps to reproduce

![微信图片_20240708174009](https://github.com/Hufe921/canvas-editor/assets/117974868/6474543e-31b5-4355-92cc-87fae1d05aa2)
你好，
1：在mac系统下，连续输入两个中文标点后，再输入中文，光标展示如此，定位不正确。
2：在safari浏览器中，无法输入中文

### What is expected?

-

### What is actually happening?

-

### System Info

```shell
-
```

### Any additional comments?

-

**Comment by Hufe921** [comment]
使用兼容模式：https://github.com/Hufe921/canvas-editor/issues/667
