### ISSUE TITLE
嵌套表格的渲染异常问题

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#684]
### version

0.9.85

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

方式1
    在单元格内插入一个表格

方式2
    复制表格行，并在单元格内粘贴

效果如下图

![image](https://github.com/Hufe921/canvas-editor/assets/107550628/50454284-5c1e-4142-b1a0-48c6daa536d6)

### What is expected?

嵌套表格可以正常的渲染，或者禁止表格嵌套

### What is actually happening?

表格嵌套渲染异常

**Comment by Hufe921** [comment]
暂不支持，重复：https://github.com/Hufe921/canvas-editor/issues/650
