### ISSUE TITLE
executeUpdateElementById方法不生效

### ISSUE THREAD

**Issue by paddingC** [Hufe921/canvas-editor#689]
### version

0.9.85

### Steps to reproduce

instance.command.executeUpdateElementById({
              id: catalogItem.id,
              properties: {
                value: value
              }
})

### What is expected?

调用方法正常返回内容

### What is actually happening?

<img width="641" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/28521120/6ac037a4-433d-4d7b-af37-ac80b30101ba">
if里面判断条件应该有误，
<img width="846" alt="image" src="https://github.com/Hufe921/canvas-editor/assets/28521120/77c41284-87ea-4b1c-86a5-40d0ce9bfe74">
而且在外部更改对应id内容是也存在bug，只能替换寻找到的第一条信息，后面同样的id信息就会多余，无法处理

**Comment by Hufe921** [comment]
没有id的元素不支持修改
