### ISSUE TITLE
表单模式下，控件可以被删除

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#690]
### version

0.9.85

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

1、插入一个无值输入控件
2、将光标放在控件内
3、按下 Backspace 键

### What is expected?

应该不触发删除操作

### What is actually happening?

控件被删除了

**Comment by Hufe921** [comment]
控件支持不可删除deletable
