### ISSUE TITLE
希望可以添加自定义字段

### ISSUE THREAD

**Issue by towyears** [Hufe921/canvas-editor#698]
### What problem does this feature solve?

希望可以添加自定义字段.就是配置打印模版,然后读取配置,根据自定义字段渲染数据打印

### What does the proposed API look like?

no

**Comment by towyears** [comment]
![Uploading 微信截图_20240717095549.png…]()

**Comment by towyears** [comment]
![微信截图_20240717095549](https://github.com/user-attachments/assets/7549cd18-42aa-4b47-9835-501aff1b2e42)

**Comment by Hufe921** [comment]
元素上可以使用extension字段
