### ISSUE TITLE
增加获取表格id的方法

### ISSUE THREAD

**Issue by Tiny-Dong** [Hufe921/canvas-editor#699]
### What problem does this feature solve?
能否支持表格选选区置时 也可以绘制光标效果

![20240717122823_rec_](https://github.com/user-attachments/assets/bf2b0fe0-bfcd-4661-a135-e3bbab0a768f)

### What does the proposed API look like?

能否支持表格选选区置时 也可以绘制光标效果

**Comment by Hufe921** [comment]
需要设置上下文信息：executeSetPositionContext

**Comment by Tiny-Dong** [comment]
> 需要设置上下文信息：executeSetPositionContext

![20240718093422_rec_](https://github.com/user-attachments/assets/b8bcf424-d99d-410a-b2c4-9749607ab9d2)

@Hufe921 
executeSetRange 和 executeSetPositionContext 设置后 光标不会自动渲染  需要重新render
