### ISSUE TITLE
设置控件id滚动无效

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#700]
### version

0.9.86

### Steps to reproduce

#592 
设置controlId无效，重新将controlId赋值
![image](https://github.com/user-attachments/assets/229a1588-13a3-47a2-b16d-af0dcb4a709c)

### What is expected?

控件能传入controlId

### What is actually happening?

controlId设置无效

**Comment by Hufe921** [comment]
接口调用是否由事件（如点击）触发

**Comment by zhuyihe** [comment]
> 接口调用是否由事件（如点击）触发

对，由点击事件触发
![image](https://github.com/user-attachments/assets/eac22d96-457f-4325-b27e-cc67a019fbe5)

这边传入了controlId
![image](https://github.com/user-attachments/assets/4141db16-d35d-424c-b4f0-94874ce23de3)

但是在渲染文字的时候将控件拆分，controlId又随机生成了，导致无法定位
![image](https://github.com/user-attachments/assets/638dc650-4b5a-4b7d-ae65-a98817f95cb0)

**Comment by Hufe921** [comment]
通过getControlList或getValue获取内部控件id后再执行定位

**Comment by zhuyihe** [comment]
> 通过getControlList或getValue获取内部控件id后再执行定位

不能主动设置吗？比如我要传入固定的id
