### ISSUE TITLE
关于导入word文档的优化

### ISSUE THREAD

**Issue by paddingC** [Hufe921/canvas-editor#701]
### What problem does this feature solve?

采用官方提供的导入插件会导致样式丢失，自己用docx-preview导入然后解析出html内容，会还原原word样式，如图
![4231721217721_ pic](https://github.com/user-attachments/assets/62263789-afac-4e2f-8c41-e455e2b9d825)
但是表格的渲染会有点问题，如
<img width="1390" alt="image" src="https://github.com/user-attachments/assets/ed5822df-2513-4a30-b674-537fcfb18447">

![4211721217560_ pic](https://github.com/user-attachments/assets/9f0ee4e3-2110-4d9f-8a60-109fdb6e54fd)
作者大佬可以优化下吗

### What does the proposed API look like?

希望可以正常渲染表格

**Comment by Hufe921** [comment]
在插件项目（ https://github.com/Hufe921/canvas-editor-plugin ） 提issue或自行维护插件。
