### ISSUE TITLE
这个能不能支持像office word那样，相邻的中文标点符号宽度减小，最后一个标点符号宽度正常

### ISSUE THREAD

**Issue by wufan-vvf** [Hufe921/canvas-editor#702]
### What problem does this feature solve?

比如有多个！的时候，太分散了 不太好看

### What does the proposed API look like?

![image](https://github.com/user-attachments/assets/4d25e063-c2df-486d-8ce6-0fe2e5ee0aa3)

**Comment by Hufe921** [comment]
重复关闭：https://github.com/Hufe921/canvas-editor/issues/692
