### ISSUE TITLE
文档留痕

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#705]
### What problem does this feature solve?

用canvas-editor 做电子病历，如何处理文档留痕？有什么思路吗?比如可以看到谁修改的文档，修改了那些内容，那些被删除了，那些修改的，那些新增的等，包括修改时间，修改人等。如果用前后文档比较的方法，感觉比较费事。谢谢。

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/312
