### ISSUE TITLE
移动端H5上键盘弹出问题

### ISSUE THREAD

**Issue by dengxiujun** [Hufe921/canvas-editor#708]
### version

v0.9.85

### Steps to reproduce

在手机h5上使用只读模式的情况下，目录定位正文会出现

### What is expected?

能否在切换目录定位正文的时候，键盘不要弹出

### What is actually happening?

在手机h5上使用只读模式的情况下，点击目录定位正文时会导致输入法键盘弹出。

**Comment by Hufe921** [comment]
目录仅为功能演示。移动端暂不考虑

**Comment by dengxiujun** [comment]
> 目录仅为功能演示。移动端暂不考虑

好的，感谢大佬
