### ISSUE TITLE
文档内容过大会导致移动端H5崩溃问题

### ISSUE THREAD

**Issue by dengxiujun** [Hufe921/canvas-editor#709]
### version

v0.9.85

### Steps to reproduce

文档内容过大会导致移动端H5崩溃问题

### What is expected?

期望移动端不崩溃

### What is actually happening?

文档内容过大，然后打开一段时间就会崩溃

**Comment by Hufe921** [comment]
移动端暂不考虑文档内容过大性能问题

**Comment by dengxiujun** [comment]
好的，感谢大佬
