### ISSUE TITLE
Can I submit a touch suport PR for the signature component?

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#710]
### What problem does this feature solve?

Today the signature component doesn't work on mobile, and I needed to handle this for my use case.

There are 3 small functions, nothing too extensive and complex.

### What does the proposed API look like?

I implemented the handling for the ontouchmove, ontouchstart and ontouchend events.

**Comment by Hufe921** [comment]
Sure, use the prefix 'demo: ' for git message
