### ISSUE TITLE
单元格框线设置优化

### ISSUE THREAD

**Issue by MayIsACat** [Hufe921/canvas-editor#714]
### version

v0.9.86

### Steps to reproduce

通过上面工具栏来创建表格A、B、C、D等表格
![表格33](https://github.com/user-attachments/assets/50dbad1c-1ef6-4031-9d3b-44fa6a653d4b)

### What is expected?

拼接表格的地方，重合部分的边框线不会重复渲染，只需要渲染一次

### What is actually happening?

有时候两个表格的边框线都渲染了，造成边框线变粗变黑，很突兀，有时候又是正常的，
正常的如下图一，下面是两个表格拼接的：
![表格AB](https://github.com/user-attachments/assets/f39c8abf-08c3-4c7f-8578-112750c22dc8)
有时候又不正常，如图二：
![表格2](https://github.com/user-attachments/assets/a15a1961-b0c8-444d-8c4e-f15f59a21ebf)

**Comment by Hufe921** [comment]
提供一下getValue后的数据，及系统信息

**Comment by wangfeng0811** [comment]
> 提供一下getValue后的数据，及系统信息
**这是getValue的信息**
[result.json](https://github.com/user-attachments/files/16410871/result.json)
我这个操作流程是为了**到达设置每个单元格的列宽不等的目的**（看了已有代码和issues，现在版本还不支持单独拖拽单元格框线来调整高度和宽度），这种操作似乎也是不大对的：
**1、想要的操作顺序是：**
右键表格-->表格边框-->单元格边框-->点击上边框/下边框/左边框/右边框，直接实现**选中区域的单元格**上边框/下边框/左边框/右边框的**显示或不显示**，像wps的表格设置边框一样
**2、现在的操作顺序是：**
需要先点一下右键表格-->表格边框-->无框线，然后再去一个一个点单元格来配置框线（这种流程让之前配置好的单元格失去边框了，需要又返回重新一个一个配置框线，很麻烦）
**目前还尝试过的思路是：**
在下图一文件代码采用方案A（注释掉方案B，其他边框也采用这个思路），也能清除上边框线如图二，但是在页面缩放之后会出现一条很细的线（是拖拽线吗？）如图三：
图一：
![zzzzzzzzz](https://github.com/user-attachments/assets/00666262-39c2-431a-ac14-a19f3f3c67b9)
图二：
![aaa](https://github.com/user-attachments/assets/b6bbf158-a232-4668-8024-dccc0b0ff705)
图三：
![bbbb](https://github.com/user-attachments/assets/8b5bf92e-a26c-4655-8b83-9abb6d5a9811)
**求助：**
大佬能否提供下实现给选中单元格区域拖拽设置宽度和高度，或者直接右键表格-->表格边框-->单元格边框-->点击上边框/下边框/左边框/右边框来实现选中单元格上边框或其他边框显示与否，不用必须先点无框线

**Comment by Hufe921** [comment]
rowMargin 可以设置更小一点试试

表格框线问题确实可以优化一下

**Comment by wangfeng0811** [comment]
> rowMargin 可以设置更小一点试试
> 
> 表格框线问题确实可以优化一下

嗯啊，rowMargin设置为更小的0.01，能达到效果，曲线救国了，感谢大佬！期待后面表格框线变得更完善！
