### ISSUE TITLE
是否可以在executeSetValue中可配置光标始终在末尾闪烁

### ISSUE THREAD

**Issue by lonlygods** [Hufe921/canvas-editor#715]
### What problem does this feature solve?

根据SSE推送数据实时更新executeSetValue时模拟打字机效果

### What does the proposed API look like?

executeSetValue({ main: main, cursorBlink: true })
或
executeCursorBlink()

**Comment by Hufe921** [comment]
在新版本发布之前，可以使用executeAppendElementList方法

**Comment by lonlygods** [comment]
> cursorBlink

完美解决！感谢大佬
