### ISSUE TITLE
页眉页脚内容编辑

### ISSUE THREAD

**Issue by lp123114** [Hufe921/canvas-editor#72]
页眉页脚内容编辑功能，有没有计划？
有没有实现的思路？
方便留个邮箱或者微信吗？想交流一下

**Comment by Hufe921** [comment]
编辑器还处于开发阶段，页眉页脚可编辑，表格分页功能还在完善，可以继续关注。
思路：重新划分编辑器区域（页眉，页脚，主内容区），通过区域标识编写逻辑

**Comment by Hufe921** [comment]
已实现，见最新版本
