### ISSUE TITLE
点击自定义的工具栏，编辑面板会失焦

### ISSUE THREAD

**Issue by gy9527** [Hufe921/canvas-editor#721]
请教大佬
我自己参考demo实现了一个工具栏，但点击时，编辑面板会失焦。
我试用demo不会失焦，然后看了文档和代码，没找到是怎么实现的。
希望大佬指点一下，麻烦你了

**Comment by cosmoscatts** [comment]
我也遇到了这个问题，请问解决了吗？

**Comment by zhoujingfu** [comment]
> 我也遇到了这个问题，请问解决了吗？

元素增加 EDITOR_COMPONENT 标识

**Comment by cosmoscatts** [comment]
> > 我也遇到了这个问题，请问解决了吗？
> 
> 元素增加 EDITOR_COMPONENT 标识

解决了，谢谢！
