### ISSUE TITLE
导出word文档

### ISSUE THREAD

**Issue by lonlygods** [Hufe921/canvas-editor#723]
### What problem does this feature solve?

是否可以导出正确的word文档

### What does the proposed API look like?

当前官方维护的中间件导出的文档样式全部丢失，有什么别的方法可以解决这个问题吗

**Comment by Hufe921** [comment]
不要在此仓库提插件问题。
如插件不具有你想要的效果，暂时可以拿到编辑器的数据后，自行实现。
