### ISSUE TITLE
从word中粘贴带上下标文本格式问题

### ISSUE THREAD

**Issue by liaojiankkk** [Hufe921/canvas-editor#726]
### version

0.9.86

### Steps to reproduce

当上标或下标的字体大小或格式和原文本不一致时，上下标样式就会失效

### What is expected?

![11](https://github.com/user-attachments/assets/9239559d-87dc-4b4a-a673-808dc982f435)

### What is actually happening?

![22](https://github.com/user-attachments/assets/ef597926-329c-4d6c-996d-9475d26987ad)

**Comment by Hufe921** [comment]
编辑器样式无法准确还原word样式
