### ISSUE TITLE
希望添加背景图时能精准控制在哪一页

### ISSUE THREAD

**Issue by goodboy-yes** [Hufe921/canvas-editor#729]
### What problem does this feature solve?

希望添加背景图时能精准控制在哪一页，应用场景是添加封面，只在首页展示背景图

### What does the proposed API look like?

interface IBackgroundOption {
  color?: string
  image?: string
  size?: BackgroundSize
  repeat?: BackgroundRepeat
// 添加类似pageNo的传参
}

**Comment by Hufe921** [comment]
增加配置
```
background?: IBackgroundOption // 背景配置。{applyPageNumbers?:number[]} // 适用页码从0开始
```
