### ISSUE TITLE
表格列数很多的时候，纸张方向为横向时正常排版，切换为纵向排版的时候表格宽度错误渲染·

### ISSUE THREAD

**Issue by wangfeng0811** [Hufe921/canvas-editor#730]
### version

v0.9.86

### Steps to reproduce

纸张方向为横向时，插入一个列数很多的表格，然后切换为纵向排版

### What is expected?

切换为纵向排版时表格能正常渲染

### What is actually happening?

纵向排版时表格宽度错误渲染：
![111](https://github.com/user-attachments/assets/6c90a196-8eb7-43f4-bbc0-62ea1b338e3a)

**Comment by Hufe921** [comment]
插入时表格宽度已定
