### ISSUE TITLE
Implementing touch support for image resize

### ISSUE THREAD

**Issue by douglasmatheus** [Hufe921/canvas-editor#731]
### What problem does this feature solve?

I implemented the touchmove, touchstart and touchend events using the mousemove and mousedown functions already in the Previewer.ts class.

https://github.com/user-attachments/assets/87c3ca7d-c51c-413c-a23e-6e66074ca68d

### What does the proposed API look like?

Boss, would you like me to send a PR for this? If so, what prefix do I use, improvement?

**Comment by Hufe921** [comment]
Thank you, but the core library is not currently considering mobile adaptation
