### ISSUE TITLE
visiblePageNoListChange、pageSizeChange这两个监听异常，滚动时没有响应

### ISSUE THREAD

**Issue by jiangziy66** [Hufe921/canvas-editor#732]
### version

0.9.87

### Steps to reproduce

加载完成后，滑动滚动条时没有监听

### What is expected?

可见页面和当前页发生改变能够及时响应

### What is actually happening?

可见页面和当前页发生改变没有响应

**Comment by Hufe921** [comment]
无法复现，可以试试官网demo在你设备上是否正常，或提供一下最小可复现demo

**Comment by goodboy-yes** [comment]
如果你的编辑器滚动容器不是document，需要在[配置](https://hufe.club/canvas-editor-docs/guide/option.html)设置scrollContainerSelector参数，不然监听不到
