### ISSUE TITLE
Can CommentList and render add to the Draw?

### ISSUE THREAD

**Issue by justsxl** [Hufe921/canvas-editor#735]
### What problem does this feature solve?

Now the commentList is in Main.ts, Can it be used as a property of Draw.ts and render in Draw?

### What does the proposed API look like?

interface IComment {
  id: string
  content: string
  userName: string
  rangeText: string
  createdDate: string
}

export interface IEditorData {
  header?: IElement[]
  main: IElement[]
  footer?: IElement[]
  comm?: IComment[]
}

**Comment by Hufe921** [comment]
The comment feature is only implemented using the internal API of the editor and is not related to the core layer of the editor. Just refer to the demo and implement it yourself
