### ISSUE TITLE
点击控件时高亮处理

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#740]
### What problem does this feature solve?

在录入文档的时候，由于都是结构化，能否光标在当前元素或者鼠标点击的时候，把这个id对应的元素进行高亮显示，包括高亮颜色，是否高亮等可以自己配置？

### What does the proposed API look like?

如上

**Comment by Hufe921** [comment]
指的是点击控件的时候 高亮吧

**Comment by bettersoft123** [comment]
是的，点击其他控件时恢复正常。

**Comment by Hufe921** [comment]
使用示例：
```
control: {
    activeBackgroundColor: '#4dc2e754'
  },
```

**Comment by lgdzz** [comment]
> 使用示例：
> 
> ```
> control: {
>     activeBackgroundColor: '#4dc2e754'
>   },
> ```

增加了这个属性，点击控件没有高亮效果，版本:0.9.96
