### ISSUE TITLE
instance.command.getPositionContextByEvent(evt)返回的element.value不是元素的值。

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#741]
### version

0.9.77

### Steps to reproduce

instance.command.getPositionContextByEvent(evt)返回的当前位置的value,不是整个元素的值，这种返回数据没有意义。能否返回这个元素的全部内容？

### What is expected?

![微信图片_20240806103011](https://github.com/user-attachments/assets/0eba0b51-c15b-4c87-afc2-8c0ff372c4b6)

### What is actually happening?

如上

**Comment by Hufe921** [comment]
这里元素值为显示值，控件值可以通过`getControlValue`获取
