### ISSUE TITLE
三击选中段落时,无法输入文字进行修改

### ISSUE THREAD

**Issue by zjx-git** [Hufe921/canvas-editor#742]
### version

v0.9.88

### Steps to reproduce

![image](https://github.com/user-attachments/assets/81b29044-56b9-4375-bd51-bde16c259e59)
![image](https://github.com/user-attachments/assets/88fd5017-6547-4fb7-bce5-a720021f91aa)

main正文部分删掉,随便输入几个字,然后鼠标双击选中这些文字. 此时再输入没有任何反应, 并且有报错(这是官方在线的demo)

### What is expected?

希望双击选中文字时依然能正常输入修改文字

### What is actually happening?

无响应, 报错

**Comment by daria2023** [comment]
测试了一下是threeclick最后元素的时候，endindex计算问题导致的：
![image](https://github.com/user-attachments/assets/7e3aa776-89d7-4d3e-a68c-f91529029111)
这样简单修改暂时没有发现这个问题了。
