### ISSUE TITLE
能否增加控件嵌套功能

### ISSUE THREAD

**Issue by xuxuxu-ni** [Hufe921/canvas-editor#744]
### What problem does this feature solve?

文本输入控件里面需要嵌套文本控件,或者单选控件,目前不支持,后面能否支持

### What does the proposed API look like?

无

**Comment by Hufe921** [comment]
场景是什么

**Comment by xuxuxu-ni** [comment]
类似这样
<img width="1048" alt="image" src="https://github.com/user-attachments/assets/7bb772d2-5cec-4da6-adb3-9e1fee9333e7">

**Comment by Hufe921** [comment]
使用标题和控件解决，暂不考虑嵌套
