### ISSUE TITLE
希望增加自定义控件的功能、变量内容填充功能

### ISSUE THREAD

**Issue by willianfu** [Hufe921/canvas-editor#745]
## 非常感谢大佬提供这么棒的编辑器，相当哇塞！！
> 在使用时，想到几个需求，非常抱歉打扰大佬，如果后续能更新进去，应该会非常有应用场景😁😁

1、增加自定义控件功能，可以像插件一样添加控件，并能定义控件值正则校验规则或者校验函数，有一个表单取值函数。
2、增加模板变量功能，可以把这个编辑器编辑好模板，外部通过api传入变量进行自动填充，实现自定义报表打印或者文档打印，这个功能在很多场景下非常有用，比如使用表单填报，然后打印直接填充表单值做为变量，注入编辑器内回显。
3、基于上面的，变量可以固定位置，也可以全文任意位置防止，比如盖章和签名，在审批的场景下，上传电子签名和印章，自动把图片填充到变量上面，完成合同文件的盖章，这个也蛮有用的。

非要感谢作者在百忙之中开发了这么优的工具！！，希望大佬能建立一个微信/qq群，让大家可以相互交流探讨使用上的问题。

### What does the proposed API look like?

😁😁😁

**Comment by Hufe921** [comment]
扩展控件：
1. 复杂或与项目耦合较深的控件，只能提issue官方支持或fork代码后自行处理
2. 简单的控件或元素可以参考插件： [canvas-editor-plugin-diagram](https://github.com/Hufe921/canvas-editor-plugin/tree/main/packages/diagram) 的实现，通过编辑器api自行扩展

控件规则：
1. 重复：https://github.com/Hufe921/canvas-editor/issues/671

模板变量：
1. 可以使用控件进行模板的制作，并通过编辑器方法进行控件赋值
