### ISSUE TITLE
寻找通过文件夹拖拽图片的源码位置

### ISSUE THREAD

**Issue by LjySama0321** [Hufe921/canvas-editor#746]
我想问下大佬们 里面通过文件夹拖拽图片的源码在哪里 我的需求是通过旁边的图片组件拖拽图片到画布上 我在内容变更的方法里写 它会一直创建下一页 并在每一页放上那张图片 请问这个怎么解决

**Comment by LjySama0321** [comment]
请问拖拽的动作指令源码在哪里啊

**Comment by daria2023** [comment]
![image](https://github.com/user-attachments/assets/a7c80d54-e047-49aa-a146-157065e89889)
