### ISSUE TITLE
IElement元素属性中是否可以增加标题（caption）?

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#748]
### What problem does this feature solve?

在插入元素中，比如我要插入个形态的：变大，变小，正常三种状态，直接插入列表的内容，但是标题还要手工打。能否直接插入标题的时候，如果标题有赋值，可以把标题和列表一起插入进去？不改变元素本身的属性。谢谢

### What does the proposed API look like?

如上

**Comment by daria2023** [comment]
你自己包装一个方法，在list前面直接添加一个文本元素是比较简单快速的实现办法吧？

**Comment by Hufe921** [comment]
> 你自己包装一个方法，在list前面直接添加一个文本元素是比较简单快速的实现办法吧？

是的自己封装一个方法，在list前加标题元素即可
