### ISSUE TITLE
表格超出页面问题

### ISSUE THREAD

**Issue by Whiteyingshan** [Hufe921/canvas-editor#751]
### version

0.9.89

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

在相邻两个页面插入两个1*1的表格

### What is expected?

如果一个单元格一页写不完了，点击回车或者空格，自动往下走不跳转到下一页，而是在改页一直往下，超出边框了。同时这个模板的第一页就变为了空白
![微信截图_20240812090259](https://github.com/user-attachments/assets/619b3ea0-3c22-4ef6-bcab-f91157fefda5)

### What is actually happening?

word的解决方式是在这两页中间再添加一个1*1的表格，新内容在新表格中输入
![微信截图_20240812091228](https://github.com/user-attachments/assets/733d4457-a2a0-4678-8ccc-409b74b5c95b)

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/41
