### ISSUE TITLE
标题行

### ISSUE THREAD

**Issue by fionazs** [Hufe921/canvas-editor#752]
### What problem does this feature solve?

你好，请问能否首行增加标题行，默认显示占位文字‘请输入标题’。标题格式应用‘标题1’，标题行格式修改为‘正文’后，占位文字消失

### What does the proposed API look like?

1：首行增加标题行，默认显示占位文字‘请输入标题’，标题格式应用‘标题1’
2：标题行格式修改为‘正文’或输入标题文字或换行后，占位文字消失

**Comment by Hufe921** [comment]
可以使用文本控件控制。
