### ISSUE TITLE
executeMode 修改 mode 后，getOptions API 返回的数据中，mode 没有更新

### ISSUE THREAD

**Issue by junestars** [Hufe921/canvas-editor#755]
### version

0.9.88

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

1、调用 getOptions 获取当前的 mode
2、调用 executeMode 修改 mode
3、调用 getOptions 获取当前的 mode

### What is expected?

getOptions 获取到的 mode 是最新真实的值

### What is actually happening?

getOptions 获取到的 mode 仍然是修改前的值

**Comment by daria2023** [comment]
根据我的理解，getOptions获取到的是默认的编辑器配置项，executeMode中没有将options中的mode进行修改，所以你走getoptions获取到的就是初始值。Draw中有getMode方法，可以添加到command中。

**Comment by junestars** [comment]
> 根据我的理解，getOptions获取到的是默认的编辑器配置项，executeMode中没有将options中的mode进行修改，所以你走getoptions获取到的就是初始值。Draw中有getMode方法，可以添加到command中。

你好，感谢回答！

问题的核心正是 executeMode 中没有将 mode 更新到 options 上。Draw.options 与当前编辑器真正的 options 状态不一致，这可能会导致一系列的问题，比如 getValue API 返回的数据中，由于 options 直接取自 Draw.options，所以数据也可能是不真实的。options 没能及时更新，还会影响到源码中所用使用到 options 的做逻辑处理的地方。

另外，下面是此问题导致的一个 BUG

在源码中对 ‘options.mode’ 进行检索，会发现 .../core/contextmenu/menus 目录下的 controlMenus.js 和 tableMenus.js 有使用其进行逻辑判断，具体作用是在表单模式下，不显示控件删除和表格相关的右键菜单，但由于 options.mode 没能正确更新，相关逻辑没有正常生效。

上述 BUG 重现方法如下

1、在单元格中插入控件
2、切换为表单模式
3、左键点击控件使其激活，然后点击右键

会发现行列操作菜单、单元格操作菜单和控件删除菜单没能正确的隐藏

重现地址为[官方demo地址](https://hufe.club/canvas-editor/)，版本为 0.9.89

**Comment by junestars** [comment]
> 根据我的理解，getOptions获取到的是默认的编辑器配置项，executeMode中没有将options中的mode进行修改，所以你走getoptions获取到的就是初始值。Draw中有getMode方法，可以添加到command中。

你好，感谢回答！

问题的核心正是 executeMode 中没有将 mode 更新到 options 上。Draw.options 与当前编辑器真正的 options 状态不一致，这可能会导致一系列的问题，比如 getValue API 返回的数据中，由于 options 直接取自 Draw.options，所以数据也可能是不真实的。options 没能及时更新，还会影响到源码中所用使用到 options 的做逻辑处理的地方。

另外，下面是此问题导致的一个 BUG

在源码中对 ‘options.mode’ 进行检索，会发现 .../core/contextmenu/menus 目录下的 controlMenus.js 和 tableMenus.js 有使用其进行逻辑判断，具体作用是在表单模式下，不显示控件删除和表格相关的右键菜单，但由于 options.mode 没能正确更新，相关逻辑没有正常生效。

上述 BUG 重现方法如下

1、在单元格中插入控件
2、切换为表单模式
3、左键点击控件使其激活，然后点击右键

会发现行列操作菜单、单元格操作菜单和控件删除菜单没能正确的隐藏

重现地址为[官方demo地址](https://hufe.club/canvas-editor/)，版本为 0.9.89

**Comment by daria2023** [comment]
确实可以删除和对表格进行操作了，我的理解是在需要获取到editorMode的时候，走draw.getMode（）去获取，不要走options去获取，可以等等听听看hufe的回复。

**Comment by Hufe921** [comment]
getOptions是当前编辑器实例所有配置，此issue为bug

> 根据我的理解，getOptions获取到的是默认的编辑器配置项，executeMode中没有将options中的mode进行修改，所以你走getoptions获取到的就是初始值。Draw中有getMode方法，可以添加到command中。
