### ISSUE TITLE
希望能实现类似word的自动生成目录功能

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#757]
### What problem does this feature solve?

希望能实现类似word和wps的的自动生成目录功能如下图：
![2024-08-13_16-18](https://github.com/user-attachments/assets/16a72e18-5930-4b92-bd97-f96c2ce8029b)
![2024-08-13_16-19](https://github.com/user-attachments/assets/a661af10-1145-48bf-b21e-c1d4ef814cd7)

### What does the proposed API look like?

生成目录功能api

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/462
