### ISSUE TITLE
火狐浏览器打印多出一页空白

### ISSUE THREAD

**Issue by Whiteyingshan** [Hufe921/canvas-editor#760]
### version

0.9.89

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

火狐浏览器打印多出一页空白，火狐浏览器版本129.0.1 (64 位)，使用自适应页面宽度，未缩放

### What is expected?

![微信截图_20240815111152](https://github.com/user-attachments/assets/7a01e2e1-9d8c-49be-9362-923c5ac67edc)

### What is actually happening?

火狐浏览器正常打印显示

**Comment by daria2023** [comment]
搜了一下目前最快速的解决办法是这个，可以判断一下浏览器然后把高度减少一个像素看看管不管用 ![image](https://github.com/user-attachments/assets/3cac8e1d-da03-421c-a49c-1dbb025a2416)

**Comment by Whiteyingshan** [comment]
感谢群友的帮助，暂时解决方法是在printImageBase64判断是否是火狐浏览器，是的话高度就减少1像素，不过不清楚会不会引来其他问题
![image](https://github.com/user-attachments/assets/2a3d9e49-44bc-4b2e-b1d9-a8efe32a0e88)
