### ISSUE TITLE
控件监听的BUG

### ISSUE THREAD

**Issue by juqianzi** [Hufe921/canvas-editor#767]
### version

0.9.90

### Steps to reproduce

在页面中通过监听控件设置菜单的权限，点击控件禁用菜单栏某些功能，再点击非控件时菜单解除限制。
在上述的操作中发现，先点击image控件，再点击非控件时无法解除限制。

### What is expected?

先点击image控件，再点击非控件时可以解除限制

### What is actually happening?

进一步调试发现，点击text控件时payload有返回值，再点击非控件时返回值为null，但是先点击image控件（或者直接单击图片）时payload有返回值，再点击非控件时无返回值。在此，希望也能返回null，而不是无返回值或者监听失效。

**Comment by Hufe921** [comment]
无法复现，提供一下录屏进行演示

**Comment by juqianzi** [comment]
控件都设置成不可删除不可交互状态下出现的，明天给你录屏哈
