### ISSUE TITLE
CRDT问题

### ISSUE THREAD

**Issue by jimmyhuangjun** [Hufe921/canvas-editor#770]
### What problem does this feature solve?

你好，看到了你的特性中包括使用Yjs实现的CRDT功能，但是看了main.ts中的代码发现update监听后，是直接删除所有的数据，然后insertElementList实现的，效果不是非常好，请问有没有可能更好的实现CRDT这部分的功能。非常感谢

### What does the proposed API look like?

CRDT

**Comment by Hufe921** [comment]
暂时可以自行实现
