### ISSUE TITLE
希望实现分割线可删除或设置成透明功能

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#776]
### What problem does this feature solve?

希望实现分割线可删除或设置成透明功能，现在的分割线是设置了就办法去掉，偶尔添加错了想删除只有整个文件去掉重新加才行

### What does the proposed API look like?

希望实现分割线可删除或设置成透明功能

**Comment by daria2023** [comment]
分割线可以删除，操作光标移动到分割线后一个元素前面可以删除啊。透明色的话可以通过直接操作element.color设置为bgcolor来实现这个目的？

**Comment by liushuai05** [comment]
> 分割线可以删除，操作光标移动到分割线后一个元素前面可以删除啊。透明色的话可以通过直接操作element.color设置为bgcolor来实现这个目的？

噢噢 试了一下 确实是这样 之前没找到方法 感谢大佬回复
