### ISSUE TITLE
修改控件元素属性

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#780]
### version

0.9.90

### Steps to reproduce

1:用getPositionContextByEvent获取元素(为何text有id,control没有id?而是control->controlId? 所有元素id能统一吗？)
2:用executeUpdateElementById修改元素信息，不生效
后面跟踪源码发现：用element.id来比较传入的id,但是element.id在control类型中不存在。。。
3：如何获取到control的id,跟control->controlId一样吗？
4：到底如何修改所有的元素的属性？谢谢.
5:  id到底是官方内部自动产生，我们调用方法传入的？
6：是不是control修改只能用executeSetControlProperties？不能用executeUpdateElementById来修改控件属性?
谢谢
![QQ图片20240822164926](https://github.com/user-attachments/assets/3d1c2955-e30c-437d-baa3-a0df2d67e0ea)
![QQ图片20240822164942](https://github.com/user-attachments/assets/f902bdba-79bb-45c1-8377-c6fecb82cf27)
![QQ图片20240822164953](https://github.com/user-attachments/assets/5e0de219-03c6-4f74-8dd3-c4a3aff152ee)

### What is expected?

如上

### What is actually happening?

如上

**Comment by Hufe921** [comment]
id：是内部元素唯一键，目前有id的元素为：图片、块、Latex、表格，均为可独立渲染元素

controlId：是控件唯一键，是用来表示组成控件的元素（前缀后缀内容等）属于一个控件，也可以理解成组id。

修改元素：使用executeUpdateElementById
修改控件：使用含有control字符的api
