### ISSUE TITLE
表格首行会吞掉回车符

### ISSUE THREAD

**Issue by Whiteyingshan** [Hufe921/canvas-editor#784]
### version

0.9.90

### Steps to reproduce

![微信截图_20240823090256](https://github.com/user-attachments/assets/7548bbe3-0a28-41d5-8f22-f40c0089e4d3)

### What is expected?

第一列的1.和第二列的2.都被吞了一个回车符

### What is actually happening?

表格首行回车符正常显示

**Comment by Hufe921** [comment]
重复：#771
