### ISSUE TITLE
分割线导致内容高度发生变化

### ISSUE THREAD

**Issue by Whiteyingshan** [Hufe921/canvas-editor#786]
### version

0.9.90

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

增加分割线时，导致内容高度发生变化

### What is expected?

以下是不加分割线和加分割线的对比，页眉增加分割线后，第一页最后一行的文本被挤到第二页去了
![5](https://github.com/user-attachments/assets/f8fcbbf3-1bcb-453c-811a-2e6e2fc60858)
![6](https://github.com/user-attachments/assets/cf6c871b-0326-42e9-a4c1-42938680d6e4)

### What is actually happening?

0.9.69的时候分割线是不会影响内容高度
![3](https://github.com/user-attachments/assets/71c97f8d-5e24-482b-b837-e65ad1d128bd)
![4](https://github.com/user-attachments/assets/34484e78-d60b-4afb-9ce7-7425b86e7069)

**Comment by daria2023** [comment]
![image](https://github.com/user-attachments/assets/4cae5f0a-2f34-4b0b-9e4d-03cdff5f8cb5)
这个是为分割线增加了一个lineWidth配置项之后，这个高度需要计算进去，所以添加分割线内容会按照你添加的高度往下移，如果你没有这个需求，可以添加一个不要计算分割线的配置项。
