### ISSUE TITLE
executeInsertElementList插入元素的格式失效

### ISSUE THREAD

**Issue by lonlygods** [Hufe921/canvas-editor#787]
### version

4.4.0

### Steps to reproduce

使用executeInsertElementList插入元素 元素数据指定了rowFlex字段但不生效 尝试了executeAppendElementList追加元素的api没有这个问题

### What is expected?

希望更新一下这个问题或者是否有什么别的方法可以解决这个问题

### What is actually happening?

![image](https://github.com/user-attachments/assets/130010c4-21e7-4f7a-aaac-47320f750cf3)
![image](https://github.com/user-attachments/assets/03e19551-24cf-43ee-b6ab-f5db6608d1ae)

**Comment by Hufe921** [comment]
插入普通元素会以当前光标上下文进行行布局设置。
针对你这种情况可以插入后调用api：executeRowFlex实现

**Comment by lonlygods** [comment]
> 插入普通元素会以当前光标上下文进行行布局设置。 针对你这种情况可以插入后调用api：executeRowFlex实现

好的 感谢🙏 已经解决了
