### ISSUE TITLE
executeSetControlProperties只能更新文本第一个字符属性？？？

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#791]
### version

0.9.90

### Steps to reproduce

1：插入文本
  instance.command.executeInsertElementList([
              {
                type: ElementType.TEXT  ,
                value: value, 
                id: generateGUID(),                
                control: {
                  type : 'text',
                  conceptId: generateGUID(),
                  code: eleId,
                  placeholder: value,
                  deletable: deletable ,
                  value: value ,
                  extension: recordElementOtherProperties(elementData)
                }
              }
            ])
2：修改文本
    let payload= 
    {
    // id: emelentdata.emreleId,
     conceptId: emelentdata.eleId,
     properties: {
      deletable: true,
      extension: '12312312222'
     }    
    } 
    const result=instance1.value.command.executeSetControlProperties(payload)
3：执行结果
   只修改了一串文本第一个字符的属性。文本串conceptId都一样。

### What is expected?

如上

### What is actually happening?

官方答复：
executeSetControlProperties 支持使用控件内部id或conceptId进行属性修改。
编辑器有完整的ts类型定义，建议合理使用代码编辑器的代码提示功能。

export type ISetControlProperties = {
  id?: string
  conceptId?: string
  properties: Partial<Omit<IControl, 'value'>>
}

**Comment by daria2023** [comment]
测试了一下没有你说的只能更新第一个字符属性的问题，你的文本控件type为什么是text不是control

**Comment by bettersoft123** [comment]
![微信图片_20240827113523](https://github.com/user-attachments/assets/a69b6ca0-401d-4a5f-b422-93b377bd7d69)
1:我试了确实是这样，用control没问题，你用文本试试看。
2:我也想用control，用control->text的话前面有前后有括号，没法去除掉。我主要是做个标题+内容模式

**Comment by daria2023** [comment]
那你可以考虑隐藏前后缀
