### ISSUE TITLE
希望能添加一个类似LaTex的无法直接修改文字控件原样显示文本功能或者api也行

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#793]
### What problem does this feature solve?

希望能添加一个类似LaTex的无法直接修改文字控件功能或者api也行，我们这边目前有一个项目需要先实现文件模板集（里面需要添加一些类似变量的字符串不允许用修改那种，我测试发现LaTex非常类似我们想要的功能，但是无赖的是LaTex有计算公式，比如字符串 {这里是需要替换的文档类型-2-这里是文档名称}  在编辑器里会被解析成 -2-  如果能直接显示成  {这里是需要替换的文档类型-2-这里是文档名称} 就非常完美了），然后每个用户再针对这个模版通过对应业务逻辑自动渲染成表格或其他文字什么的，这样
![image](https://github.com/user-attachments/assets/46efd3bd-6640-45ad-8863-4e5fde4b4aa6)

### What does the proposed API look like?

希望能添加一个类似LaTex的无法直接修改文字控件功能或者api

**Comment by Hufe921** [comment]
插入标题并设置只读即可:
``` ts
    instance.command.executeInsertTitle({
      type: ElementType.TITLE,
      level: TitleLevel.FIRST,
      value: '',
      title: {
        disabled: true
      },
      valueList: [
        {
          value: '测试标题'
        }
      ]
    })
```
