### ISSUE TITLE
怎么在已填写的文本里插入值啊，executeSetValue好像没用

### ISSUE THREAD

**Issue by junliangwei** [Hufe921/canvas-editor#794]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/8ca11941-a793-4f27-80ae-59c7ade4ead9)

### What does the proposed API look like?

executeSetValue

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/command-execute.html#executeinsertelementlist
```ts
  instance.command.executeInsertElementList([{
    value:'123'
  }])
```
