### ISSUE TITLE
新增设计模式

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#795]
### What problem does this feature solve?

#793 感谢大佬回复，我试了一下使用只读标题发现还是有2个问题 1.这个只读的标题内容可以按删除键一个一个删除掉 2.浮动图片可以插入到标题的中间，导致内容被截断成两个json对象变量效果失效（或者说给变量匹配增加了难度）
问题1截图：
![image](https://github.com/user-attachments/assets/297eefc3-2b6a-4e68-a6c3-91cef621c9c8)
问题2截图：
![image](https://github.com/user-attachments/assets/9b4a9594-1b9f-47cf-82d6-e2ca81f8ad08)
![image](https://github.com/user-attachments/assets/c97e06a8-20a2-4f00-8c30-09203103544d)

### What does the proposed API look like?

希望能实现类似LaTex的真实 的只读（渲染成图片），就是如果删除整个标签删除，如果添加浮动图片，不能把光标定在标签内部

**Comment by Hufe921** [comment]
deletable设置false

**Comment by liushuai05** [comment]
> deletable设置false

非常感谢大佬，完美解决

**Comment by liushuai05** [comment]
> deletable设置false

对了大佬 这样的标签好像成了牛皮癣  想要整个删掉好像又删除不掉了

**Comment by Hufe921** [comment]
做模板的时候添加的不可删除标题吗

**Comment by liushuai05** [comment]
> 做模板的时候添加的不可删除标题吗

嗯嗯 就加了 deletable设置false  以后 通过api添加的标签 会完全无法删除 怎么都删不掉 全选按 del和删除键都不行  没加之前可以删 但又不能限制只读

**Comment by Hufe921** [comment]
那需要添加设计模式了

**Comment by liushuai05** [comment]
> 那需要添加设计模式了

非常感谢大佬  按目前来看 用这个标题其实也能行 就是要解决无法完全删除的问题  （就是不能删除中间内容，但是要能删除整个标签，不然就真成牛皮癣了）
也不是非得重构一个完整的新模块什么的

**Comment by liushuai05** [comment]
> 那需要添加设计模式了

已经得到解决了，采用Control的placeholder即可，在qq群里得到了大佬解惑

**Comment by liushuai05** [comment]
非常感谢大佬 已经看到你添加的DESIGN模式了 我这边试试看
