### ISSUE TITLE
打开编辑器页面，如何触发光标聚焦且聚焦在文档内容末尾处

### ISSUE THREAD

**Issue by junliangwei** [Hufe921/canvas-editor#796]
### What problem does this feature solve?

打开编辑器页面，如何触发光标聚焦且聚焦在文档内容末尾处

### What does the proposed API look like?

如题

**Comment by junliangwei** [comment]
看了api 感觉是不是用法错不对
![image](https://github.com/user-attachments/assets/0a2c81ca-9b3b-4aee-b135-2fa0100f03a2)

**Comment by Hufe921** [comment]
> 看了api 感觉是不是用法错不对 ![image](https://private-user-images.githubusercontent.com/58672206/362097526-0a2c81ca-9b3b-4aee-b135-2fa0100f03a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Mzk4NTUsIm5iZiI6MTcyNDgzOTU1NSwicGF0aCI6Ii81ODY3MjIwNi8zNjIwOTc1MjYtMGEyYzgxY2EtOWIzYi00YWVlLWIxMzUtMmZhMDEwMGYwM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDE3OWY4NGRiMjU4NjJmMDA5MzgwYmRlYWUyZTdhMzBhNThhZjZkNzJlMTY3NjYxZTNhY2MwODdjNjk3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hVPBRjA96mkbq1dTU9Vw_W-9b7LruvVu1-Ov-6_iwIY)

你这是定位控件的api，光标聚焦的需要新增

**Comment by junliangwei** [comment]
> > 看了api 感觉是不是用法错不对 ![image](https://private-user-images.githubusercontent.com/58672206/362097526-0a2c81ca-9b3b-4aee-b135-2fa0100f03a2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4Mzk4NTUsIm5iZiI6MTcyNDgzOTU1NSwicGF0aCI6Ii81ODY3MjIwNi8zNjIwOTc1MjYtMGEyYzgxY2EtOWIzYi00YWVlLWIxMzUtMmZhMDEwMGYwM2EyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODI4VDEwMDU1NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY3NDE3OWY4NGRiMjU4NjJmMDA5MzgwYmRlYWUyZTdhMzBhNThhZjZkNzJlMTY3NjYxZTNhY2MwODdjNjk3NTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.hVPBRjA96mkbq1dTU9Vw_W-9b7LruvVu1-Ov-6_iwIY)
> 
> 你这是定位控件的api，光标聚焦的需要新增

不明白 有什么api能够实现 能指点一下嘛

**Comment by Hufe921** [comment]
新增api
```ts
instance.command.executeFocus({
    position: LocationPosition.AFTER
  })
```

**Comment by junliangwei** [comment]
> 新增api
> 
> ```ts
> instance.command.executeFocus({
>     position: LocationPosition.AFTER
>   })
> ```



> 新增api
> 
> ```ts
> instance.command.executeFocus({
>     position: LocationPosition.AFTER
>   })
> ```

谢谢，等待大哥npm包更新

**Comment by liujianing971218** [comment]
这个api只能够将光标聚焦到开始或者结尾嘛？如果是自己希望将光标移动到文档的某个位置应该怎么做呢？
