### ISSUE TITLE
控件删除的bug

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#797]
### version

0.9.90

### Steps to reproduce

增加的control->text控件，属性deletable=false, 前后缀用\u200c不可见字符，用executeSetControlProperties修改属性 当deletable=true的时候，控件无法删除。而且使用不可见字符后，鼠标点击文本，光标定位不准，只能在文本前后定位。

### What is expected?

如上

### What is actually happening?

如上

**Comment by bettersoft123** [comment]
好像光标要在最后面再删除，就能删除掉，应该光标在这个控件的任何位置，只要backspace把整个控件都能删除掉。

**Comment by Hufe921** [comment]
删除问题无法复现。应该是光标没有定位到控件内，使用不可见的前后缀就要考虑到此问题。
后期结合#740的实现，进行交互优化
