### ISSUE TITLE
Is there any server end export 

### ISSUE THREAD

**Issue by NicholasNap** [Hufe921/canvas-editor#798]
### What problem does this feature solve?

I found there not exist the way to export the word document at the server, what should I do?

### What does the proposed API look like?

Export the word document at the server end.

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/en/guide/plugin-internal.html#word

**Comment by NicholasNap** [comment]
I mean is there something like java server end api to export word document.

**Comment by douglasmatheus** [comment]
> I mean is there something like java server end api to export word document.

Hello, in Java there is [Apache POI](https://poi.apache.org/index.html) and [OpenOffice.org's Universal Network Objects (UNO)](https://www.openoffice.org/udk/common/man/uno.html). I believe there must be others as well, and in other languages ​​there must certainly be several libs for export. In the case of UNO, if I'm not mistaken, it supports several languages ​​(Visual Basic, Java, C++, and others) and platforms (Windows, Linux, Unix, etc.).

The ideal is to generate on the front end, but if in your case you need a backend, I would initially recommend these two in Java. I hope this helps.
