### ISSUE TITLE
表格内容过多，表格错位

### ISSUE THREAD

**Issue by zhaoxuanHome** [Hufe921/canvas-editor#802]
### version

0.9.92

### Steps to reproduce

我本地和代码提供的demo都进行测试。
现在展示：三张图片
**1.正常：表格内容没有超过当页**
![canvas-editor (2)](https://github.com/user-attachments/assets/04ae6528-7de8-4f73-88ad-c1e4c67806a5)

**2.异常：表格内容超过当页到达第二页**
![canvas-editor (1)](https://github.com/user-attachments/assets/aa888ef1-9b35-4242-ba96-832f07a2062d)

**3.异常：表格内容超过当页并且超过第二页，后续内容被隐藏**
![canvas-editor](https://github.com/user-attachments/assets/afa78323-8aa6-48e7-9a30-32197b049a59)

### What is expected?

表格内容跨行，可以自动分割新表格

![image](https://github.com/user-attachments/assets/89bee942-8c82-4371-83ba-ddc795a18da3)

### What is actually happening?

表格内容夸页，表格不自动分裂表格进行存储

**Comment by Hufe921** [comment]
重复：#41
