### ISSUE TITLE
使用executeUpdateElementById修改表格时，表格内数据处理错误

### ISSUE THREAD

**Issue by zhoujingfu** [Hufe921/canvas-editor#806]
### version

0.9.92

### Steps to reproduce

1. 获取到表格的id
2. 使用executeUpdateElementById修改表格extension

### What is expected?

正常修改

### What is actually happening?

表格内单元格数据前面自动增加\n，控件自复制
![GIF 2024-9-11 18-30-12](https://github.com/user-attachments/assets/2327c408-a5df-4f95-8dbb-52d23d7a742a)

**Comment by zyb1123** [comment]
如何插入自己编辑好带有内容的表格？
