### ISSUE TITLE
后端程序如何将编辑器的内容转换为PDF或HTML之类能打印的文件格式

### ISSUE THREAD

**Issue by chengliang4810** [Hufe921/canvas-editor#808]
### What problem does this feature solve?

后台多文档合并PDF进行打印

### What does the proposed API look like?

将文档内容转换为html代码之类的

**Comment by Hufe921** [comment]
html：可以前端获取给后端。
pdf：如果不可复制的pdf就可以满足需求，可以直接导出图片后直接生成pdf；
如果需要正常可复制文字的pdf，需拿到编辑器结构化数据后自行绘制

**Comment by xuwencheng** [comment]
> html：可以前端获取给后端。 pdf：如果不可复制的pdf就可以满足需求，可以直接导出图片后直接生成pdf； 如果需要正常可复制文字的pdf，需拿到编辑器结构化数据后自行绘制

我用getImage转的图片，会把页边距四个角的线条也包含在内，这个有办法可以去掉吗？
![image](https://github.com/user-attachments/assets/e0556b69-7ff2-4944-847f-92519667caac)
