### ISSUE TITLE
导出word以后 word页面数 和网页上的页面数对不上

### ISSUE THREAD

**Issue by CHEN20241111123123** [Hufe921/canvas-editor#810]
### What problem does this feature solve?

导出word以后 word页面数 和网页上的页面数对不上

### What does the proposed API look like?

导出word以后 word页面数 和网页上的页面数对不上

**Comment by CHEN20241111123123** [comment]
导出word 发现回车不识别 全在同一行显示

**Comment by CHEN20241111123123** [comment]
![B8E4CAA9-F2FA-4010-8174-B9A8960FC757](https://github.com/user-attachments/assets/5e5e8051-02d0-44bc-b5c1-4de1667eda94)
![Uploading FE08C22A-0745-4b77-9EA8-A022295588D3.png…]()

**Comment by CHEN20241111123123** [comment]
![B8E4CAA9-F2FA-4010-8174-B9A8960FC757](https://github.com/user-attachments/assets/492c01e7-684f-4c5a-b970-d786eec9126b)

**Comment by CHEN20241111123123** [comment]
![Uploading FE08C22A-0745-4b77-9EA8-A022295588D3.png…]()

**Comment by CHEN20241111123123** [comment]
![Uploading FE08C22A-0745-4b77-9EA8-A022295588D3.png…]()

**Comment by CHEN20241111123123** [comment]
![a3791426a61da9d6bb59ea7df87723b2](https://github.com/user-attachments/assets/caf0a114-55e3-4d0d-9a75-6ca98f7c8def)

**Comment by CHEN20241111123123** [comment]
表格下方就没有换行了

**Comment by Hufe921** [comment]
此仓库不解决插件问题
