### ISSUE TITLE
能通过目录内的标题的id 获取页码数吗 想做一个页面插入目录的功能

### ISSUE THREAD

**Issue by CHEN20241111123123** [Hufe921/canvas-editor#812]
### What problem does this feature solve?

能通过目录内的标题的id 获取页码数吗 想做一个页面插入目录的功能

### What does the proposed API look like?

能通过目录内的标题的id 获取页码数吗 想做一个页面插入目录的功能

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/738
