### ISSUE TITLE
当文本中连续输入英文字母 f 时 光标会不准确

### ISSUE THREAD

**Issue by wangtao1025** [Hufe921/canvas-editor#813]
### version

latest

### Steps to reproduce

官网 demo 中在中文标题中间插入多个英文字符会造成光标位置不准确
![Snipaste_2024-09-20_17-22-51](https://github.com/user-attachments/assets/56a69991-bbd2-444f-bd68-e408a58f0982)

### What is expected?

光标准确

### What is actually happening?

无

**Comment by Hufe921** [comment]
先配置使用渲染兼容模式：
```
const options: IEditorOption = {
  renderMode: RenderMode.COMPATIBILITY
}
```

**Comment by claviering** [comment]
输入数字1也会这样子，光标是没有问题的，是渲染的文字稍稍的偏差

<img width="315" alt="Screen Shot 2024-10-10 at 11 08 34" src="https://github.com/user-attachments/assets/85777a83-5887-4927-98c8-350277c7df93">

**Comment by claviering** [comment]
使用其他字体就可以

**Comment by claviering** [comment]
连续输入数字 1 也会出现光标位置不准确
```
ctx.font = '24px Microsoft YaHei';
ctx.measureText("1").width * 2 !== ctx.measureText("11").width
// ctx.measureText("1").width: 12
// ctx.measureText("1").width: 23.12109375
```

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
