### ISSUE TITLE
Use image links rather than base64

### ISSUE THREAD

**Issue by lehno** [Hufe921/canvas-editor#814]
### What problem does this feature solve?

When storing data of editor in backend, it would be better to have the image link and when applying to editor in frontend, it transforms again in base64. When geting editor value, it brings the original link back

### What does the proposed API look like?

Create a command to insert a new image control that contains the link of the image in the extension property and core uses it to download image and show it as base64, when calling editor value, return only extension

**Comment by Hufe921** [comment]
Image element support link insertion
```
{
      type: ElementType.IMAGE,
      value: 'https://via.placeholder.com/200',
      width: 200,
      height: 200
}
```
