### ISSUE TITLE
Control type rich textarea

### ISSUE THREAD

**Issue by lehno** [Hufe921/canvas-editor#816]
### What problem does this feature solve?

It solves the problem of having a specifc area in the document where user can type long text and insert styles like bold, bullet, ordered lists, table.
On the picture below, I was able to create a template of a document, where subject name and signature / signoff can be auto populated on backend. 
But the area called {Body} and {Diagnosis} is the area where I want to let user type rich text and insert new elements. And in the backend, access the value json and extract the content of Body only

<img width="853" alt="image" src="https://github.com/user-attachments/assets/dbb06a33-6d50-4628-9832-8f6c6b67d27c">

### What does the proposed API look like?

A proposed solution is having a extra control of type TEXTAREA, that allows any type of content as the rest of the document, but all inside a control where I can extract the value of this area in the backend without rendering the canvas by using `extension` to define specific properties like: `{ name: 'Body' }`

If there is a way of doing it today or you can point me to some code.
Thanks for this amazing project, I already was able to do a lot with it.

**Comment by Hufe921** [comment]
My summary of your requirement is: the control supports inserting rich text elements through APIs?

**Comment by lehno** [comment]
Yes, we have some requirements of inside a control, be able to insert tables, images, other regular elements. At backend, I find the control and can extract all content of that control

**Comment by lehno** [comment]
Thanks for this update. I was able to test it and it works with text, styles, list, but I cant add a table inside, is this more difficult?

**Comment by lehno** [comment]
Also, if you insert a checkbox inside, you can click to mark it checked
