### ISSUE TITLE
Show pageNo and pageCount in header or main

### ISSUE THREAD

**Issue by lehno** [Hufe921/canvas-editor#817]
### What problem does this feature solve?

We have some use cases that they need the page number or count in some other areas of the document

### What does the proposed API look like?

Be able to insert the pageNo or pageCount as a variable and when rendering, value is replaced

**Comment by Hufe921** [comment]
Give an actual usage scenario

**Comment by lehno** [comment]
The documents we produce need to be printed in a later stage and some hospitals want to show the page counter for example. So if they print, they know in the first page how many pages it should have
<img width="833" alt="image" src="https://github.com/user-attachments/assets/061d8e48-abac-4c71-815c-af0593991dea">

**Comment by Hufe921** [comment]
`pageCount`:
```ts
  instance.listener.pageSizeChange = function (payload) {
    instance.command.executeSetControlValue({
      conceptId: '1',
      value: `page count: ${payload}`
    })
  }
```

`pageNo`:
If the page number data is placed within the main text, it will affect the calculation of the page number itself and cause a calculation loop. This requirement cannot be fulfilled
