### ISSUE TITLE
表格中插入的表格不可编辑

### ISSUE THREAD

**Issue by Leroy1109** [Hufe921/canvas-editor#820]
### version

0.9.92

### Steps to reproduce

插入表格，在单元格中插入表格，单元格中表格不能选中单元格和编辑

### What is expected?

单元格中表格可以编辑

### What is actually happening?

插入表格，在单元格中插入表格，单元格中表格不能选中单元格和编辑

**Comment by Hufe921** [comment]
不支持嵌套
