### ISSUE TITLE
在监听controlChange时遇到的问题

### ISSUE THREAD

**Issue by AsuraMeng** [Hufe921/canvas-editor#822]
### version

0.9.93

### Steps to reproduce

在监听instance.listener.controlChange = (payload: IControl | null) => {}， 从一个控件到另一个控件，中间会有一个null进行过度，导致处理时，会有一个中间的无效变化需要处理，动态效果时，就会造成闪烁的问题

### What is expected?

期望从一个控件到另一个控件，不要出现中间payload=null的过度

### What is actually happening?

根据当前获取的控件，边框切换动态效果时，闪烁

**Comment by Hufe921** [comment]
null的时候当前控件被销毁，可以自行逻辑判断

**Comment by AsuraMeng** [comment]
非常感谢你的回复，我的应用场景是比如一个左侧一个列表，一人知识库。编辑器中存在两个文本控件。当控件聚焦时，左侧需要切换到知识库。失去焦点时，切换到列表。
因从一个控件到另一个控件，中间的控件改变多了个中间状态，导致左侧的切换就像闪烁一样，切到列表，又切到知识库。




孟庆德
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Hufe921/canvas-editor"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2024年9月25日(星期三) 晚上8:44
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Hufe921/canvas-editor] 在监听controlChange时遇到的问题 (Issue #822)






null的时候当前控件被销毁，可以自行逻辑判断

**Comment by Hufe921** [comment]
你可以这样写：
```ts
  let isDestroy = false
  instance.listener.controlChange = function (payload) {
    if (payload) {
      console.log('激活')
      isDestroy = false
    } else {
      isDestroy = true
      setTimeout(() => {
        if (isDestroy) {
          console.log('销毁')
        }
      })
    }
  }
```
