### ISSUE TITLE
表格的单元格设置不可编辑，不可删除时，表格中的控件设置的可编辑失效

### ISSUE THREAD

**Issue by AsuraMeng** [Hufe921/canvas-editor#823]
### version

0.9.93

### Steps to reproduce

单元格插入文本控件，控件设置可编辑不可删除，单元格示设置时，可能删除。需要设置单元格不可删除，不可删除。只对文本控件可编辑，结果是单元格优先的生效，文本控件不生效

### What is expected?

就近优先原则。单元格中的文本控件设置可编辑不可删除，可以正常设置

### What is actually happening?

在单元格中设置文本控件可编辑，不可删除，无法正常设置

**Comment by Hufe921** [comment]
单元格优先控件，单元格不要设置不可编辑
