### ISSUE TITLE
executeSetControlProperties后controlId自动被修改？ 

### ISSUE THREAD

**Issue by bettersoft123** [Hufe921/canvas-editor#832]
### version

0.9.93

### Steps to reproduce

executeSetControlProperties是修改control属性的基本方法，为何调用完此方法后，再看controlId已经自动发生了变化，是否可以不变，毕竟这个controlId是需要保存下来的。谢谢

### What is expected?

如上

### What is actually happening?

如上

**Comment by Hufe921** [comment]
可以使用conceptId此id为用户自定义id不会改变
