### ISSUE TITLE
表格能支持超出画布宽度并能横向左右滚动吗

### ISSUE THREAD

**Issue by tuzixiangs** [Hufe921/canvas-editor#834]
### What problem does this feature solve?

目前的表格宽度不能超过画布的宽度,导致复制或者导入进来的表格会被压缩宽度,排版会严重变形.

### What does the proposed API look like?

希望实现类似于下面的效果

https://github.com/user-attachments/assets/b5cebd19-ae7c-40b9-a651-18001426c965

**Comment by Hufe921** [comment]
基于编辑器实现技术方式及特性，暂不考虑此需求实现
