### ISSUE TITLE
当保存或者复制到剪切板粘贴时获取到的控件颜色会丢失

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#843]
### version

0.9.94

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

如下截图，下面那个控件是我按ctrl+c然后再ctrl+v粘贴出来的，颜色没有，然后按保存时右边console打印出来的内容每个控件中没有颜色值获取到，options里倒是有一个，但是保存后再按这个json渲染出来所有控件都是没有颜色的
![image](https://github.com/user-attachments/assets/8da56ad3-3e56-4e5e-8cb8-3f71849b1fa6)

![image](https://github.com/user-attachments/assets/37bf92c5-b54c-4f0c-9f46-cda88a68bed9)

### What is expected?

理论上控件能设置颜色那应该也能保存这个颜色，

### What is actually happening?

但是好像保存不了

**Comment by daria2023** [comment]
![image](https://github.com/user-attachments/assets/993670d5-8685-4ed0-9a29-f789dedbf2ee)
版本一致，颜色可以复制，你的问题没有复现出来

**Comment by liushuai05** [comment]
> ![image](https://private-user-images.githubusercontent.com/95205482/376443212-993670d5-8685-4ed0-9a29-f789dedbf2ee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3Mjg5NjQ5MzUsIm5iZiI6MTcyODk2NDYzNSwicGF0aCI6Ii85NTIwNTQ4Mi8zNzY0NDMyMTItOTkzNjcwZDUtODY4NS00ZWQwLTlhMjktZjc4OWRlZGJmMmVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMTUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDE1VDAzNTcxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZjNWU4NDhjOGViN2RkODc0NDQyMzEwZjM0YWQ1YmZkZTM2ZWVjZGMxOGI3N2NmNWFlMDgwMzYzOTVlY2I0ZWMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.BqZbDs1WJ39RVpUc_eCsozOeO3rwj8_l_BE0GhG-XgM) 版本一致，颜色可以复制，你的问题没有复现出来

无法复制：ctrl+c 然后ctrl+v  而不是重新建立一个控件
无法保存：ctrl+v  只能保存全局颜色，无法针对每一个保存，并且括号无法保存自定义颜色

https://github.com/user-attachments/assets/4e833bd4-d085-45f7-90e0-f55f445ac6df


我已经在修复这个问题了

**Comment by Hufe921** [comment]
placeholder和前后缀不支持设置样式， 应该统一配置

**Comment by liushuai05** [comment]
> placeholder和前后缀不支持设置样式， 应该统一配置

好滴吧看样子这个只是我这里的特定需求，感谢大佬
