### ISSUE TITLE
设置表单里面的值是的函数在哪

### ISSUE THREAD

**Issue by songyipan** [Hufe921/canvas-editor#845]
### What problem does this feature solve?

设置表里面的值是的函数在哪

### What does the proposed API look like?

设置表里面的值是的函数在哪

**Comment by Hufe921** [comment]
设置某行某列里面的元素？

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.

**Comment by Hufe921** [comment]
表格元素设置conceptId
获取元素信息：getElementById
修改元素属性：executeUpdateElementById
