### ISSUE TITLE
希望新增通过value内容获取对应内容list，并返回对应页码功能

### ISSUE THREAD

**Issue by liushuai05** [Hufe921/canvas-editor#846]
### What problem does this feature solve?

我们这边客户提了个需求，要求部分关键词内容要能直观的在左侧显示关键字并且能直观显示该内容在哪些页面有，并且能直接点击关键字跳转到对应页码，后面的跳转功能我看到好像能实现，就是获取页码好像没有。

### What does the proposed API look like?

希望新增通过value内容获取对应所有内容，并返回对应页码api

**Comment by Hufe921** [comment]
获取关键词所在页码？

**Comment by liushuai05** [comment]
> 获取关键词所在页码？

是滴是滴能获取 所在页码和控件ID即可  但是可能一个关键词对应有多个控件
