### ISSUE TITLE
编辑模式下焦点放到数据元框里面还是可以删除当前数据元的这个有优化吗

### ISSUE THREAD

**Issue by myNameWZH** [Hufe921/canvas-editor#849]
### What problem does this feature solve?

编辑模式下焦点放到数据元框里面还是可以删除当前数据元的这个有优化吗

### What does the proposed API look like?

编辑模式下焦点放到数据元框里面还是可以删除当前数据元的这个有优化吗

**Comment by daria2023** [comment]
你是说文本控件设置deletable为false之后光标定位控件内部可以删除内部文字吗？

**Comment by daria2023** [comment]
你是说文本控件设置deletable为false之后光标定位控件内部可以删除内部文字吗？

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/schema.html
```ts
{
  deletable?: boolean;
  disabled?: boolean;
}
```
