### ISSUE TITLE
内容框输入 标题 1 换行 再输入标题 2 第二行会莫名出现一个空格

### ISSUE THREAD

**Issue by sonlige** [Hufe921/canvas-editor#851]
### version

0.9.94

### Steps to reproduce

官方例子也有该问题

### What is expected?

官方例子也有该问题

### What is actually happening?

内容框输入 标题 1 换行 再输入标题 2 第二行会莫名出现一个空格

### Editor Value

```json
<span style="font-family: &quot;Microsoft YaHei&quot;; font-size: 16px;">标题 1<br> 标题 2</span>
```

### System Info

```shell
System:
    OS: macOS 12.6
    CPU: (8) x64 Intel(R) Core(TM) i5-8250U CPU @ 1.60GHz
    Memory: 46.05 MB / 16.00 GB
    Shell: 5.8.1 - /bin/zsh
  Binaries:
    Node: 16.10.0 - /usr/local/bin/node
    Yarn: 1.22.19 - /usr/local/bin/yarn
    npm: 7.24.0 - /usr/local/bin/npm
  Browsers:
    Chrome: 129.0.6668.101
    Safari: 15.6.1
```

**Comment by sonlige** [comment]
补充: 好像是上一行如果只有 3 个文字,那么换行再输入就会带上 1 个空格

**Comment by Hufe921** [comment]
没有复现，而且你提供的EditorValue为啥是html？

你可以录屏给出复现步骤 或最小可访问的复现demo地址

**Comment by sonlige** [comment]
https://github.com/user-attachments/assets/412259b9-8ba2-4285-82c3-b26ddab2ab1a

**Comment by sonlige** [comment]
我在录制屏幕的时候想了一下有可能是 微信输入法 的问题, 当我切换到其他输入法的时候该问题并不产生, 后面验证过后发现 , wps 不会有该情况发生 , 腾讯文档有该情况发现, 这个可能是 微信输入法的 bug

**Comment by sonlige** [comment]
我在录制屏幕的时候想了一下有可能是 微信输入法 的问题, 当我切换到其他输入法的时候该问题并不产生, 后面验证过后发现 , wps 不会有该情况发生 , 腾讯文档有该情况发生, 这个可能是 微信输入法 的bug
