### ISSUE TITLE
复制粘贴问题

### ISSUE THREAD

**Issue by sonlige** [Hufe921/canvas-editor#852]
### What problem does this feature solve?

从 wps 复制粘贴过来 , 文档格式会丢失 , 例如 , 字体 , 居中 

### What does the proposed API look like?

直接复制之后格式对上

**Comment by Hufe921** [comment]
字体刻意为之，可以参考之前issues。居中没有复现。提供一下wps数据

**Comment by sonlige** [comment]
我从之前的 issues 查看到对应的 字体处理方式, 我尝试一下 , wps的数据就是直接在里面写一些数据,使用 wps 进行居中,再进行复制

**Comment by sonlige** [comment]
补充 : 我把 wps 的数据修改过后,全选复制,标题便能自动居中 , 不知道会不会是与 wps 的隐藏字符有关系
