### ISSUE TITLE
希望在输入控件加上禁止粘贴的属性

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#853]
### What problem does this feature solve?

由于业务需要希望作者能加上禁止粘贴的属性
主要是文本和日期控件
![image](https://github.com/user-attachments/assets/426170eb-5984-4e71-be82-a96a21c6145a)

### What does the proposed API look like?

暂无

**Comment by Hufe921** [comment]
试试,是否满足需求
```ts
  instance.override.paste = () => {
    const rangeContext = instance.command.getRangeContext()
    if (rangeContext?.startElement?.control?.type === ControlType.DATE) {
      return
    }
    return { preventDefault: false }
  }
```

**Comment by zhuyihe** [comment]
> ```ts
>  const rangeContext = instance.command.getRangeContext()
> ```

能否根据控件id判读 只有部分控件不能禁止用户粘贴

**Comment by Hufe921** [comment]
rangeContext内有控件相关信息，可以调试试试

**Comment by zhuyihe** [comment]
> rangeContext内有控件相关信息，可以调试试试

好的 谢谢

**Comment by AndyT-PrimoSpade** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
