### ISSUE TITLE
PDF版本Draw.ts 是否可以提供setValue 对应的getValue方法，对占位符进行数据替换

### ISSUE THREAD

**Issue by doomsky94yifei** [Hufe921/canvas-editor#854]
### What problem does this feature solve?

PDF版本和主分支版本的数据结构不一致，是否可在主分支集成pdf绘制，或在pdf分支提供 对应的getValue方法，对占位符进行数据替换

### What does the proposed API look like?

在1

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/607
现阶段考虑自行实现
