### ISSUE TITLE
能不能指定控件不能被修改内容和删除？

### ISSUE THREAD

**Issue by lgdzz** [Hufe921/canvas-editor#857]
### What problem does this feature solve?

1、能不能指定部份控件在编辑模式下禁止删除内容和修改内容？
2、能不能增加块循环复制，比如给一个开始一个结束的标记，能复制标记中间的内容进行循环生成处理？

### What does the proposed API look like?

-

**Comment by Hufe921** [comment]
1. https://hufe.club/canvas-editor-docs/guide/schema.html
```ts
deletable?: boolean; // 是否可删除
disabled?: boolean; // 是否可编辑
pasteDisabled?: boolean; // 是否粘贴
```

2. 数据操作自行处理
