### ISSUE TITLE
支持获取和设置编辑器内部粘贴板数据

### ISSUE THREAD

**Issue by goodboy-yes** [Hufe921/canvas-editor#860]
### What problem does this feature solve?

现在复制控件时conceptId和extension这些自定义字段是相同的，在业务上没法区分为两个不同控件，需要在粘贴时更改conceptId，看源码中是通过localStorage中转编辑器内部数据，现在有个想法是粘贴时更改localStorage里的数据，再走编辑器内部逻辑，这样是否可行，是否有方式能获取到相关数据？
感谢~

### What does the proposed API look like?

新增获取和设置编辑器内部粘贴板数据api，或暴露EDITOR_CLIPBOARD常量开发者自行处理

**Comment by Hufe921** [comment]
不同控件的 controlId不同

**Comment by goodboy-yes** [comment]
感谢回复，我在实际使用中每个控件会额外维护一些信息存储在数据库中，两者通过自定义的conceptId联系起来，controlId是编辑器生成的，不好在插入控件时就和额外信息建立联系
现有的复制粘贴操作会造成有两个相同conceptId的控件，我在编辑其中一个的信息时会导致同时更改了这两个控件的信息，但实际上我想让这两个控件独立开来

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/853#issuecomment-2428859098
参考之前issue重写粘贴方法。
