### ISSUE TITLE
Example Demo

### ISSUE THREAD

**Issue by jordanparker6** [Hufe921/canvas-editor#861]
### What problem does this feature solve?

Hey team,

Nice editor! 

Coming from tip-tap the plugin framework is very attractive.

It would be amazing if you could make the code for the demo example public so we can see how we could use this repo in a full editor set up.

Let me know if this is something you would be interested. Happy to support as I get to know this project more.

Jordan

### What does the proposed API look like?

`/demos/` folder in the main repo with the vite or nextjs setup?

**Comment by Hufe921** [comment]
npm run dev：src/main.ts is the example code
