### ISSUE TITLE
Word Count Doesn't Update Correctly

### ISSUE THREAD

**Issue by jordanparker6** [Hufe921/canvas-editor#862]
### version

v0.9.94

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

The current live demo examples the word count not updating correctly.

You can see it works fine for deletes but as I type it doesn't update the word count correctly. It some slow increments by 1 at a rate not equal to the typing rate and doesn't end up converging to the true word count.

### What is expected?

Its expected to update correctly. The debounce is not long enough that this should impact it.

### What is actually happening?

Freely typing text isn't updating the word count.

### Any additional comments?

(https://www.loom.com/share/9cb11c4d0eec4aa3ac8cbf15907be210)

**Comment by Hufe921** [comment]
Word count calculation consumes performance, so there may be some delay in using web woker for calculations
