### ISSUE TITLE
控件本身实现了在修改时能监听获取到修改后的内容吗

### ISSUE THREAD

**Issue by jianghuchaun-konan** [Hufe921/canvas-editor#863]
控件本身实现了在修改时能监听获取到修改后的内容吗
![image](https://github.com/user-attachments/assets/a96ea0aa-f67a-462f-afbb-43a4b4e82a53)
我这里是在图片中的方法中又添加了监听，监听到修改，拿到修改后的内容
![image](https://github.com/user-attachments/assets/a0b79612-053c-4857-b626-833b055bc411)
然后再通过我定义的字段找到相同的控件遍历去修改，目前是可以实现全部修改，但是在修改表格内控件的时候会有问题
![image](https://github.com/user-attachments/assets/f9647169-c850-41ac-830e-d2e71b222cc7)
![image](https://github.com/user-attachments/assets/32289486-0682-49d4-a4c8-888f422799c8)
![image](https://github.com/user-attachments/assets/9b05c0d0-089f-4be9-9682-9aec0c1f322f)

**Comment by Hufe921** [comment]
不同控件设置相同的Iconceptd 设置值的时候都会设置。

**Comment by jianghuchaun-konan** [comment]
> 不同控件设置相同的Iconceptd设置值的时候都会设置。

控件设置了相同的Iconceptd，修改单个控件的时候相同Iconceptd的控价就会统一修改掉吗

**Comment by Hufe921** [comment]
通过executeSetControlValue api会全部修改。可以动手试试

**Comment by jianghuchaun-konan** [comment]
> 通过executeSetControlValue api会全部修改。可以手动尝试

![image](https://github.com/user-attachments/assets/a959f4ce-f986-4ed3-964d-a30a22a00076)
上图中我在controlChange的监听中尝试调用了executeSetControlValue方法去修改所有相同的控件，但是并没有全部修改，只有当前输入的控件有效果如下
![image](https://github.com/user-attachments/assets/445fb469-c353-4cda-9202-aac6392bfb30)
