### ISSUE TITLE
图片在只读模式下有focus  状态

### ISSUE THREAD

**Issue by yzw20110902** [Hufe921/canvas-editor#875]
### version

0.9.94

### Steps to reproduce

图片在只读模式下有focus  状态

### What is expected?

图片在只读模式下有focus 应该是无focus 状态

### What is actually happening?

插入图片，点击为可读模式，在点击图片就出现了

### Any additional comments?

![image](https://github.com/user-attachments/assets/f8d97663-e59a-497f-a25e-762a9e567b78)

**Comment by Hufe921** [comment]
查看也可以聚焦并双击预览，不过可拖拽点倒是可以隐藏
