### ISSUE TITLE
疑问：鼠标点击获取当前位置

### ISSUE THREAD

**Issue by daria2023** [Hufe921/canvas-editor#882]
![image](https://github.com/user-attachments/assets/9d5071f9-a4b2-4959-8b0f-10d5509f6090)
我正在看鼠标点击文档下半部分空白部分时发现当鼠标位置位于`main`区域后，有一个判断是对`y <= margins[1]` 为什么y坐标是和右边距进行对比呢，没有理解到，希望您可以帮忙解答一下，谢谢

**Comment by Hufe921** [comment]
应该是margin[0]上边距
