### ISSUE TITLE
placeholder中存在‘\n’时没有正确渲染换行

### ISSUE THREAD

**Issue by yumi-toushou** [Hufe921/canvas-editor#883]
### What problem does this feature solve?

![image](https://github.com/user-attachments/assets/3a005106-9e4e-45b0-82df-a5718ed8a706)
![image](https://github.com/user-attachments/assets/d1e43466-1ba3-4a59-90c4-3e92d2b1a7c3)

### What does the proposed API look like?

addPlaceholder 方法没有将 '\n' 换成 ZERO ?

![image](https://github.com/user-attachments/assets/92b5f887-f6b3-48d8-a293-2a86078810b6)

**Comment by Hufe921** [comment]
是的 有问题。
可以发起一下pr
