### ISSUE TITLE
请问我在表格里添加的控件在使用executeSetControlValue去修改时会报错是什么原因呢

### ISSUE THREAD

**Issue by jianghuchaun-konan** [Hufe921/canvas-editor#884]
我设置了conceptId
![image](https://github.com/user-attachments/assets/991d7b16-0397-4afe-b770-d24993d1ddb2)
然后在controlChange的监听中使用executeSetControlValue修改
![image](https://github.com/user-attachments/assets/a24acaba-e07f-441c-9363-a09c5f32271b)
在表格之外的都可以正常修改，但是表格内部的修改就会报错如下图
![image](https://github.com/user-attachments/assets/b0e6ea6e-834c-4cb9-b2ab-0e55276bb49e)
![image](https://github.com/user-attachments/assets/589d7e3c-da6c-4f5b-b756-0ac393d2e377)
求大佬j解惑

**Comment by Hufe921** [comment]
为什么要在controlChange设置控件数据？

**Comment by jianghuchaun-konan** [comment]
> 为什么要在controlChange设置控件数据？

我有一个场景，要在修改一个控件的时候将插入的所有相同的控件也同步去修改

**Comment by Hufe921** [comment]
可以在控件失活的时候 再设置，不要立刻设置。

**Comment by jianghuchaun-konan** [comment]
> 可以在控件失活的时候 再设置，不要立刻设置。

请问有对应的api吗，可以拿到修改的数据吗

**Comment by Hufe921** [comment]
优化controlChange，增加控件失活激活状态：
```
  instance.eventBus.on('controlChange', payload => {
    if (payload.state === ControlState.INACTIVE) {
      instance.command.executeSetControlValue({
        conceptId: payload.control?.conceptId,
        value: payload.control?.value || ''
      })
    }
  })
```

**Comment by jianghuchaun-konan** [comment]
大佬，再请问您一个问题，executeRemoveControl这个api可以实现如同修改一样同步去删除控件吗

**Comment by jianghuchaun-konan** [comment]
感觉修改后在失活时并没有监听到数据变化，修改后在失活时拿到的数据是空的如下图
![image](https://github.com/user-attachments/assets/201458cb-b7c9-46ce-a8b8-b6643516a965)
![1732181068270](https://github.com/user-attachments/assets/05e6081e-0f0b-4020-a604-44adf771cb9d)
![1732181311704](https://github.com/user-attachments/assets/5c32416d-5c7b-4bc2-a9cf-e6bde4a10353)
另外有一种情况是在修改完第一个控件后立即去点击下一个控件就会报错
![1732181382658](https://github.com/user-attachments/assets/edc78dba-6099-470e-be97-3f74ace48b1a)

**Comment by Hufe921** [comment]
确定是最新提交记录的代码？本地没有复现

**Comment by jianghuchaun-konan** [comment]
> 确定是最新提交记录的代码？本地没有复现 /src/editor/core/draw/control/Control.ts=>initControl方法 截图一下

是最新的代码
![image](https://github.com/user-attachments/assets/664efea1-9e59-4b1f-896c-955b09de7391)
![image](https://github.com/user-attachments/assets/bc56895b-a998-4868-8ba7-9e741331eb61)

**Comment by Hufe921** [comment]
旧代码

**Comment by jianghuchaun-konan** [comment]
好的，是代码不完整，问题解决了，
