### ISSUE TITLE
图片元素能携带其他值吗？

### ISSUE THREAD

**Issue by lgdzz** [Hufe921/canvas-editor#887]
### What problem does this feature solve?

1. 比如图片元素除自己自身外，在附加一个换行符在图片前面或者后面，删除图片同时换行符也删除；
2. mode设置为打印模式控件的边界符能不能隐藏，或者有没有隐藏边界符的方法；
3. 指定页面不显示页眉页脚能不能加个配置，如果会影响高度计算，是否可以将需要不显示的页眉页脚页的内容设置为白色；
4. 页码的层级是否能高于浮动图片之上？

@Hufe921

**Comment by yzw20110902** [comment]
希望有个扩展值

**Comment by Hufe921** [comment]
1. 加换行符的目的是什么？
2. 边界符指的是什么
3. 有issue
4. 设置图片衬于文字下方

**Comment by Hufe921** [comment]
> 希望有个扩展值

每个元素都有扩展字段：extension

**Comment by lgdzz** [comment]
1. 为了图片能撑满整页需要将图片设置为浮于文字之上，加换行符是为了切换到下一页，弊端就是删除图片之后还是会留下换行符，如果能将换行符捆绑到图片上是否能解决？
2. 边界符是指控件的左右字符，如：{}，在打印模式下还是会出现。
3. 具体是哪个issue，怎么解决？
4. 浮动图片的目的是为了遮住某个内容，如果衬于文字下方就打不到遮住效果，页码不能被遮住。

**Comment by Hufe921** [comment]
1. 图片设置上下型环绕
2.待解决：#778
3.遮住内容的场景是什么
