### ISSUE TITLE
editor编辑器格式和HTML格式的互转

### ISSUE THREAD

**Issue by wudith** [Hufe921/canvas-editor#890]
### What problem does this feature solve?

需要将HTML格式的内容转成editor编辑器的json格式，两边互转，请问有提供这方面的api或者方法可调用的吗？

### What does the proposed API look like?

editor编辑器格式和HTML格式的互转的api

**Comment by Hufe921** [comment]
https://hufe.club/canvas-editor-docs/guide/api-common.html#getelementlistbyhtml

注意：html非编辑器使用数据结构转换会有信息丢失
