### ISSUE TITLE
字号，字体这种为什么一定要先选中文字后才能设置？

### ISSUE THREAD

**Issue by xuwencheng** [Hufe921/canvas-editor#892]
### version

0.9.96

### Link to minimal reproduction

https://hufe.club/canvas-editor/

### Steps to reproduce

在官方demo中，鼠标随便点击在某一段文字处，修改字号或者字体，没有任何变化

### What is expected?

像谷歌的在线文档或者wps那样，可以随处修改字号或者字体，不选中文字也可以。如果是选中文字后修改字号字体，则是对选中的文字生效；如果不选中文字时去修改字号字体，则是对下一次的文字输入生效

### What is actually happening?

只有选中文字后，修改字号字体才有效

**Comment by Hufe921** [comment]
重复：https://github.com/Hufe921/canvas-editor/issues/870
