### ISSUE TITLE
光标问题

### ISSUE THREAD

**Issue by dpl12** [Hufe921/canvas-editor#894]
### version

0.0.0

### Steps to reproduce

我用的不是最新的版本，发现光标在添加文本组件后不可见，请问大佬之后是怎么解决的？

### What is expected?

。

### What is actually happening?

。

**Comment by Hufe921** [comment]
无法复现，提供最小可复现demo

**Comment by dpl12** [comment]
> 无法复现，提供最小可复现demo

https://github.com/user-attachments/assets/7ead6062-26dc-4243-9a85-7de0d013f1f4

**Comment by Hufe921** [comment]
可以升级最新版本尝试，或自行跟踪光标定位代码运行，寻找问题

**Comment by dpl12** [comment]
好，谢谢
