### ISSUE TITLE
Insert area goes always to bottom of document, ignoring cursor position

### ISSUE THREAD

**Issue by lehno** [Hufe921/canvas-editor#898]
### version

0.9.97

### Steps to reproduce

Put cursor between 2 paragraphs and insert area element
<img width="886" alt="image" src="https://github.com/user-attachments/assets/c7313ba0-ad1d-453d-890e-52977cbfdbaa">

### What is expected?

It inserts the area between the 2 paragraphs

### What is actually happening?

It inserts always at the end of the document
<img width="865" alt="image" src="https://github.com/user-attachments/assets/33cc7ea8-6b80-4cbc-a9cf-07e32e0a3cfe">

**Comment by MzoroHaHa** [comment]
sorry, area only insert to the top or bottom.
