### ISSUE TITLE
Insert table inside area in FORM mode makes table uneditable

### ISSUE THREAD

**Issue by lehno** [Hufe921/canvas-editor#899]
### version

0.0.97

### Steps to reproduce

Create a page with area element
Change to form mode
Insert a table
<img width="893" alt="image" src="https://github.com/user-attachments/assets/acd56e73-95cf-4b14-9b24-73374b2564e3">

### What is expected?

User is able to type inside table rows inside a area element

### What is actually happening?

Table is uneditable, but if you change mode to design and back to form, then it is editable

**Comment by Hufe921** [comment]
Form mode allows only controls to be edited
