### ISSUE TITLE
低版本chrome无法显示完全，版本70 or 49

### ISSUE THREAD

**Issue by Helton-543** [Hufe921/canvas-editor#903]
### version

v0.9.97

### Steps to reproduce

使用70版本chrome，无报错，就只是显示部分空白，而且文档下方出现光标（inputarea输入框出现光标）

### What is expected?

显示正常

### What is actually happening?

无报错，就只是显示部分空白，而且文档下方出现光标（inputarea输入框出现光标），只显示了边框线和标题

**Comment by Hufe921** [comment]
不考虑旧版本
