### ISSUE TITLE
可以支持md数据渲染吗

### ISSUE THREAD

**Issue by 2919807875** [Hufe921/canvas-editor#904]
### What problem does this feature solve?

可以支持md数据渲染吗

### What does the proposed API look like?

可以支持md数据渲染吗

**Comment by MzoroHaHa** [comment]
编辑器有一个 executeSetHTML 方法，你可以试试先把markdown 转为 html,再用 executeSetHTML ;

**Comment by 2919807875** [comment]
> 编辑器有一个 executeSetHTML 方法，你可以试试先把markdown 转为 html,再用 executeSetHTML ;

好的，谢谢

**Comment by Hufe921** [comment]
可以参考：src/plugins/markdown
自己写个插件
