### ISSUE TITLE
跨行控件复制粘贴后变成纯文本

### ISSUE THREAD

**Issue by goodboy-yes** [Hufe921/canvas-editor#912]
### version

0.9.96

### Steps to reproduce

![1](https://github.com/user-attachments/assets/38dcc3b7-c8ba-41a9-aca5-0b5487fee7ad)

### What is expected?

粘贴后还是控件

### What is actually happening?

跨行控件复制粘贴后变成纯文本

**Comment by daria2023** [comment]
应该是跨行粘贴对比内容是出现的问题：[#913](https://github.com/Hufe921/canvas-editor/pull/913)

**Comment by Hufe921** [comment]
无法复现，确定复制的时候包含前后缀。
最新逻辑：选区包含完整的控件前后缀才是复制控件，否则仅复制控件内的值
https://github.com/Hufe921/canvas-editor/commit/750bf14428c7c7e55ed55f88c0c2b20f31f76e59

**Comment by daria2023** [comment]
hufe你好，你是macos系统吗，我刚在mac和win都试了一下，macos没有问题，windows系统我复制了这段文字![image](https://github.com/user-attachments/assets/14da4f13-bafd-4c79-94df-2680487db4a0)
粘贴之后效果![image](https://github.com/user-attachments/assets/85afe95f-8c30-4902-9620-7d7a15e94d7d)
这个我用jsonstringfy对比过两个字符串，换行符号不太一样。
