### ISSUE TITLE
下拉框多选，删除选项的部分问题

### ISSUE THREAD

**Issue by zhuyihe** [Hufe921/canvas-editor#914]
### version

0.9.97

### Steps to reproduce

下拉框选中状态未清除
 1.光标放在下拉框的起始位置
 2.删除选项
 3.ctrl+z撤销
 4.光标至于下拉框的最后面
 5.删除选项

### What is expected?

1.选项删除问题
  1.1.光标在选项上的时候，删除当前选项
  1.2.光标在下拉框的后面，依次删除选项
2. 下拉框选中状态未清除

### What is actually happening?

https://github.com/user-attachments/assets/dac2e4aa-3945-48b6-95d9-019ff08eaf49

**Comment by daria2023** [comment]
没有dispose这个下拉框吗？为什么我在demo中选中某个选项，这个下拉框会及时销毁，你这个是demo中复现的？

**Comment by zhuyihe** [comment]
> 没有dispose这个下拉框吗？为什么我在demo中选中某个选项，这个下拉框会及时销毁，你这个是demo中复现的？

官网的demo同样能复现出来，仔细看我的操作方式

**Comment by daria2023** [comment]
多选时可以复现出来，我试了一下，撤销操作后不管先点击哪一个选项进行取消操作，第一次点击都不会正常显示，不管是全选还是选几个，不知道撤销为什么会影响到。
