### ISSUE TITLE
executeSetControlProperties更改控件highlight出错

### ISSUE THREAD

**Issue by tuzixiangs** [Hufe921/canvas-editor#916]
### version

0.9.98

### Steps to reproduce

当一个控件有highlight值时,通过executeSetControlProperties修改控件highlight,可触发该bug

### What is expected?

通过executeSetControlProperties修改控件highlight时,能修改整个控件值

### What is actually happening?

具体原因: 
 formatElementList 函数执行时 element 中的highlight 覆盖了 controlDefaultStyle 中的highlight

复现视频: 

https://github.com/user-attachments/assets/198581f6-b10b-49a3-9eb7-c727fa385854

目解决方法: 
将 formatElementList 函数第467 行,...element换至...controlDefaultStyle上可解决当前问题.(不确定是否有其他影响)

https://github.com/user-attachments/assets/b6524140-d81f-4f64-9de3-3c93d4867a14

**Comment by Hufe921** [comment]
输入内容时会继承控件默认样式，元素样式优先于控件默认样式，因此你之后再设置默认高亮样式无效。
如果想修改控件样式可以：
```
    instance.command.executeSetControlValue({
      conceptId: '1',
      value: [
        {
          value: '123',
          highlight: 'red'
        }
      ]
    })
```
