### ISSUE TITLE
关于如何通过搜索选中文本自动插入批注

### ISSUE THREAD

**Issue by shawnada** [Hufe921/canvas-editor#922]
### What problem does this feature solve?

您好，我希望开发的功能是：
根据“关键字”搜索文本之后，自动利用“成组”功能实现批注

目前遇到的问题是：
1.搜索功能只能实现“高亮”，不能选中结果
2.成组功能必须要有选中的区域，才能创建批注

### What does the proposed API look like?

由于代码能力比较差，目前不知道怎么实现，不知道老师能否指点一下如何解决，或者通过哪些API相结合可以实现
另外请问是否有其他方式可以联系作者大哥呢

**Comment by Hufe921** [comment]
示例：
```
    const rangeList = instance.command.getKeywordRangeList('三天')
    rangeList.forEach(range => {
      range.startIndex -= 1
      instance.command.executeReplaceRange(range)
      instance.command.executeSetGroup()
    })
```

**Comment by shawnada** [comment]
![image](https://github.com/user-attachments/assets/f09eadf2-8011-492b-a518-ed845480963b)
解决了，感谢
