### ISSUE TITLE
当一页全部是table时，从右侧拖动控件，释放到表格里，光标会跳动，导致滚动

### ISSUE THREAD

**Issue by bigbear1007** [Hufe921/canvas-editor#926]
### What problem does this feature solve?

当一页全部是table时，从右侧控件列表tree拖动控件，释放到表格里，光标会定位到表格最右侧并在拖动到editor的时候跳动，导致页面滚动。有没有办法能够在拖动控件的时候不让他滚动，换个模式？还是禁止光标之类的？

### What does the proposed API look like?

无

https://github.com/user-attachments/assets/2dded9cf-b91b-469f-88f4-7e7c7b2b5577

**Comment by Hufe921** [comment]
command.getValue 发一下编辑器数据

**Comment by bigbear1007** [comment]
[data.zip](https://github.com/user-attachments/files/18104471/data.zip)
在这里
