### ISSUE TITLE
现在是否不支持表格里面嵌套表格

### ISSUE THREAD

**Issue by zhang3arosy** [Hufe921/canvas-editor#929]
### What problem does this feature solve?

现在需要动态生成数据,因为数据是数组形式，并且数组下面还有数组，所以，需要表格里面嵌套一个表格。好像0.9.98版本不支持这样操作。

### What does the proposed API look like?

我想要内嵌版本，使得支持多层for循环

**Comment by Hufe921** [comment]
理论上渲染是支持的，但是交互等很多细节不支持
#650
