### ISSUE TITLE
官方组件的流程图组件使用0.9.98版本主库时，用executeUpdateElementById更新图片value时不生效

### ISSUE THREAD

**Issue by Erlin0220** [Hufe921/canvas-editor#933]
### version

0.9.98

### Steps to reproduce

https://codesandbox.io/p/sandbox/happy-robinson-ftvy82?from-embed=&workspaceId=ws_Aac7TN8QwYP1nXZqPFp3CU

### What is expected?

希望可以修复

### What is actually happening?

executeUpdateElementById更新图片value时不生效

**Comment by Hufe921** [comment]
等待版本升级

**Comment by Erlin0220** [comment]
你好，可以更新一下npm包吗？
