### ISSUE TITLE
本地word导入的格式问题

### ISSUE THREAD

**Issue by shawnada** [Hufe921/canvas-editor#935]
### version

最新

### Steps to reproduce

您好，我有一个导入本地word（带格式）的需求：
1.例如word原文如下
![image](https://github.com/user-attachments/assets/04d78488-baeb-45d5-a438-d2791f6b2237)

2.通过官方插件直接导入word效果如下，丢失了较多格式，“缩进”，“标题大小”“居中等等”
![image](https://github.com/user-attachments/assets/9d44c3b7-c42a-4ae3-b311-d3cd39bc4d3c)

3.于是我尝试将word转换成html后，用executeSetHTML导入，但仍然丢失了“缩进”
![image](https://github.com/user-attachments/assets/5ba17cf2-6375-4277-bec4-e5d4e288b77b)

4.转换后的html原文是有缩进的内容的
[转换后.txt](https://github.com/user-attachments/files/18176463/default.txt)

### What is expected?

1.如果官方的导入word能支持格式更好，但是似乎会比较麻烦
2.希望修复一下导入html对格式的支持，让“缩进”能够正常显示
谢谢

### What is actually happening?

1

**Comment by Hufe921** [comment]
参考插件：https://github.com/Hufe921/canvas-editor-plugin
自行扩展
