### ISSUE TITLE
可否可以给控件加一个字段key,使得提取想要的数据更加方便

### ISSUE THREAD

**Issue by 2071003642** [Hufe921/canvas-editor#938]
### What problem does this feature solve?

1.给控件加一个字段key,就可以从数据数组里面更快更精准的提取想要的数据，方便数据处理。
2.同时有了key,同时可以更好的给控件赋默认值

### What does the proposed API look like?

原有数据结构示例如下：
{
    "value": "",
    "type": "control",
    "control": {
        "type": "date",
        "dateFormat": "yyyy-MM-dd hh:mm:ss",
        "value": [],
        "placeholder": "时间"
    }
}
计划数据结构如下:
{
    "value": "",
    "type": "control",
    "control": {
        "type": "date",
        "dateFormat": "yyyy-MM-dd hh:mm:ss",
        "value": [],
        "key":"time"
        "placeholder": "时间"
    }
}

**Comment by wwqwq2313** [comment]
Hello, we tried to solve the issue.

This is what we did:

Added a 'key' field of type string to the IControlBasic interface in the Control.ts file. This new field will allow for easier and more precise data extraction and default value assignment for controls.

You can review changes in this commit: https://github.com/wwqwq2313/Hufe921-canvas-editor-938/commit/7e1f6c6402f6f381bf0ce67cae5e17af03d8f208.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

Latta AI seeks to solve problems in open source projects as part of its mission to support developers around the world. Learn more about our mission at https://latta.ai/ourmission . If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by Hufe921** [comment]
id或conceptId 已经可以满足
