### ISSUE TITLE
复制word 粘贴样式错乱

### ISSUE THREAD

**Issue by buliangrengithub** [Hufe921/canvas-editor#939]
### version

v0.9

### Steps to reproduce

![1734944379870](https://github.com/user-attachments/assets/6cd6f3dc-160e-470b-84c6-99f21abf09c4)     复制word的表格粘贴到编辑器中，修改word内容  ，就出现这个问题，样式错乱

### What is expected?

有什么修复方法

### What is actually happening?

![1734944379870](https://github.com/user-attachments/assets/6cd6f3dc-160e-470b-84c6-99f21abf09c4)     复制word的表格粘贴到编辑器中，修改word内容  ，就出现这个问题，样式错乱

**Comment by Hufe921** [comment]
https://github.com/Hufe921/canvas-editor/issues/41
