### ISSUE TITLE
Tab占位后，设置样式无效（字体字号加粗等）

### ISSUE THREAD

**Issue by Tiny-Dong** [Hufe921/canvas-editor#942]
### What problem does this feature solve?

![chrome-capture-2024-11-24 (2)](https://github.com/user-attachments/assets/13978be5-2128-40f3-97cf-c0badb08330f)

### What does the proposed API look like?

如上图

**Comment by fionazs** [comment]
你好，尝试了一下，这个问题似乎没有解决，在tab键后，已经选择的字体样式如加粗、删除线等，就没有了
