### ISSUE TITLE
引入不进来插件

### ISSUE THREAD

**Issue by sjqit** [Hufe921/canvas-editor#944]
确定npm添加成功了canvas-editor-plugin-docx  但是import此插件就报错。。。。。  实在不知道为什么了！
![image](https://github.com/user-attachments/assets/766e0115-6c21-4faa-88fb-78b90565b809)
![image](https://github.com/user-attachments/assets/7e503ef6-3cbc-45ed-bce8-5251f93fb278)
![image](https://github.com/user-attachments/assets/35f9ba90-1f6c-4bea-b834-18603452a74b)

**Comment by Hufe921** [comment]
尝试重新安装，并重新运行。
参考demo：https://hufe.club/canvas-editor-plugin/

如还有问题，提供最小可复现demo
