### ISSUE TITLE
疑惑:为什么每次init完都会再旁边额外生成一个文档呢？

### ISSUE THREAD

**Issue by itjbh** [Hufe921/canvas-editor#949]
### What problem does this feature solve?

![1](https://github.com/user-attachments/assets/0e3b00d3-2168-49e4-b138-af9ac3dcafda)
代码: 1.监听父级的docJson，
    docJson: {
      handler (val) {
        if(val) {
          console.log("val----------",val)
          this.init()
        }
      },
    }

2.然后调用这个初始化的方法
init(){
      this.$nextTick(() => {    

          const isApple = typeof navigator !== 'undefined' && /Mac OS X/.test(navigator.userAgent)

            //加载编辑器界面
            const instance =  new Editor(
                document.querySelector('.canvas-editor'),
                {
                  header: this.header,
                  main: this.docJson,
                  footer: this.footer
                },
                this.options
              )
            

          this.editorRef = instance;
          // cypress使用
          Reflect.set(window, 'editor', instance)}）}

### What does the proposed API look like?

使用destory()方法似乎也不行，因为在之前无法锁定instance对象

**Comment by Hufe921** [comment]
应该和框架无关，提供最小复现demo我看一下你如何使用的吧，如https://codesandbox.io/

**Comment by itjbh** [comment]
最小复现demo啥意思

**Comment by itjbh** [comment]
解决了，谢谢
