### ISSUE TITLE
多倍行间距时，文字位置问题

### ISSUE THREAD

**Issue by 403554707** [Hufe921/canvas-editor#950]
![image](https://github.com/user-attachments/assets/377df363-ea13-4024-aa96-cfc3af415886)
当我设置行间距以后，内容是居中展示。但是word的格式是顶部对齐。请问这个要怎么改动？
![image](https://github.com/user-attachments/assets/54a47f70-7dd0-4715-b4af-a92f5c06ba80)

**Comment by Hufe921** [comment]
wps默认也是这个样式，你想要的效果可以在第二行再设置行间距达到这个效果
<img width="678" alt="image" src="https://github.com/user-attachments/assets/4d4a5759-a2a4-4080-8304-fc91aec2391a" />
