### ISSUE TITLE
复制较长内容到表格后，显示异常

### ISSUE THREAD

**Issue by fionazs** [Hufe921/canvas-editor#952]
### version

-

### Steps to reproduce

复制较长的一段文本内容到某个单元格内
<img width="627" alt="63339383f1dd3f73b522290f0f21c31" src="https://github.com/user-attachments/assets/4c7bdd8c-1e9f-4866-b7f2-0a33211cea53" />
<img width="620" alt="d32c94ee141f7dc5397ac2e864e1431" src="https://github.com/user-attachments/assets/d62a451b-8742-4c88-ac75-9fdd38b096da" />

### What is expected?

显示正确，复制的内容能在表格的某一行内完整展示

### What is actually happening?

异常分页，且表格显示异常

**Comment by Hufe921** [comment]
#41
