### ISSUE TITLE
疑问：保存是用instance.command.getValue()的数据还是用instance.command.getHTML()的数据呢？

### ISSUE THREAD

**Issue by itjbh** [Hufe921/canvas-editor#953]
### What problem does this feature solve?

回显如果是getValue()回显数据是放到new Editor的第二个参数中吗？如果是getHTML()是放在new Editor第一个参数吗

### What does the proposed API look like?

使用canvas组件，不同界面点击进去会出现2个界面，
![image](https://github.com/user-attachments/assets/4c4f7834-74be-4b30-9edf-f9ca9b0b8dde)
我看document.querySelector('.canvas-editor');会显示
![image](https://github.com/user-attachments/assets/b32f909a-6a4a-4080-8275-352a5991f6b5)

**Comment by Hufe921** [comment]
要通过getValue获取结构化数据，setValue或实例化编辑器时传入结构化数据
getHTML setHTML仅作为后备方式不建议使用

https://hufe.club/canvas-editor-docs/guide/start.html
